<?php

namespace AlibabaCloud\Green\V20170823;

use AlibabaCloud\ApiResolverTrait;

/**
 * @deprecated
 *
 * @method static CreateCdiBag createCdiBag(array $options = [])
 * @method static CreateCdiBaseBag createCdiBaseBag(array $options = [])
 * @method static CreateImageLib createImageLib(array $options = [])
 * @method static CreateKeyword createKeyword(array $options = [])
 * @method static CreateKeywordLib createKeywordLib(array $options = [])
 * @method static CreateWebSiteInstance createWebSiteInstance(array $options = [])
 * @method static CreateWebsiteIndexPageBaseline createWebsiteIndexPageBaseline(array $options = [])
 * @method static DeleteImageFromLib deleteImageFromLib(array $options = [])
 * @method static DeleteImageLib deleteImageLib(array $options = [])
 * @method static DeleteKeyword deleteKeyword(array $options = [])
 * @method static DeleteKeywordLib deleteKeywordLib(array $options = [])
 * @method static DeleteNotificationContacts deleteNotificationContacts(array $options = [])
 * @method static DescribeAppInfo describeAppInfo(array $options = [])
 * @method static DescribeAppUploadInfo describeAppUploadInfo(array $options = [])
 * @method static DescribeAuditContent describeAuditContent(array $options = [])
 * @method static DescribeAuditContentItem describeAuditContentItem(array $options = [])
 * @method static DescribeAuditSetting describeAuditSetting(array $options = [])
 * @method static DescribeImageFromLib describeImageFromLib(array $options = [])
 * @method static DescribeImageLib describeImageLib(array $options = [])
 * @method static DescribeImageUploadInfo describeImageUploadInfo(array $options = [])
 * @method static DescribeKeyword describeKeyword(array $options = [])
 * @method static DescribeKeywordLib describeKeywordLib(array $options = [])
 * @method static DescribeNotificationSetting describeNotificationSetting(array $options = [])
 * @method static DescribeOpenApiUsage describeOpenApiUsage(array $options = [])
 * @method static DescribeOssIncrementCheckSetting describeOssIncrementCheckSetting(array $options = [])
 * @method static DescribeOssIncrementOverview describeOssIncrementOverview(array $options = [])
 * @method static DescribeOssIncrementStats describeOssIncrementStats(array $options = [])
 * @method static DescribeOssResultItems describeOssResultItems(array $options = [])
 * @method static DescribeOssStockStatus describeOssStockStatus(array $options = [])
 * @method static DescribeSdkUrl describeSdkUrl(array $options = [])
 * @method static DescribeUpdatePackageResult describeUpdatePackageResult(array $options = [])
 * @method static DescribeUploadInfo describeUploadInfo(array $options = [])
 * @method static DescribeUserStatus describeUserStatus(array $options = [])
 * @method static DescribeWebsiteIndexPageBaseline describeWebsiteIndexPageBaseline(array $options = [])
 * @method static DescribeWebsiteInstance describeWebsiteInstance(array $options = [])
 * @method static DescribeWebsiteInstanceId describeWebsiteInstanceId(array $options = [])
 * @method static DescribeWebsiteInstanceKeyUrl describeWebsiteInstanceKeyUrl(array $options = [])
 * @method static DescribeWebsiteScanResult describeWebsiteScanResult(array $options = [])
 * @method static DescribeWebsiteScanResultDetail describeWebsiteScanResultDetail(array $options = [])
 * @method static DescribeWebsiteStat describeWebsiteStat(array $options = [])
 * @method static DescribeWebsiteVerifyInfo describeWebsiteVerifyInfo(array $options = [])
 * @method static ExportOssResult exportOssResult(array $options = [])
 * @method static GreenApiResolver greenApiResolver(array $options = [])
 * @method static MarkAuditContent markAuditContent(array $options = [])
 * @method static MarkAuditContentItem markAuditContentItem(array $options = [])
 * @method static MarkOssResult markOssResult(array $options = [])
 * @method static MarkWebsiteScanResult markWebsiteScanResult(array $options = [])
 * @method static RefundCdiBag refundCdiBag(array $options = [])
 * @method static RefundCdiBaseBag refundCdiBaseBag(array $options = [])
 * @method static RefundWebSiteInstance refundWebSiteInstance(array $options = [])
 * @method static RenewWebSiteInstance renewWebSiteInstance(array $options = [])
 * @method static SendVerifyCodeToEmail sendVerifyCodeToEmail(array $options = [])
 * @method static SendVerifyCodeToPhone sendVerifyCodeToPhone(array $options = [])
 * @method static SendWebsiteFeedback sendWebsiteFeedback(array $options = [])
 * @method static UpdateAppPackage updateAppPackage(array $options = [])
 * @method static UpdateAuditSetting updateAuditSetting(array $options = [])
 * @method static UpdateImageLib updateImageLib(array $options = [])
 * @method static UpdateKeywordLib updateKeywordLib(array $options = [])
 * @method static UpdateNotificationSetting updateNotificationSetting(array $options = [])
 * @method static UpdateOssIncrementCheckSetting updateOssIncrementCheckSetting(array $options = [])
 * @method static UpdateOssStockStatus updateOssStockStatus(array $options = [])
 * @method static UpdateWebsiteInstance updateWebsiteInstance(array $options = [])
 * @method static UpdateWebsiteInstanceKeyUrl updateWebsiteInstanceKeyUrl(array $options = [])
 * @method static UpdateWebsiteInstanceStatus updateWebsiteInstanceStatus(array $options = [])
 * @method static UpgradeCdiBaseBag upgradeCdiBaseBag(array $options = [])
 * @method static UploadImageToLib uploadImageToLib(array $options = [])
 * @method static VerifyEmail verifyEmail(array $options = [])
 * @method static VerifyPhone verifyPhone(array $options = [])
 * @method static VerifyWebsiteInstance verifyWebsiteInstance(array $options = [])
 */
class Green
{
    use ApiResolverTrait;
}
