<?php

namespace AlibabaCloud\Green\V20170823;

use AlibabaCloud\ApiResolverTrait;

/**
 * Resolve Api based on the method name.
 *
 * @method DescribeOssCallbackSetting describeOssCallbackSetting(array $options = [])
 * @method UpdateOssCallbackSetting updateOssCallbackSetting(array $options = [])
 * @method VerifyCustomOcrTemplate verifyCustomOcrTemplate(array $options = [])
 * @method UpdateCustomOcrTemplate updateCustomOcrTemplate(array $options = [])
 * @method DescribeCustomOcrTemplate describeCustomOcrTemplate(array $options = [])
 * @method DeleteCustomOcrTemplate deleteCustomOcrTemplate(array $options = [])
 * @method CreatCustomOcrTemplate creatCustomOcrTemplate(array $options = [])
 * @method MarkAuditContentItem markAuditContentItem(array $options = [])
 * @method DescribeAuditContentItem describeAuditContentItem(array $options = [])
 * @method DeleteNotificationContacts deleteNotificationContacts(array $options = [])
 * @method DescribeUpdatePackageResult describeUpdatePackageResult(array $options = [])
 * @method DescribeUploadInfo describeUploadInfo(array $options = [])
 * @method DescribeAppUploadInfo describeAppUploadInfo(array $options = [])
 * @method DescribeSdkUrl describeSdkUrl(array $options = [])
 * @method DescribeAppInfo describeAppInfo(array $options = [])
 * @method UpdateAppPackage updateAppPackage(array $options = [])
 * @method RefundCdiBaseBag refundCdiBaseBag(array $options = [])
 * @method RefundCdiBag refundCdiBag(array $options = [])
 * @method RefundWebSiteInstance refundWebSiteInstance(array $options = [])
 * @method UpgradeCdiBaseBag upgradeCdiBaseBag(array $options = [])
 * @method CreateCdiBaseBag createCdiBaseBag(array $options = [])
 * @method CreateCdiBag createCdiBag(array $options = [])
 * @method RenewWebSiteInstance renewWebSiteInstance(array $options = [])
 * @method CreateWebSiteInstance createWebSiteInstance(array $options = [])
 * @method DescribeOssIncrementCheckSetting describeOssIncrementCheckSetting(array $options = [])
 * @method UpdateOssIncrementCheckSetting updateOssIncrementCheckSetting(array $options = [])
 * @method MarkOssResult markOssResult(array $options = [])
 * @method DescribeOssIncrementOverview describeOssIncrementOverview(array $options = [])
 * @method ExportOssResult exportOssResult(array $options = [])
 * @method UpdateOssStockStatus updateOssStockStatus(array $options = [])
 * @method DescribeOssStockStatus describeOssStockStatus(array $options = [])
 * @method DescribeOssIncrementStats describeOssIncrementStats(array $options = [])
 * @method DescribeOssResultItems describeOssResultItems(array $options = [])
 * @method UpdateWebsiteInstanceKeyUrl updateWebsiteInstanceKeyUrl(array $options = [])
 * @method DescribeWebsiteIndexPageBaseline describeWebsiteIndexPageBaseline(array $options = [])
 * @method CreateWebsiteIndexPageBaseline createWebsiteIndexPageBaseline(array $options = [])
 * @method DescribeWebsiteInstanceId describeWebsiteInstanceId(array $options = [])
 * @method SendWebsiteFeedback sendWebsiteFeedback(array $options = [])
 * @method DescribeWebsiteInstance describeWebsiteInstance(array $options = [])
 * @method MarkWebsiteScanResult markWebsiteScanResult(array $options = [])
 * @method UpdateWebsiteInstance updateWebsiteInstance(array $options = [])
 * @method UpdateWebsiteInstanceStatus updateWebsiteInstanceStatus(array $options = [])
 * @method DescribeWebsiteVerifyInfo describeWebsiteVerifyInfo(array $options = [])
 * @method DescribeWebsiteStat describeWebsiteStat(array $options = [])
 * @method DescribeWebsiteScanResultDetail describeWebsiteScanResultDetail(array $options = [])
 * @method DescribeWebsiteScanResult describeWebsiteScanResult(array $options = [])
 * @method VerifyWebsiteInstance verifyWebsiteInstance(array $options = [])
 * @method DescribeWebsiteInstanceKeyUrl describeWebsiteInstanceKeyUrl(array $options = [])
 * @method SendVerifyCodeToPhone sendVerifyCodeToPhone(array $options = [])
 * @method UpdateNotificationSetting updateNotificationSetting(array $options = [])
 * @method SendVerifyCodeToEmail sendVerifyCodeToEmail(array $options = [])
 * @method VerifyEmail verifyEmail(array $options = [])
 * @method VerifyPhone verifyPhone(array $options = [])
 * @method DescribeNotificationSetting describeNotificationSetting(array $options = [])
 * @method DescribeKeywordLib describeKeywordLib(array $options = [])
 * @method DescribeKeyword describeKeyword(array $options = [])
 * @method UpdateKeywordLib updateKeywordLib(array $options = [])
 * @method DeleteKeyword deleteKeyword(array $options = [])
 * @method DeleteKeywordLib deleteKeywordLib(array $options = [])
 * @method CreateKeywordLib createKeywordLib(array $options = [])
 * @method CreateKeyword createKeyword(array $options = [])
 * @method UpdateImageLib updateImageLib(array $options = [])
 * @method UploadImageToLib uploadImageToLib(array $options = [])
 * @method DescribeImageUploadInfo describeImageUploadInfo(array $options = [])
 * @method DescribeAuditSetting describeAuditSetting(array $options = [])
 * @method DeleteImageFromLib deleteImageFromLib(array $options = [])
 * @method DeleteImageLib deleteImageLib(array $options = [])
 * @method CreateImageLib createImageLib(array $options = [])
 * @method DescribeUserStatus describeUserStatus(array $options = [])
 * @method DescribeImageLib describeImageLib(array $options = [])
 * @method DescribeImageFromLib describeImageFromLib(array $options = [])
 * @method DescribeOpenApiUsage describeOpenApiUsage(array $options = [])
 * @method DescribeAuditContent describeAuditContent(array $options = [])
 * @method MarkAuditContent markAuditContent(array $options = [])
 * @method UpdateAuditSetting updateAuditSetting(array $options = [])
 */
class GreenApiResolver
{
    use ApiResolverTrait;
}
