<?php

namespace AlibabaCloud\Slb;

use AlibabaCloud\ApiResolverTrait;

/**
 * Find the specified Api of the Slb based on the method name as the Api name.
 *
 * @package   AlibabaCloud\Slb
 *
 * @method V20140515\AddAccessControlListEntry addAccessControlListEntry(array $options = [])
 * @method V20140515\AddBackendServers addBackendServers(array $options = [])
 * @method V20140515\AddBackendServersAsyn addBackendServersAsyn(array $options = [])
 * @method V20140515\AddListenerWhiteListItem addListenerWhiteListItem(array $options = [])
 * @method V20140515\AddTags addTags(array $options = [])
 * @method V20140515\AddVServerGroupBackendServers addVServerGroupBackendServers(array $options = [])
 * @method V20140515\AddVServerGroupBackendServersAsyn addVServerGroupBackendServersAsyn(array $options = [])
 * @method V20140515\CreateAccessControlList createAccessControlList(array $options = [])
 * @method V20140515\CreateDomainExtension createDomainExtension(array $options = [])
 * @method V20140515\CreateLoadBalancer createLoadBalancer(array $options = [])
 * @method V20140515\CreateLoadBalancerHTTPListener createLoadBalancerHTTPListener(array $options = [])
 * @method V20140515\CreateLoadBalancerHTTPListenerAsyn createLoadBalancerHTTPListenerAsyn(array $options = [])
 * @method V20140515\CreateLoadBalancerHTTPSListener createLoadBalancerHTTPSListener(array $options = [])
 * @method V20140515\CreateLoadBalancerHTTPSListenerAsyn createLoadBalancerHTTPSListenerAsyn(array $options = [])
 * @method V20140515\CreateLoadBalancerOld createLoadBalancerOld(array $options = [])
 * @method V20140515\CreateLoadBalancerTCPListener createLoadBalancerTCPListener(array $options = [])
 * @method V20140515\CreateLoadBalancerTCPListenerAsyn createLoadBalancerTCPListenerAsyn(array $options = [])
 * @method V20140515\CreateLoadBalancerUDPListener createLoadBalancerUDPListener(array $options = [])
 * @method V20140515\CreateLoadBalancerUDPListenerAsyn createLoadBalancerUDPListenerAsyn(array $options = [])
 * @method V20140515\CreateMasterSlaveServerGroup createMasterSlaveServerGroup(array $options = [])
 * @method V20140515\CreateMasterSlaveVServerGroup createMasterSlaveVServerGroup(array $options = [])
 * @method V20140515\CreateRule createRule(array $options = [])
 * @method V20140515\CreateRules createRules(array $options = [])
 * @method V20140515\CreateVServerGroup createVServerGroup(array $options = [])
 * @method V20140515\DeleteAccessControlList deleteAccessControlList(array $options = [])
 * @method V20140515\DeleteCACertificate deleteCACertificate(array $options = [])
 * @method V20140515\DeleteDomainExtension deleteDomainExtension(array $options = [])
 * @method V20140515\DeleteLoadBalancer deleteLoadBalancer(array $options = [])
 * @method V20140515\DeleteLoadBalancerListener deleteLoadBalancerListener(array $options = [])
 * @method V20140515\DeleteMasterSlaveServerGroup deleteMasterSlaveServerGroup(array $options = [])
 * @method V20140515\DeleteMasterSlaveVServerGroup deleteMasterSlaveVServerGroup(array $options = [])
 * @method V20140515\DeleteRule deleteRule(array $options = [])
 * @method V20140515\DeleteRules deleteRules(array $options = [])
 * @method V20140515\DeleteServerCertificate deleteServerCertificate(array $options = [])
 * @method V20140515\DeleteVServerGroup deleteVServerGroup(array $options = [])
 * @method V20140515\DescribeAccessControlListAttribute describeAccessControlListAttribute(array $options = [])
 * @method V20140515\DescribeAccessControlLists describeAccessControlLists(array $options = [])
 * @method V20140515\DescribeAutoRenewStatus describeAutoRenewStatus(array $options = [])
 * @method V20140515\DescribeCACertificates describeCACertificates(array $options = [])
 * @method V20140515\DescribeCertificateRelatedListenersAndRules describeCertificateRelatedListenersAndRules(array $options = [])
 * @method V20140515\DescribeDomainExtensions describeDomainExtensions(array $options = [])
 * @method V20140515\DescribeHealthStatus describeHealthStatus(array $options = [])
 * @method V20140515\DescribeIdleInstances describeIdleInstances(array $options = [])
 * @method V20140515\DescribeListenerAccessControlAttribute describeListenerAccessControlAttribute(array $options = [])
 * @method V20140515\DescribeLoadBalancerAttribute describeLoadBalancerAttribute(array $options = [])
 * @method V20140515\DescribeLoadBalancerAutoReleaseTime describeLoadBalancerAutoReleaseTime(array $options = [])
 * @method V20140515\DescribeLoadBalancerBackendServers describeLoadBalancerBackendServers(array $options = [])
 * @method V20140515\DescribeLoadBalancerHTTPListenerAttribute describeLoadBalancerHTTPListenerAttribute(array $options = [])
 * @method V20140515\DescribeLoadBalancerHTTPSListenerAttribute describeLoadBalancerHTTPSListenerAttribute(array $options = [])
 * @method V20140515\DescribeLoadBalancerTCPListenerAttribute describeLoadBalancerTCPListenerAttribute(array $options = [])
 * @method V20140515\DescribeLoadBalancerUDPListenerAttribute describeLoadBalancerUDPListenerAttribute(array $options = [])
 * @method V20140515\DescribeLoadBalancers describeLoadBalancers(array $options = [])
 * @method V20140515\DescribeLoadBalancersPro describeLoadBalancersPro(array $options = [])
 * @method V20140515\DescribeLoadBalancersRelatedEcs describeLoadBalancersRelatedEcs(array $options = [])
 * @method V20140515\DescribeMasterSlaveServerGroupAttribute describeMasterSlaveServerGroupAttribute(array $options = [])
 * @method V20140515\DescribeMasterSlaveServerGroups describeMasterSlaveServerGroups(array $options = [])
 * @method V20140515\DescribeMasterSlaveVServerGroupAttribute describeMasterSlaveVServerGroupAttribute(array $options = [])
 * @method V20140515\DescribeMasterSlaveVServerGroups describeMasterSlaveVServerGroups(array $options = [])
 * @method V20140515\DescribeRegions describeRegions(array $options = [])
 * @method V20140515\DescribeRuleAttribute describeRuleAttribute(array $options = [])
 * @method V20140515\DescribeRuleAttributes describeRuleAttributes(array $options = [])
 * @method V20140515\DescribeRules describeRules(array $options = [])
 * @method V20140515\DescribeServerCertificates describeServerCertificates(array $options = [])
 * @method V20140515\DescribeSlbQuotas describeSlbQuotas(array $options = [])
 * @method V20140515\DescribeTags describeTags(array $options = [])
 * @method V20140515\DescribeVServerGroupAttribute describeVServerGroupAttribute(array $options = [])
 * @method V20140515\DescribeVServerGroupAttributes describeVServerGroupAttributes(array $options = [])
 * @method V20140515\DescribeVServerGroups describeVServerGroups(array $options = [])
 * @method V20140515\DescribeZones describeZones(array $options = [])
 * @method V20140515\InnerQueryQuotaConfig innerQueryQuotaConfig(array $options = [])
 * @method V20140515\ModifyLoadBalancerInstanceSpec modifyLoadBalancerInstanceSpec(array $options = [])
 * @method V20140515\ModifyLoadBalancerInternetSpec modifyLoadBalancerInternetSpec(array $options = [])
 * @method V20140515\ModifyLoadBalancerPayType modifyLoadBalancerPayType(array $options = [])
 * @method V20140515\ModifyLoadBalancerResourceGroup modifyLoadBalancerResourceGroup(array $options = [])
 * @method V20140515\ModifyLoadBalancerVPCAddress modifyLoadBalancerVPCAddress(array $options = [])
 * @method V20140515\ModifyVServerGroupBackendServers modifyVServerGroupBackendServers(array $options = [])
 * @method V20140515\ModifyVServerGroupBackendServersAsyn modifyVServerGroupBackendServersAsyn(array $options = [])
 * @method V20140515\MoveResourceGroup moveResourceGroup(array $options = [])
 * @method V20140515\RemoveAccessControlListEntry removeAccessControlListEntry(array $options = [])
 * @method V20140515\RemoveBackendServers removeBackendServers(array $options = [])
 * @method V20140515\RemoveBackendServersAsyn removeBackendServersAsyn(array $options = [])
 * @method V20140515\RemoveListenerWhiteListItem removeListenerWhiteListItem(array $options = [])
 * @method V20140515\RemoveTags removeTags(array $options = [])
 * @method V20140515\RemoveVServerGroupBackendServer removeVServerGroupBackendServer(array $options = [])
 * @method V20140515\RemoveVServerGroupBackendServers removeVServerGroupBackendServers(array $options = [])
 * @method V20140515\RemoveVServerGroupBackendServersAsyn removeVServerGroupBackendServersAsyn(array $options = [])
 * @method V20140515\SetAccessControlListAttribute setAccessControlListAttribute(array $options = [])
 * @method V20140515\SetAccessControlListAttributeImpl setAccessControlListAttributeImpl(array $options = [])
 * @method V20140515\SetAutoRenewStatus setAutoRenewStatus(array $options = [])
 * @method V20140515\SetBackendServers setBackendServers(array $options = [])
 * @method V20140515\SetBackendServersAsyn setBackendServersAsyn(array $options = [])
 * @method V20140515\SetCACertificateName setCACertificateName(array $options = [])
 * @method V20140515\SetDomainExtensionAttribute setDomainExtensionAttribute(array $options = [])
 * @method V20140515\SetListenerAccessControlStatus setListenerAccessControlStatus(array $options = [])
 * @method V20140515\SetLoadBalancerAutoReleaseTime setLoadBalancerAutoReleaseTime(array $options = [])
 * @method V20140515\SetLoadBalancerHTTPListenerAttribute setLoadBalancerHTTPListenerAttribute(array $options = [])
 * @method V20140515\SetLoadBalancerHTTPSListenerAttribute setLoadBalancerHTTPSListenerAttribute(array $options = [])
 * @method V20140515\SetLoadBalancerName setLoadBalancerName(array $options = [])
 * @method V20140515\SetLoadBalancerStatus setLoadBalancerStatus(array $options = [])
 * @method V20140515\SetLoadBalancerTCPListenerAttribute setLoadBalancerTCPListenerAttribute(array $options = [])
 * @method V20140515\SetLoadBalancerUDPListenerAttribute setLoadBalancerUDPListenerAttribute(array $options = [])
 * @method V20140515\SetRule setRule(array $options = [])
 * @method V20140515\SetServerCertificateName setServerCertificateName(array $options = [])
 * @method V20140515\SetVServerGroup setVServerGroup(array $options = [])
 * @method V20140515\SetVServerGroupAttribute setVServerGroupAttribute(array $options = [])
 * @method V20140515\SetVServerGroupAttributeAsyn setVServerGroupAttributeAsyn(array $options = [])
 * @method V20140515\StartLoadBalancerListener startLoadBalancerListener(array $options = [])
 * @method V20140515\StopLoadBalancerListener stopLoadBalancerListener(array $options = [])
 * @method V20140515\UploadCACertificate uploadCACertificate(array $options = [])
 * @method V20140515\UploadServerCertificate uploadServerCertificate(array $options = [])
 */
class SlbV20140515ApiResolver
{
    use ApiResolverTrait;

    /**
     * @var string
     */
    protected $namespace = 'AlibabaCloud\\Slb\\V20140515';
}
