<?php

namespace AlibabaCloud\Iot\V20180120;

use AlibabaCloud\ApiResolverTrait;

/**
 * Resolve Api based on the method name.
 *
 * @method RamAuth ramAuth(array $options = [])
 * @method SetDeviceDesiredProperty setDeviceDesiredProperty(array $options = [])
 * @method QueryDeviceDesiredProperty queryDeviceDesiredProperty(array $options = [])
 * @method IdleService idleService(array $options = [])
 * @method CreateProductTags createProductTags(array $options = [])
 * @method UpdateProductTags updateProductTags(array $options = [])
 * @method ListProductTags listProductTags(array $options = [])
 * @method ListProductByTags listProductByTags(array $options = [])
 * @method DeleteProductTags deleteProductTags(array $options = [])
 * @method QueryDeviceGroupByTags queryDeviceGroupByTags(array $options = [])
 * @method QueryDeviceListByDeviceGroup queryDeviceListByDeviceGroup(array $options = [])
 * @method QuerySuperDeviceGroup querySuperDeviceGroup(array $options = [])
 * @method QueryDeviceByTags queryDeviceByTags(array $options = [])
 * @method SetDeviceGroupTags setDeviceGroupTags(array $options = [])
 * @method InvokeThingsService invokeThingsService(array $options = [])
 * @method SetDevicesProperty setDevicesProperty(array $options = [])
 * @method QueryDevicePropertiesData queryDevicePropertiesData(array $options = [])
 * @method QueryAppDeviceList queryAppDeviceList(array $options = [])
 * @method UpdateDeviceGroup updateDeviceGroup(array $options = [])
 * @method QueryDeviceGroupTagList queryDeviceGroupTagList(array $options = [])
 * @method QueryDeviceGroupList queryDeviceGroupList(array $options = [])
 * @method QueryDeviceGroupInfo queryDeviceGroupInfo(array $options = [])
 * @method QueryDeviceGroupByDevice queryDeviceGroupByDevice(array $options = [])
 * @method DeleteDeviceGroup deleteDeviceGroup(array $options = [])
 * @method CreateDeviceGroup createDeviceGroup(array $options = [])
 * @method BatchDeleteDeviceGroupRelations batchDeleteDeviceGroupRelations(array $options = [])
 * @method BatchAddDeviceGroupRelations batchAddDeviceGroupRelations(array $options = [])
 * @method SaveDeviceProp saveDeviceProp(array $options = [])
 * @method DeleteDeviceProp deleteDeviceProp(array $options = [])
 * @method QueryPageByApplyId queryPageByApplyId(array $options = [])
 * @method QueryDevice queryDevice(array $options = [])
 * @method BatchGetDeviceState batchGetDeviceState(array $options = [])
 * @method RRpc rRpc(array $options = [])
 * @method QueryTopicReverseRouteTable queryTopicReverseRouteTable(array $options = [])
 * @method QueryTopicRouteTable queryTopicRouteTable(array $options = [])
 * @method PubBroadcast pubBroadcast(array $options = [])
 * @method DeleteTopicRouteTable deleteTopicRouteTable(array $options = [])
 * @method CreateTopicRouteTable createTopicRouteTable(array $options = [])
 * @method QueryAhDeviceList queryAhDeviceList(array $options = [])
 * @method AhQueryDeviceList ahQueryDeviceList(array $options = [])
 * @method QueryDeviceProp queryDeviceProp(array $options = [])
 * @method CreateRuleAction createRuleAction(array $options = [])
 * @method CreateRule createRule(array $options = [])
 * @method ListRuleActions listRuleActions(array $options = [])
 * @method StartRule startRule(array $options = [])
 * @method QueryProductTopic queryProductTopic(array $options = [])
 * @method DeleteRuleAction deleteRuleAction(array $options = [])
 * @method StopRule stopRule(array $options = [])
 * @method Pub pub(array $options = [])
 * @method ListRule listRule(array $options = [])
 * @method GetRule getRule(array $options = [])
 * @method CreateProductTopic createProductTopic(array $options = [])
 * @method GetDeviceShadow getDeviceShadow(array $options = [])
 * @method DeleteProductTopic deleteProductTopic(array $options = [])
 * @method DeleteRule deleteRule(array $options = [])
 * @method UpdateProductTopic updateProductTopic(array $options = [])
 * @method GetRuleAction getRuleAction(array $options = [])
 * @method UpdateRuleAction updateRuleAction(array $options = [])
 * @method UpdateDeviceShadow updateDeviceShadow(array $options = [])
 * @method UpdateRule updateRule(array $options = [])
 * @method GetGatewayBySubDevice getGatewayBySubDevice(array $options = [])
 * @method QueryBatchRegisterDeviceStatus queryBatchRegisterDeviceStatus(array $options = [])
 * @method RemoveThingTopo removeThingTopo(array $options = [])
 * @method GetThingTopo getThingTopo(array $options = [])
 * @method NotifyAddThingTopo notifyAddThingTopo(array $options = [])
 * @method QueryDevicePropertyData queryDevicePropertyData(array $options = [])
 * @method QueryDevicePropertyStatus queryDevicePropertyStatus(array $options = [])
 * @method BatchRegisterDevice batchRegisterDevice(array $options = [])
 * @method BatchRegisterDeviceWithApplyId batchRegisterDeviceWithApplyId(array $options = [])
 * @method BatchCheckDeviceNames batchCheckDeviceNames(array $options = [])
 * @method UpdateProduct updateProduct(array $options = [])
 * @method RegisterDevice registerDevice(array $options = [])
 * @method SetDeviceProperty setDeviceProperty(array $options = [])
 * @method QueryProductList queryProductList(array $options = [])
 * @method QueryDeviceStatistics queryDeviceStatistics(array $options = [])
 * @method QueryProduct queryProduct(array $options = [])
 * @method QueryDeviceEventData queryDeviceEventData(array $options = [])
 * @method QueryDeviceServiceData queryDeviceServiceData(array $options = [])
 * @method QueryDeviceDetail queryDeviceDetail(array $options = [])
 * @method InvokeThingService invokeThingService(array $options = [])
 * @method GetDeviceStatus getDeviceStatus(array $options = [])
 * @method DisableThing disableThing(array $options = [])
 * @method EnableThing enableThing(array $options = [])
 * @method DeleteDevice deleteDevice(array $options = [])
 * @method DeleteProduct deleteProduct(array $options = [])
 * @method CreateProduct createProduct(array $options = [])
 */
class IotApiResolver
{
    use ApiResolverTrait;
}
