<?php

namespace AlibabaCloud\Vod\V20170321;

use AlibabaCloud\ApiResolverTrait;

/**
 * @deprecated
 *
 * @method static AddCategory addCategory(array $options = [])
 * @method static AddEditingProject addEditingProject(array $options = [])
 * @method static AddFaceRegistration addFaceRegistration(array $options = [])
 * @method static AddVodTemplate addVodTemplate(array $options = [])
 * @method static AddWatermark addWatermark(array $options = [])
 * @method static CreateAudit createAudit(array $options = [])
 * @method static CreateUploadAttachedMedia createUploadAttachedMedia(array $options = [])
 * @method static CreateUploadImage createUploadImage(array $options = [])
 * @method static CreateUploadVideo createUploadVideo(array $options = [])
 * @method static DeleteCategory deleteCategory(array $options = [])
 * @method static DeleteEditingProject deleteEditingProject(array $options = [])
 * @method static DeleteImage deleteImage(array $options = [])
 * @method static DeleteMezzanines deleteMezzanines(array $options = [])
 * @method static DeleteStream deleteStream(array $options = [])
 * @method static DeleteVideo deleteVideo(array $options = [])
 * @method static DeleteVodTemplate deleteVodTemplate(array $options = [])
 * @method static DeleteWatermark deleteWatermark(array $options = [])
 * @method static DescribePlayTopVideos describePlayTopVideos(array $options = [])
 * @method static DescribePlayUserAvg describePlayUserAvg(array $options = [])
 * @method static DescribePlayUserTotal describePlayUserTotal(array $options = [])
 * @method static DescribePlayVideoStatis describePlayVideoStatis(array $options = [])
 * @method static EditLiveRecordVideo editLiveRecordVideo(array $options = [])
 * @method static GetAuditHistory getAuditHistory(array $options = [])
 * @method static GetCategories getCategories(array $options = [])
 * @method static GetEditingProject getEditingProject(array $options = [])
 * @method static GetEditingProjectMaterials getEditingProjectMaterials(array $options = [])
 * @method static GetFileInfo getFileInfo(array $options = [])
 * @method static GetImageInfo getImageInfo(array $options = [])
 * @method static GetMediaDNAResult getMediaDNAResult(array $options = [])
 * @method static GetMezzanineInfo getMezzanineInfo(array $options = [])
 * @method static GetPlayInfo getPlayInfo(array $options = [])
 * @method static GetVideoInfo getVideoInfo(array $options = [])
 * @method static GetVideoInfos getVideoInfos(array $options = [])
 * @method static GetVideoList getVideoList(array $options = [])
 * @method static GetVideoPlayAuth getVideoPlayAuth(array $options = [])
 * @method static GetVodTemplate getVodTemplate(array $options = [])
 * @method static GetWatermark getWatermark(array $options = [])
 * @method static ListAIJob listAIJob(array $options = [])
 * @method static ListAuditSecurityIp listAuditSecurityIp(array $options = [])
 * @method static ListLiveRecordVideo listLiveRecordVideo(array $options = [])
 * @method static ListSnapshots listSnapshots(array $options = [])
 * @method static ListVodTemplate listVodTemplate(array $options = [])
 * @method static ListWatermark listWatermark(array $options = [])
 * @method static ProduceEditingProjectVideo produceEditingProjectVideo(array $options = [])
 * @method static RefreshUploadVideo refreshUploadVideo(array $options = [])
 * @method static RegisterMedia registerMedia(array $options = [])
 * @method static SearchEditingProject searchEditingProject(array $options = [])
 * @method static SearchMedia searchMedia(array $options = [])
 * @method static SetAuditSecurityIp setAuditSecurityIp(array $options = [])
 * @method static SetDefaultWatermark setDefaultWatermark(array $options = [])
 * @method static SetEditingProjectMaterials setEditingProjectMaterials(array $options = [])
 * @method static SubmitAIJob submitAIJob(array $options = [])
 * @method static SubmitPreprocessJobs submitPreprocessJobs(array $options = [])
 * @method static SubmitSnapshotJob submitSnapshotJob(array $options = [])
 * @method static SubmitTranscodeJobs submitTranscodeJobs(array $options = [])
 * @method static UpdateCategory updateCategory(array $options = [])
 * @method static UpdateEditingProject updateEditingProject(array $options = [])
 * @method static UpdateImageInfos updateImageInfos(array $options = [])
 * @method static UpdateVideoInfo updateVideoInfo(array $options = [])
 * @method static UpdateVideoInfos updateVideoInfos(array $options = [])
 * @method static UpdateVodTemplate updateVodTemplate(array $options = [])
 * @method static UpdateWatermark updateWatermark(array $options = [])
 * @method static UploadMediaByURL uploadMediaByURL(array $options = [])
 * @method static VodApiResolver vodApiResolver(array $options = [])
 */
class Vod
{
    use ApiResolverTrait;
}
