<?php

namespace AlibabaCloud\Smartag\V20180313;

use AlibabaCloud\ApiResolverTrait;

/**
 * Resolve Api based on the method name.
 *
 * @method SetSagRouteableAddress setSagRouteableAddress(array $options = [])
 * @method ClearSagRouteableAddress clearSagRouteableAddress(array $options = [])
 * @method DescribeNetworkOptimizationSettings describeNetworkOptimizationSettings(array $options = [])
 * @method DescribeSagRouteableAddress describeSagRouteableAddress(array $options = [])
 * @method ModifyNetworkOptimization modifyNetworkOptimization(array $options = [])
 * @method DetachNetworkOptimizationSags detachNetworkOptimizationSags(array $options = [])
 * @method DescribeNetworkOptimizationSags describeNetworkOptimizationSags(array $options = [])
 * @method DescribeNetworkOptimizations describeNetworkOptimizations(array $options = [])
 * @method DeleteNetworkOptimizationSetting deleteNetworkOptimizationSetting(array $options = [])
 * @method DeleteNetworkOptimization deleteNetworkOptimization(array $options = [])
 * @method CreateNetworkOptimization createNetworkOptimization(array $options = [])
 * @method AddNetworkOptimizationSetting addNetworkOptimizationSetting(array $options = [])
 * @method AttachNetworkOptimizationSags attachNetworkOptimizationSags(array $options = [])
 * @method ModifySerialNumber modifySerialNumber(array $options = [])
 * @method KickOutClients kickOutClients(array $options = [])
 * @method DescribeSagOnlineClientStatistics describeSagOnlineClientStatistics(array $options = [])
 * @method ResetSmartAccessGatewayClientUserPassword resetSmartAccessGatewayClientUserPassword(array $options = [])
 * @method ModifySmartAccessGatewayClientUser modifySmartAccessGatewayClientUser(array $options = [])
 * @method DescribeUserOnlineClientStatistics describeUserOnlineClientStatistics(array $options = [])
 * @method DescribeUserOnlineClients describeUserOnlineClients(array $options = [])
 * @method DescribeUserFlowStatistics describeUserFlowStatistics(array $options = [])
 * @method DeleteSmartAccessGatewayClientUser deleteSmartAccessGatewayClientUser(array $options = [])
 * @method DescribeSmartAccessGatewayClientUsers describeSmartAccessGatewayClientUsers(array $options = [])
 * @method CreateSmartAccessGatewayClientUser createSmartAccessGatewayClientUser(array $options = [])
 * @method DescribeACLs describeACLs(array $options = [])
 * @method DescribeACLAttribute describeACLAttribute(array $options = [])
 * @method DeleteACL deleteACL(array $options = [])
 * @method DeleteACLRule deleteACLRule(array $options = [])
 * @method ModifyACLRule modifyACLRule(array $options = [])
 * @method DisassociateACL disassociateACL(array $options = [])
 * @method AssociateACL associateACL(array $options = [])
 * @method AddACLRule addACLRule(array $options = [])
 * @method ModifyACL modifyACL(array $options = [])
 * @method CreateACL createACL(array $options = [])
 * @method UnicomSignConfirm unicomSignConfirm(array $options = [])
 * @method UpgradeSmartAccessGateway upgradeSmartAccessGateway(array $options = [])
 * @method DowngradeSmartAccessGateway downgradeSmartAccessGateway(array $options = [])
 * @method DeleteSAGLinkLevelHa deleteSAGLinkLevelHa(array $options = [])
 * @method SwitchSAGHaState switchSAGHaState(array $options = [])
 * @method CreateSAGLinkLevelHa createSAGLinkLevelHa(array $options = [])
 * @method UnicomOrderConfirm unicomOrderConfirm(array $options = [])
 * @method DescribeGrantRules describeGrantRules(array $options = [])
 * @method GrantInstanceToCbn grantInstanceToCbn(array $options = [])
 * @method RevokeInstanceFromCbn revokeInstanceFromCbn(array $options = [])
 * @method RebootSmartAccessGateway rebootSmartAccessGateway(array $options = [])
 * @method SwitchCloudBoxHaState switchCloudBoxHaState(array $options = [])
 * @method CreateSmartAccessGateway createSmartAccessGateway(array $options = [])
 * @method DescribeSmartAccessGatewayHa describeSmartAccessGatewayHa(array $options = [])
 * @method DeleteDedicatedLineBackup deleteDedicatedLineBackup(array $options = [])
 * @method CreateDedicatedLineBackup createDedicatedLineBackup(array $options = [])
 * @method ActivateSmartAccessGateway activateSmartAccessGateway(array $options = [])
 * @method UnlockSmartAccessGateway unlockSmartAccessGateway(array $options = [])
 * @method DescribeSmartAccessGatewayVersions describeSmartAccessGatewayVersions(array $options = [])
 * @method BindSmartAccessGateway bindSmartAccessGateway(array $options = [])
 * @method CreateCloudConnectNetwork createCloudConnectNetwork(array $options = [])
 * @method DeleteCloudConnectNetwork deleteCloudConnectNetwork(array $options = [])
 * @method DescribeCloudConnectNetworks describeCloudConnectNetworks(array $options = [])
 * @method DescribeRegions describeRegions(array $options = [])
 * @method DescribeSmartAccessGateways describeSmartAccessGateways(array $options = [])
 * @method GetCloudConnectNetworkUseLimit getCloudConnectNetworkUseLimit(array $options = [])
 * @method GetSmartAccessGatewayUseLimit getSmartAccessGatewayUseLimit(array $options = [])
 * @method ModifyCloudConnectNetwork modifyCloudConnectNetwork(array $options = [])
 * @method ModifySmartAccessGateway modifySmartAccessGateway(array $options = [])
 * @method UnbindSmartAccessGateway unbindSmartAccessGateway(array $options = [])
 * @method UpdateSmartAccessGatewayVersion updateSmartAccessGatewayVersion(array $options = [])
 */
class SmartagApiResolver
{
    use ApiResolverTrait;
}
