<?php

namespace AlibabaCloud\Iot;

use AlibabaCloud\ApiResolverTrait;

/**
 * Find the specified Api of the Iot based on the method name as the Api name.
 *
 * @package   AlibabaCloud\Iot
 *
 * @method V20180120\ActiveDevice activeDevice(array $options = [])
 * @method V20180120\AddEventRecordPlanDevice addEventRecordPlanDevice(array $options = [])
 * @method V20180120\AddRecordPlanDevice addRecordPlanDevice(array $options = [])
 * @method V20180120\AhQueryDeviceList ahQueryDeviceList(array $options = [])
 * @method V20180120\BatchAddDeviceGroupRelations batchAddDeviceGroupRelations(array $options = [])
 * @method V20180120\BatchCheckDeviceNames batchCheckDeviceNames(array $options = [])
 * @method V20180120\BatchDeleteDeviceGroupRelations batchDeleteDeviceGroupRelations(array $options = [])
 * @method V20180120\BatchGetDeviceState batchGetDeviceState(array $options = [])
 * @method V20180120\BatchRegisterDevice batchRegisterDevice(array $options = [])
 * @method V20180120\BatchRegisterDeviceWithApplyId batchRegisterDeviceWithApplyId(array $options = [])
 * @method V20180120\BindDeviceToEdgeInstance bindDeviceToEdgeInstance(array $options = [])
 * @method V20180120\BindFunctionToEdgeInstance bindFunctionToEdgeInstance(array $options = [])
 * @method V20180120\CreateDeviceGroup createDeviceGroup(array $options = [])
 * @method V20180120\CreateEdgeInstance createEdgeInstance(array $options = [])
 * @method V20180120\CreateEdgeInstanceDeployment createEdgeInstanceDeployment(array $options = [])
 * @method V20180120\CreateEdgeInstanceMessageRoute createEdgeInstanceMessageRoute(array $options = [])
 * @method V20180120\CreateProduct createProduct(array $options = [])
 * @method V20180120\CreateProductTags createProductTags(array $options = [])
 * @method V20180120\CreateProductTopic createProductTopic(array $options = [])
 * @method V20180120\CreateRule createRule(array $options = [])
 * @method V20180120\CreateRuleAction createRuleAction(array $options = [])
 * @method V20180120\CreateTopicRouteTable createTopicRouteTable(array $options = [])
 * @method V20180120\DeleteDevice deleteDevice(array $options = [])
 * @method V20180120\DeleteDeviceGroup deleteDeviceGroup(array $options = [])
 * @method V20180120\DeleteDeviceProp deleteDeviceProp(array $options = [])
 * @method V20180120\DeleteEdgeInstance deleteEdgeInstance(array $options = [])
 * @method V20180120\DeleteEdgeInstanceMessageRoute deleteEdgeInstanceMessageRoute(array $options = [])
 * @method V20180120\DeleteEventRecordPlan deleteEventRecordPlan(array $options = [])
 * @method V20180120\DeleteEventRecordPlanDevice deleteEventRecordPlanDevice(array $options = [])
 * @method V20180120\DeleteProduct deleteProduct(array $options = [])
 * @method V20180120\DeleteProductTags deleteProductTags(array $options = [])
 * @method V20180120\DeleteProductTopic deleteProductTopic(array $options = [])
 * @method V20180120\DeleteRecordPlan deleteRecordPlan(array $options = [])
 * @method V20180120\DeleteRecordPlanDevice deleteRecordPlanDevice(array $options = [])
 * @method V20180120\DeleteRule deleteRule(array $options = [])
 * @method V20180120\DeleteRuleAction deleteRuleAction(array $options = [])
 * @method V20180120\DeleteTimeTemplate deleteTimeTemplate(array $options = [])
 * @method V20180120\DeleteTopicRouteTable deleteTopicRouteTable(array $options = [])
 * @method V20180120\DisableThing disableThing(array $options = [])
 * @method V20180120\EnableThing enableThing(array $options = [])
 * @method V20180120\GenerateOssUriForTsl generateOssUriForTsl(array $options = [])
 * @method V20180120\GetDeviceProductList getDeviceProductList(array $options = [])
 * @method V20180120\GetDeviceShadow getDeviceShadow(array $options = [])
 * @method V20180120\GetDeviceStatus getDeviceStatus(array $options = [])
 * @method V20180120\GetEdgeInstance getEdgeInstance(array $options = [])
 * @method V20180120\GetEdgeInstanceMessageRoute getEdgeInstanceMessageRoute(array $options = [])
 * @method V20180120\GetGatewayBySubDevice getGatewayBySubDevice(array $options = [])
 * @method V20180120\GetRule getRule(array $options = [])
 * @method V20180120\GetRuleAction getRuleAction(array $options = [])
 * @method V20180120\GetThingTopo getThingTopo(array $options = [])
 * @method V20180120\ImportTslFromOss importTslFromOss(array $options = [])
 * @method V20180120\InvokeThingService invokeThingService(array $options = [])
 * @method V20180120\InvokeThingsService invokeThingsService(array $options = [])
 * @method V20180120\ListProductByTags listProductByTags(array $options = [])
 * @method V20180120\ListProductTags listProductTags(array $options = [])
 * @method V20180120\ListRule listRule(array $options = [])
 * @method V20180120\ListRuleActions listRuleActions(array $options = [])
 * @method V20180120\ModifyDeviceStatus modifyDeviceStatus(array $options = [])
 * @method V20180120\NotifyAddThingTopo notifyAddThingTopo(array $options = [])
 * @method V20180120\Pub pub(array $options = [])
 * @method V20180120\PubBroadcast pubBroadcast(array $options = [])
 * @method V20180120\QueryAhDeviceList queryAhDeviceList(array $options = [])
 * @method V20180120\QueryAppDeviceList queryAppDeviceList(array $options = [])
 * @method V20180120\QueryBatchRegisterDeviceStatus queryBatchRegisterDeviceStatus(array $options = [])
 * @method V20180120\QueryDevice queryDevice(array $options = [])
 * @method V20180120\QueryDeviceByTags queryDeviceByTags(array $options = [])
 * @method V20180120\QueryDeviceDetail queryDeviceDetail(array $options = [])
 * @method V20180120\QueryDeviceEvent queryDeviceEvent(array $options = [])
 * @method V20180120\QueryDeviceEventData queryDeviceEventData(array $options = [])
 * @method V20180120\QueryDeviceEventPicture queryDeviceEventPicture(array $options = [])
 * @method V20180120\QueryDeviceEventRecord queryDeviceEventRecord(array $options = [])
 * @method V20180120\QueryDeviceFileVod queryDeviceFileVod(array $options = [])
 * @method V20180120\QueryDeviceGroupByDevice queryDeviceGroupByDevice(array $options = [])
 * @method V20180120\QueryDeviceGroupByTags queryDeviceGroupByTags(array $options = [])
 * @method V20180120\QueryDeviceGroupInfo queryDeviceGroupInfo(array $options = [])
 * @method V20180120\QueryDeviceGroupList queryDeviceGroupList(array $options = [])
 * @method V20180120\QueryDeviceGroupTagList queryDeviceGroupTagList(array $options = [])
 * @method V20180120\QueryDeviceList queryDeviceList(array $options = [])
 * @method V20180120\QueryDeviceListByDeviceGroup queryDeviceListByDeviceGroup(array $options = [])
 * @method V20180120\QueryDevicePictureFile queryDevicePictureFile(array $options = [])
 * @method V20180120\QueryDevicePictureLifeCycle queryDevicePictureLifeCycle(array $options = [])
 * @method V20180120\QueryDeviceProp queryDeviceProp(array $options = [])
 * @method V20180120\QueryDevicePropertiesData queryDevicePropertiesData(array $options = [])
 * @method V20180120\QueryDevicePropertyData queryDevicePropertyData(array $options = [])
 * @method V20180120\QueryDevicePropertyStatus queryDevicePropertyStatus(array $options = [])
 * @method V20180120\QueryDeviceRecordLifeCycle queryDeviceRecordLifeCycle(array $options = [])
 * @method V20180120\QueryDeviceServiceData queryDeviceServiceData(array $options = [])
 * @method V20180120\QueryDeviceStatistics queryDeviceStatistics(array $options = [])
 * @method V20180120\QueryEdgeInstance queryEdgeInstance(array $options = [])
 * @method V20180120\QueryEdgeInstanceDeployDetail queryEdgeInstanceDeployDetail(array $options = [])
 * @method V20180120\QueryEdgeInstanceDevice queryEdgeInstanceDevice(array $options = [])
 * @method V20180120\QueryEdgeInstanceFunction queryEdgeInstanceFunction(array $options = [])
 * @method V20180120\QueryEdgeInstanceGateway queryEdgeInstanceGateway(array $options = [])
 * @method V20180120\QueryEdgeInstanceMessageRoute queryEdgeInstanceMessageRoute(array $options = [])
 * @method V20180120\QueryEventRecordPlanByDevice queryEventRecordPlanByDevice(array $options = [])
 * @method V20180120\QueryEventRecordPlanDetail queryEventRecordPlanDetail(array $options = [])
 * @method V20180120\QueryEventRecordPlanDevices queryEventRecordPlanDevices(array $options = [])
 * @method V20180120\QueryEventRecordPlans queryEventRecordPlans(array $options = [])
 * @method V20180120\QueryLiveStreaming queryLiveStreaming(array $options = [])
 * @method V20180120\QueryMeasureList queryMeasureList(array $options = [])
 * @method V20180120\QueryMeasureSummary queryMeasureSummary(array $options = [])
 * @method V20180120\QueryMeasureTop queryMeasureTop(array $options = [])
 * @method V20180120\QueryMonthRecord queryMonthRecord(array $options = [])
 * @method V20180120\QueryPageByApplyId queryPageByApplyId(array $options = [])
 * @method V20180120\QueryPictureFiles queryPictureFiles(array $options = [])
 * @method V20180120\QueryProduct queryProduct(array $options = [])
 * @method V20180120\QueryProductBiz queryProductBiz(array $options = [])
 * @method V20180120\QueryProductList queryProductList(array $options = [])
 * @method V20180120\QueryProductTopic queryProductTopic(array $options = [])
 * @method V20180120\QueryRecord queryRecord(array $options = [])
 * @method V20180120\QueryRecordPlanByDevice queryRecordPlanByDevice(array $options = [])
 * @method V20180120\QueryRecordPlanDetail queryRecordPlanDetail(array $options = [])
 * @method V20180120\QueryRecordPlanDevices queryRecordPlanDevices(array $options = [])
 * @method V20180120\QueryRecordPlans queryRecordPlans(array $options = [])
 * @method V20180120\QueryRecordUrl queryRecordUrl(array $options = [])
 * @method V20180120\QuerySuperDeviceGroup querySuperDeviceGroup(array $options = [])
 * @method V20180120\QueryTimeTemplate queryTimeTemplate(array $options = [])
 * @method V20180120\QueryTimeTemplateDetail queryTimeTemplateDetail(array $options = [])
 * @method V20180120\QueryTopicReverseRouteTable queryTopicReverseRouteTable(array $options = [])
 * @method V20180120\QueryTopicRouteTable queryTopicRouteTable(array $options = [])
 * @method V20180120\RRpc rRpc(array $options = [])
 * @method V20180120\RegisterDevice registerDevice(array $options = [])
 * @method V20180120\RemoveThingTopo removeThingTopo(array $options = [])
 * @method V20180120\ResetEdgeInstanceDeployments resetEdgeInstanceDeployments(array $options = [])
 * @method V20180120\SaveDeviceProp saveDeviceProp(array $options = [])
 * @method V20180120\SetDeviceGroupTags setDeviceGroupTags(array $options = [])
 * @method V20180120\SetDevicePictureLifeCycle setDevicePictureLifeCycle(array $options = [])
 * @method V20180120\SetDeviceProperty setDeviceProperty(array $options = [])
 * @method V20180120\SetDeviceRecordLifeCycle setDeviceRecordLifeCycle(array $options = [])
 * @method V20180120\SetDeviceStorageLifeCycle setDeviceStorageLifeCycle(array $options = [])
 * @method V20180120\SetDevicesProperty setDevicesProperty(array $options = [])
 * @method V20180120\SetEventRecordPlan setEventRecordPlan(array $options = [])
 * @method V20180120\SetRecordPlan setRecordPlan(array $options = [])
 * @method V20180120\SetTimeTemplate setTimeTemplate(array $options = [])
 * @method V20180120\StartRule startRule(array $options = [])
 * @method V20180120\StopLiveStreaming stopLiveStreaming(array $options = [])
 * @method V20180120\StopRule stopRule(array $options = [])
 * @method V20180120\TriggerCapturePicture triggerCapturePicture(array $options = [])
 * @method V20180120\TriggerRecord triggerRecord(array $options = [])
 * @method V20180120\UnbindDeviceFromEdgeInstance unbindDeviceFromEdgeInstance(array $options = [])
 * @method V20180120\UnbindFunctionFromEdgeInstance unbindFunctionFromEdgeInstance(array $options = [])
 * @method V20180120\UpdateDeviceGroup updateDeviceGroup(array $options = [])
 * @method V20180120\UpdateDeviceShadow updateDeviceShadow(array $options = [])
 * @method V20180120\UpdateEdgeInstance updateEdgeInstance(array $options = [])
 * @method V20180120\UpdateEdgeInstanceFunction updateEdgeInstanceFunction(array $options = [])
 * @method V20180120\UpdateEdgeInstanceMessageRoute updateEdgeInstanceMessageRoute(array $options = [])
 * @method V20180120\UpdateEventRecordPlan updateEventRecordPlan(array $options = [])
 * @method V20180120\UpdateEventRecordPlanDevice updateEventRecordPlanDevice(array $options = [])
 * @method V20180120\UpdateProduct updateProduct(array $options = [])
 * @method V20180120\UpdateProductTags updateProductTags(array $options = [])
 * @method V20180120\UpdateProductTopic updateProductTopic(array $options = [])
 * @method V20180120\UpdateRecordPlan updateRecordPlan(array $options = [])
 * @method V20180120\UpdateRecordPlanDevice updateRecordPlanDevice(array $options = [])
 * @method V20180120\UpdateRule updateRule(array $options = [])
 * @method V20180120\UpdateRuleAction updateRuleAction(array $options = [])
 * @method V20180120\UpdateTimeTemplate updateTimeTemplate(array $options = [])
 */
class IotV20180120ApiResolver
{
    use ApiResolverTrait;

    /**
     * @var string
     */
    protected $namespace = 'AlibabaCloud\\Iot\\V20180120';
}
