<?php

namespace AlibabaCloud\Baas;

use AlibabaCloud\ApiResolverTrait;

/**
 * Find the specified Api of the Baas based on the method name as the Api name.
 *
 * @package   AlibabaCloud\Baas
 *
 * @method static V20180731\AcceptInvitation acceptInvitation(array $options = [])
 * @method static V20180731\ApplyBlockchain applyBlockchain(array $options = [])
 * @method static V20180731\CheckConsortiumDomain checkConsortiumDomain(array $options = [])
 * @method static V20180731\CheckOrganizationDomain checkOrganizationDomain(array $options = [])
 * @method static V20180731\ConfirmConsortiumMember confirmConsortiumMember(array $options = [])
 * @method static V20180731\CreateBlockchainApplication createBlockchainApplication(array $options = [])
 * @method static V20180731\CreateBlockchainApply createBlockchainApply(array $options = [])
 * @method static V20180731\CreateChaincode createChaincode(array $options = [])
 * @method static V20180731\CreateChannel createChannel(array $options = [])
 * @method static V20180731\CreateChannelMember createChannelMember(array $options = [])
 * @method static V20180731\CreateConsortium createConsortium(array $options = [])
 * @method static V20180731\CreateConsortiumMember createConsortiumMember(array $options = [])
 * @method static V20180731\CreateEcosphere createEcosphere(array $options = [])
 * @method static V20180731\CreateOrganization createOrganization(array $options = [])
 * @method static V20180731\DeleteChaincode deleteChaincode(array $options = [])
 * @method static V20180731\DescribeApplies describeApplies(array $options = [])
 * @method static V20180731\DescribeBcSchema describeBcSchema(array $options = [])
 * @method static V20180731\DescribeBlock describeBlock(array $options = [])
 * @method static V20180731\DescribeBlockchainCreateTask describeBlockchainCreateTask(array $options = [])
 * @method static V20180731\DescribeBlockchainInfo describeBlockchainInfo(array $options = [])
 * @method static V20180731\DescribeBlockchainSchema describeBlockchainSchema(array $options = [])
 * @method static V20180731\DescribeCandidateOrganizations describeCandidateOrganizations(array $options = [])
 * @method static V20180731\DescribeChaincodeCollectionConfig describeChaincodeCollectionConfig(array $options = [])
 * @method static V20180731\DescribeChaincodeUploadPolicy describeChaincodeUploadPolicy(array $options = [])
 * @method static V20180731\DescribeChannelMembers describeChannelMembers(array $options = [])
 * @method static V20180731\DescribeConsortiumAdminStatus describeConsortiumAdminStatus(array $options = [])
 * @method static V20180731\DescribeConsortiumChaincodes describeConsortiumChaincodes(array $options = [])
 * @method static V20180731\DescribeConsortiumChannels describeConsortiumChannels(array $options = [])
 * @method static V20180731\DescribeConsortiumConfig describeConsortiumConfig(array $options = [])
 * @method static V20180731\DescribeConsortiumDeletable describeConsortiumDeletable(array $options = [])
 * @method static V20180731\DescribeConsortiumMemberApproval describeConsortiumMemberApproval(array $options = [])
 * @method static V20180731\DescribeConsortiumMembers describeConsortiumMembers(array $options = [])
 * @method static V20180731\DescribeConsortiumOrderers describeConsortiumOrderers(array $options = [])
 * @method static V20180731\DescribeConsortiumSpecs describeConsortiumSpecs(array $options = [])
 * @method static V20180731\DescribeConsortiums describeConsortiums(array $options = [])
 * @method static V20180731\DescribeEcosphereSpecs describeEcosphereSpecs(array $options = [])
 * @method static V20180731\DescribeEthereumDeletable describeEthereumDeletable(array $options = [])
 * @method static V20180731\DescribeEthereumNodeConfiguration describeEthereumNodeConfiguration(array $options = [])
 * @method static V20180731\DescribeExplorer describeExplorer(array $options = [])
 * @method static V20180731\DescribeInvitationCode describeInvitationCode(array $options = [])
 * @method static V20180731\DescribeInvitationList describeInvitationList(array $options = [])
 * @method static V20180731\DescribeInviter describeInviter(array $options = [])
 * @method static V20180731\DescribeMetric describeMetric(array $options = [])
 * @method static V20180731\DescribeMyBlockchains describeMyBlockchains(array $options = [])
 * @method static V20180731\DescribeMySuccessApplies describeMySuccessApplies(array $options = [])
 * @method static V20180731\DescribeMySuccessfulApplication describeMySuccessfulApplication(array $options = [])
 * @method static V20180731\DescribeOrdererLogs describeOrdererLogs(array $options = [])
 * @method static V20180731\DescribeOrganization describeOrganization(array $options = [])
 * @method static V20180731\DescribeOrganizationChaincodes describeOrganizationChaincodes(array $options = [])
 * @method static V20180731\DescribeOrganizationChannels describeOrganizationChannels(array $options = [])
 * @method static V20180731\DescribeOrganizationDeletable describeOrganizationDeletable(array $options = [])
 * @method static V20180731\DescribeOrganizationMembers describeOrganizationMembers(array $options = [])
 * @method static V20180731\DescribeOrganizationPeers describeOrganizationPeers(array $options = [])
 * @method static V20180731\DescribeOrganizationSpecs describeOrganizationSpecs(array $options = [])
 * @method static V20180731\DescribeOrganizationUserCerts describeOrganizationUserCerts(array $options = [])
 * @method static V20180731\DescribeOrganizationUsers describeOrganizationUsers(array $options = [])
 * @method static V20180731\DescribeOrganizations describeOrganizations(array $options = [])
 * @method static V20180731\DescribeOrgnaizationChaincodes describeOrgnaizationChaincodes(array $options = [])
 * @method static V20180731\DescribeOssProperties describeOssProperties(array $options = [])
 * @method static V20180731\DescribePeerLogs describePeerLogs(array $options = [])
 * @method static V20180731\DescribeRegions describeRegions(array $options = [])
 * @method static V20180731\DescribeResourceType describeResourceType(array $options = [])
 * @method static V20180731\DescribeRootDomain describeRootDomain(array $options = [])
 * @method static V20180731\DescribeSchemaDetail describeSchemaDetail(array $options = [])
 * @method static V20180731\DescribeTasks describeTasks(array $options = [])
 * @method static V20180731\DescribeTemplates describeTemplates(array $options = [])
 * @method static V20180731\DescribeTransaction describeTransaction(array $options = [])
 * @method static V20180731\DestroyConsortium destroyConsortium(array $options = [])
 * @method static V20180731\DestroyEthereum destroyEthereum(array $options = [])
 * @method static V20180731\DestroyOrganization destroyOrganization(array $options = [])
 * @method static V20180731\DownloadAll downloadAll(array $options = [])
 * @method static V20180731\DownloadBizview downloadBizview(array $options = [])
 * @method static V20180731\DownloadOrganizationSDK downloadOrganizationSDK(array $options = [])
 * @method static V20180731\DownloadSDK2 downloadSDK2(array $options = [])
 * @method static V20180731\DownloadSdk downloadSdk(array $options = [])
 * @method static V20180731\DownloadSignedData downloadSignedData(array $options = [])
 * @method static V20180731\GetApplies getApplies(array $options = [])
 * @method static V20180731\GetBcSchema getBcSchema(array $options = [])
 * @method static V20180731\GetBlockchainCreateTask getBlockchainCreateTask(array $options = [])
 * @method static V20180731\GetBlockchainInfo getBlockchainInfo(array $options = [])
 * @method static V20180731\GetMyBlockchains getMyBlockchains(array $options = [])
 * @method static V20180731\GetMySuccessApplies getMySuccessApplies(array $options = [])
 * @method static V20180731\GetOssProperties getOssProperties(array $options = [])
 * @method static V20180731\GetTemplates getTemplates(array $options = [])
 * @method static V20180731\InstallChaincode installChaincode(array $options = [])
 * @method static V20180731\InstantiateChaincode instantiateChaincode(array $options = [])
 * @method static V20180731\InviteUser inviteUser(array $options = [])
 * @method static V20180731\JoinChannel joinChannel(array $options = [])
 * @method static V20180731\OperateUser operateUser(array $options = [])
 * @method static V20180731\QueryBlock queryBlock(array $options = [])
 * @method static V20180731\QueryConsortiumDeletable queryConsortiumDeletable(array $options = [])
 * @method static V20180731\QueryEthereumDeletable queryEthereumDeletable(array $options = [])
 * @method static V20180731\QueryMetric queryMetric(array $options = [])
 * @method static V20180731\QueryOrganizationDeletable queryOrganizationDeletable(array $options = [])
 * @method static V20180731\QueryTransaction queryTransaction(array $options = [])
 * @method static V20180731\RejectUser rejectUser(array $options = [])
 * @method static V20180731\ResetCertificate resetCertificate(array $options = [])
 * @method static V20180731\ResetOrganizationUserPassword resetOrganizationUserPassword(array $options = [])
 * @method static V20180731\ResetUser resetUser(array $options = [])
 * @method static V20180731\SchemaDetail schemaDetail(array $options = [])
 * @method static V20180731\SynchronizeChaincode synchronizeChaincode(array $options = [])
 * @method static V20180731\UpdateEthereumNodeConfiguration updateEthereumNodeConfiguration(array $options = [])
 * @method static V20180731\UpdateSchema updateSchema(array $options = [])
 * @method static V20180731\UpgradeChaincode upgradeChaincode(array $options = [])
 */
class BaasV20180731
{
    use ApiResolverTrait;

    /**
     * @var string
     */
    protected $namespace = 'AlibabaCloud\\Baas\\V20180731';
}
