<?php

namespace AlibabaCloud\Imm;

use AlibabaCloud\ApiResolverTrait;

/**
 * Find the specified Api of the Imm based on the method name as the Api name.
 *
 * @package   AlibabaCloud\Imm
 *
 * @method static V20170906\CompareFace compareFace(array $options = [])
 * @method static V20170906\CompareImageFaces compareImageFaces(array $options = [])
 * @method static V20170906\ConvertOfficeFormat convertOfficeFormat(array $options = [])
 * @method static V20170906\CreateCADConversionTask createCADConversionTask(array $options = [])
 * @method static V20170906\CreateDeleteFaceSetJob createDeleteFaceSetJob(array $options = [])
 * @method static V20170906\CreateDocIndexTask createDocIndexTask(array $options = [])
 * @method static V20170906\CreateFaceJob createFaceJob(array $options = [])
 * @method static V20170906\CreateFaceSet createFaceSet(array $options = [])
 * @method static V20170906\CreateGroupFacesJob createGroupFacesJob(array $options = [])
 * @method static V20170906\CreateIndexFaceJob createIndexFaceJob(array $options = [])
 * @method static V20170906\CreateOfficeConversionTask createOfficeConversionTask(array $options = [])
 * @method static V20170906\CreatePornBatchDetectJob createPornBatchDetectJob(array $options = [])
 * @method static V20170906\CreateSet createSet(array $options = [])
 * @method static V20170906\CreateTagJob createTagJob(array $options = [])
 * @method static V20170906\CreateTagSet createTagSet(array $options = [])
 * @method static V20170906\CreateVideoAnalyseTask createVideoAnalyseTask(array $options = [])
 * @method static V20170906\DeleteDocIndex deleteDocIndex(array $options = [])
 * @method static V20170906\DeleteFaceById deleteFaceById(array $options = [])
 * @method static V20170906\DeleteFaceByUrl deleteFaceByUrl(array $options = [])
 * @method static V20170906\DeleteFaceJob deleteFaceJob(array $options = [])
 * @method static V20170906\DeleteFaceSearchGroup deleteFaceSearchGroup(array $options = [])
 * @method static V20170906\DeleteFaceSearchImageById deleteFaceSearchImageById(array $options = [])
 * @method static V20170906\DeleteFaceSearchUser deleteFaceSearchUser(array $options = [])
 * @method static V20170906\DeleteFaceSet deleteFaceSet(array $options = [])
 * @method static V20170906\DeleteImage deleteImage(array $options = [])
 * @method static V20170906\DeleteImageJob deleteImageJob(array $options = [])
 * @method static V20170906\DeleteOfficeConversionTask deleteOfficeConversionTask(array $options = [])
 * @method static V20170906\DeletePhotoProcessTask deletePhotoProcessTask(array $options = [])
 * @method static V20170906\DeletePornBatchDetectJob deletePornBatchDetectJob(array $options = [])
 * @method static V20170906\DeleteProject deleteProject(array $options = [])
 * @method static V20170906\DeleteSet deleteSet(array $options = [])
 * @method static V20170906\DeleteTagByName deleteTagByName(array $options = [])
 * @method static V20170906\DeleteTagByUrl deleteTagByUrl(array $options = [])
 * @method static V20170906\DeleteTagJob deleteTagJob(array $options = [])
 * @method static V20170906\DeleteTagSet deleteTagSet(array $options = [])
 * @method static V20170906\DeleteVideo deleteVideo(array $options = [])
 * @method static V20170906\DeleteVideoTask deleteVideoTask(array $options = [])
 * @method static V20170906\DescribeRegions describeRegions(array $options = [])
 * @method static V20170906\DetectClothes detectClothes(array $options = [])
 * @method static V20170906\DetectFace detectFace(array $options = [])
 * @method static V20170906\DetectImageCelebrity detectImageCelebrity(array $options = [])
 * @method static V20170906\DetectImageFaces detectImageFaces(array $options = [])
 * @method static V20170906\DetectImageTags detectImageTags(array $options = [])
 * @method static V20170906\DetectImageTexts detectImageTexts(array $options = [])
 * @method static V20170906\DetectLogo detectLogo(array $options = [])
 * @method static V20170906\DetectQRCodes detectQRCodes(array $options = [])
 * @method static V20170906\DetectTag detectTag(array $options = [])
 * @method static V20170906\FindImages findImages(array $options = [])
 * @method static V20170906\FindImagesByTagNames findImagesByTagNames(array $options = [])
 * @method static V20170906\FindSimilarFaces findSimilarFaces(array $options = [])
 * @method static V20170906\GetDocIndex getDocIndex(array $options = [])
 * @method static V20170906\GetDocIndexTask getDocIndexTask(array $options = [])
 * @method static V20170906\GetFaceDetail getFaceDetail(array $options = [])
 * @method static V20170906\GetFaceJob getFaceJob(array $options = [])
 * @method static V20170906\GetFaceSearchGroup getFaceSearchGroup(array $options = [])
 * @method static V20170906\GetFaceSearchImage getFaceSearchImage(array $options = [])
 * @method static V20170906\GetFaceSearchUser getFaceSearchUser(array $options = [])
 * @method static V20170906\GetFaceSet getFaceSet(array $options = [])
 * @method static V20170906\GetFaceSetDetail getFaceSetDetail(array $options = [])
 * @method static V20170906\GetImage getImage(array $options = [])
 * @method static V20170906\GetImageJob getImageJob(array $options = [])
 * @method static V20170906\GetOfficeConversionTask getOfficeConversionTask(array $options = [])
 * @method static V20170906\GetPhotoProcessTask getPhotoProcessTask(array $options = [])
 * @method static V20170906\GetPornBatchDetectJob getPornBatchDetectJob(array $options = [])
 * @method static V20170906\GetProject getProject(array $options = [])
 * @method static V20170906\GetSet getSet(array $options = [])
 * @method static V20170906\GetTagJob getTagJob(array $options = [])
 * @method static V20170906\GetTagSet getTagSet(array $options = [])
 * @method static V20170906\GetVideo getVideo(array $options = [])
 * @method static V20170906\GetVideoTask getVideoTask(array $options = [])
 * @method static V20170906\GroupFaces groupFaces(array $options = [])
 * @method static V20170906\IndexFace indexFace(array $options = [])
 * @method static V20170906\IndexImage indexImage(array $options = [])
 * @method static V20170906\IndexTag indexTag(array $options = [])
 * @method static V20170906\IndexVideo indexVideo(array $options = [])
 * @method static V20170906\ListFaceGroupPhotos listFaceGroupPhotos(array $options = [])
 * @method static V20170906\ListFaceGroups listFaceGroups(array $options = [])
 * @method static V20170906\ListFaceJobs listFaceJobs(array $options = [])
 * @method static V20170906\ListFaceSearchGroupImages listFaceSearchGroupImages(array $options = [])
 * @method static V20170906\ListFaceSearchGroupUsers listFaceSearchGroupUsers(array $options = [])
 * @method static V20170906\ListFaceSearchGroups listFaceSearchGroups(array $options = [])
 * @method static V20170906\ListFaceSets listFaceSets(array $options = [])
 * @method static V20170906\ListImageFaces listImageFaces(array $options = [])
 * @method static V20170906\ListImageJobs listImageJobs(array $options = [])
 * @method static V20170906\ListImages listImages(array $options = [])
 * @method static V20170906\ListOfficeConversionTask listOfficeConversionTask(array $options = [])
 * @method static V20170906\ListPhotoProcessTasks listPhotoProcessTasks(array $options = [])
 * @method static V20170906\ListPornBatchDetectJobs listPornBatchDetectJobs(array $options = [])
 * @method static V20170906\ListProjects listProjects(array $options = [])
 * @method static V20170906\ListSetTags listSetTags(array $options = [])
 * @method static V20170906\ListSets listSets(array $options = [])
 * @method static V20170906\ListTagJobs listTagJobs(array $options = [])
 * @method static V20170906\ListTagNames listTagNames(array $options = [])
 * @method static V20170906\ListTagPhotos listTagPhotos(array $options = [])
 * @method static V20170906\ListTagSets listTagSets(array $options = [])
 * @method static V20170906\ListVideoAudios listVideoAudios(array $options = [])
 * @method static V20170906\ListVideoFrames listVideoFrames(array $options = [])
 * @method static V20170906\ListVideoTasks listVideoTasks(array $options = [])
 * @method static V20170906\ListVideos listVideos(array $options = [])
 * @method static V20170906\PhotoProcess photoProcess(array $options = [])
 * @method static V20170906\PutProject putProject(array $options = [])
 * @method static V20170906\RegistFace registFace(array $options = [])
 * @method static V20170906\SearchDocIndex searchDocIndex(array $options = [])
 * @method static V20170906\SearchFace searchFace(array $options = [])
 * @method static V20170906\SearchImages searchImages(array $options = [])
 * @method static V20170906\SearchImagesByTagNames searchImagesByTagNames(array $options = [])
 * @method static V20170906\UpdateDocIndexMeta updateDocIndexMeta(array $options = [])
 * @method static V20170906\UpdateFaceGroupById updateFaceGroupById(array $options = [])
 * @method static V20170906\UpdateImage updateImage(array $options = [])
 * @method static V20170906\UpdateProject updateProject(array $options = [])
 * @method static V20170906\UpdateSet updateSet(array $options = [])
 */
class ImmV20170906
{
    use ApiResolverTrait;

    /**
     * @var string
     */
    protected $namespace = 'AlibabaCloud\\Imm\\V20170906';
}
