<?php

namespace AlibabaCloud\Mts;

use AlibabaCloud\ApiResolverTrait;

/**
 * Find the specified Api of the Mts based on the method name as the Api name.
 *
 * @package   AlibabaCloud\Mts
 *
 * @method V20140618\ActivateMediaWorkflow activateMediaWorkflow(array $options = [])
 * @method V20140618\AddAsrPipeline addAsrPipeline(array $options = [])
 * @method V20140618\AddCategory addCategory(array $options = [])
 * @method V20140618\AddCensorPipeline addCensorPipeline(array $options = [])
 * @method V20140618\AddCoverPipeline addCoverPipeline(array $options = [])
 * @method V20140618\AddKwsPipeline addKwsPipeline(array $options = [])
 * @method V20140618\AddMedia addMedia(array $options = [])
 * @method V20140618\AddMediaTag addMediaTag(array $options = [])
 * @method V20140618\AddMediaWorkflow addMediaWorkflow(array $options = [])
 * @method V20140618\AddPipeline addPipeline(array $options = [])
 * @method V20140618\AddPornPipeline addPornPipeline(array $options = [])
 * @method V20140618\AddTemplate addTemplate(array $options = [])
 * @method V20140618\AddTerrorismPipeline addTerrorismPipeline(array $options = [])
 * @method V20140618\AddVideoSummaryPipeline addVideoSummaryPipeline(array $options = [])
 * @method V20140618\AddWaterMarkTemplate addWaterMarkTemplate(array $options = [])
 * @method V20140618\BindInputBucket bindInputBucket(array $options = [])
 * @method V20140618\BindOutputBucket bindOutputBucket(array $options = [])
 * @method V20140618\CancelJob cancelJob(array $options = [])
 * @method V20140618\CategoryTree categoryTree(array $options = [])
 * @method V20140618\CheckResource checkResource(array $options = [])
 * @method V20140618\CreateKwsDictionary createKwsDictionary(array $options = [])
 * @method V20140618\CreateMcuTemplate createMcuTemplate(array $options = [])
 * @method V20140618\CreateSession createSession(array $options = [])
 * @method V20140618\DeactivateMediaWorkflow deactivateMediaWorkflow(array $options = [])
 * @method V20140618\DecryptKey decryptKey(array $options = [])
 * @method V20140618\DeleteCategory deleteCategory(array $options = [])
 * @method V20140618\DeleteKwsDictionary deleteKwsDictionary(array $options = [])
 * @method V20140618\DeleteMcuJob deleteMcuJob(array $options = [])
 * @method V20140618\DeleteMcuTemplate deleteMcuTemplate(array $options = [])
 * @method V20140618\DeleteMedia deleteMedia(array $options = [])
 * @method V20140618\DeleteMediaTag deleteMediaTag(array $options = [])
 * @method V20140618\DeleteMediaWorkflow deleteMediaWorkflow(array $options = [])
 * @method V20140618\DeletePipeline deletePipeline(array $options = [])
 * @method V20140618\DeleteTemplate deleteTemplate(array $options = [])
 * @method V20140618\DeleteWaterMarkTemplate deleteWaterMarkTemplate(array $options = [])
 * @method V20140618\DescribeMtsUserResourcePackage describeMtsUserResourcePackage(array $options = [])
 * @method V20140618\GetLicense getLicense(array $options = [])
 * @method V20140618\GetPackage getPackage(array $options = [])
 * @method V20140618\ListAllCategory listAllCategory(array $options = [])
 * @method V20140618\ListAllMediaBucket listAllMediaBucket(array $options = [])
 * @method V20140618\ListAllMediaStorage listAllMediaStorage(array $options = [])
 * @method V20140618\ListAsrPipeline listAsrPipeline(array $options = [])
 * @method V20140618\ListCensorPipeline listCensorPipeline(array $options = [])
 * @method V20140618\ListCoverPipeline listCoverPipeline(array $options = [])
 * @method V20140618\ListFpShotJob listFpShotJob(array $options = [])
 * @method V20140618\ListJob listJob(array $options = [])
 * @method V20140618\ListKwsPipeline listKwsPipeline(array $options = [])
 * @method V20140618\ListMedia listMedia(array $options = [])
 * @method V20140618\ListMediaCensorJob listMediaCensorJob(array $options = [])
 * @method V20140618\ListMediaWorkflowExecutions listMediaWorkflowExecutions(array $options = [])
 * @method V20140618\ListPornPipeline listPornPipeline(array $options = [])
 * @method V20140618\ListTerrorismPipeline listTerrorismPipeline(array $options = [])
 * @method V20140618\ListVideoSummaryPipeline listVideoSummaryPipeline(array $options = [])
 * @method V20140618\LogicalDeleteResource logicalDeleteResource(array $options = [])
 * @method V20140618\PhysicalDeleteResource physicalDeleteResource(array $options = [])
 * @method V20140618\PlayInfo playInfo(array $options = [])
 * @method V20140618\PlayerAuth playerAuth(array $options = [])
 * @method V20140618\QueryAnalysisJobList queryAnalysisJobList(array $options = [])
 * @method V20140618\QueryAnnotationJobList queryAnnotationJobList(array $options = [])
 * @method V20140618\QueryAsrJobList queryAsrJobList(array $options = [])
 * @method V20140618\QueryAsrPipelineList queryAsrPipelineList(array $options = [])
 * @method V20140618\QueryAuthConfig queryAuthConfig(array $options = [])
 * @method V20140618\QueryCensorJobList queryCensorJobList(array $options = [])
 * @method V20140618\QueryCensorPipelineList queryCensorPipelineList(array $options = [])
 * @method V20140618\QueryComplexJobList queryComplexJobList(array $options = [])
 * @method V20140618\QueryCoverJobList queryCoverJobList(array $options = [])
 * @method V20140618\QueryCoverPipelineList queryCoverPipelineList(array $options = [])
 * @method V20140618\QueryEditingJobList queryEditingJobList(array $options = [])
 * @method V20140618\QueryFacerecogJobList queryFacerecogJobList(array $options = [])
 * @method V20140618\QueryFpImportResult queryFpImportResult(array $options = [])
 * @method V20140618\QueryFpShotJobList queryFpShotJobList(array $options = [])
 * @method V20140618\QueryImageSearchJobList queryImageSearchJobList(array $options = [])
 * @method V20140618\QueryJobList queryJobList(array $options = [])
 * @method V20140618\QueryKwsDictionary queryKwsDictionary(array $options = [])
 * @method V20140618\QueryKwsJobList queryKwsJobList(array $options = [])
 * @method V20140618\QueryKwsPipelineList queryKwsPipelineList(array $options = [])
 * @method V20140618\QueryMcuJob queryMcuJob(array $options = [])
 * @method V20140618\QueryMcuTemplate queryMcuTemplate(array $options = [])
 * @method V20140618\QueryMediaCensorJobDetail queryMediaCensorJobDetail(array $options = [])
 * @method V20140618\QueryMediaCensorJobList queryMediaCensorJobList(array $options = [])
 * @method V20140618\QueryMediaDetailJobList queryMediaDetailJobList(array $options = [])
 * @method V20140618\QueryMediaFpDeleteJobList queryMediaFpDeleteJobList(array $options = [])
 * @method V20140618\QueryMediaInfoJobList queryMediaInfoJobList(array $options = [])
 * @method V20140618\QueryMediaList queryMediaList(array $options = [])
 * @method V20140618\QueryMediaListByURL queryMediaListByURL(array $options = [])
 * @method V20140618\QueryMediaWorkflowExecutionList queryMediaWorkflowExecutionList(array $options = [])
 * @method V20140618\QueryMediaWorkflowList queryMediaWorkflowList(array $options = [])
 * @method V20140618\QueryPipelineList queryPipelineList(array $options = [])
 * @method V20140618\QueryPornJobList queryPornJobList(array $options = [])
 * @method V20140618\QueryPornPipelineList queryPornPipelineList(array $options = [])
 * @method V20140618\QuerySnapshotJobList querySnapshotJobList(array $options = [])
 * @method V20140618\QuerySubtitleJobList querySubtitleJobList(array $options = [])
 * @method V20140618\QueryTagJobList queryTagJobList(array $options = [])
 * @method V20140618\QueryTemplateList queryTemplateList(array $options = [])
 * @method V20140618\QueryTerrorismJobList queryTerrorismJobList(array $options = [])
 * @method V20140618\QueryTerrorismPipelineList queryTerrorismPipelineList(array $options = [])
 * @method V20140618\QueryVideoGifJobList queryVideoGifJobList(array $options = [])
 * @method V20140618\QueryVideoPoseJobList queryVideoPoseJobList(array $options = [])
 * @method V20140618\QueryVideoSplitJobList queryVideoSplitJobList(array $options = [])
 * @method V20140618\QueryVideoSummaryJobList queryVideoSummaryJobList(array $options = [])
 * @method V20140618\QueryVideoSummaryPipelineList queryVideoSummaryPipelineList(array $options = [])
 * @method V20140618\QueryWaterMarkTemplateList queryWaterMarkTemplateList(array $options = [])
 * @method V20140618\RefreshCdnDomainConfigsCache refreshCdnDomainConfigsCache(array $options = [])
 * @method V20140618\RegisterMediaDetailPerson registerMediaDetailPerson(array $options = [])
 * @method V20140618\RegisterMediaDetailScenario registerMediaDetailScenario(array $options = [])
 * @method V20140618\ReportAnnotationJobResult reportAnnotationJobResult(array $options = [])
 * @method V20140618\ReportAsrJobResult reportAsrJobResult(array $options = [])
 * @method V20140618\ReportCensorJobResult reportCensorJobResult(array $options = [])
 * @method V20140618\ReportCoverJobResult reportCoverJobResult(array $options = [])
 * @method V20140618\ReportFacerecogJobResult reportFacerecogJobResult(array $options = [])
 * @method V20140618\ReportFpShotJobResult reportFpShotJobResult(array $options = [])
 * @method V20140618\ReportMediaDetailJobResult reportMediaDetailJobResult(array $options = [])
 * @method V20140618\ReportPornJobResult reportPornJobResult(array $options = [])
 * @method V20140618\ReportTagJobResult reportTagJobResult(array $options = [])
 * @method V20140618\ReportTerrorismJobResult reportTerrorismJobResult(array $options = [])
 * @method V20140618\ReportVideoSplitJobResult reportVideoSplitJobResult(array $options = [])
 * @method V20140618\SearchMedia searchMedia(array $options = [])
 * @method V20140618\SearchMediaWorkflow searchMediaWorkflow(array $options = [])
 * @method V20140618\SearchPipeline searchPipeline(array $options = [])
 * @method V20140618\SearchTemplate searchTemplate(array $options = [])
 * @method V20140618\SearchWaterMarkTemplate searchWaterMarkTemplate(array $options = [])
 * @method V20140618\SetAuthConfig setAuthConfig(array $options = [])
 * @method V20140618\SubmitAnalysisJob submitAnalysisJob(array $options = [])
 * @method V20140618\SubmitAnnotationJob submitAnnotationJob(array $options = [])
 * @method V20140618\SubmitAsrJob submitAsrJob(array $options = [])
 * @method V20140618\SubmitComplexJob submitComplexJob(array $options = [])
 * @method V20140618\SubmitCoverJob submitCoverJob(array $options = [])
 * @method V20140618\SubmitEditingJobs submitEditingJobs(array $options = [])
 * @method V20140618\SubmitFacerecogJob submitFacerecogJob(array $options = [])
 * @method V20140618\SubmitFpShotJob submitFpShotJob(array $options = [])
 * @method V20140618\SubmitImageQuality submitImageQuality(array $options = [])
 * @method V20140618\SubmitImageQualityJob submitImageQualityJob(array $options = [])
 * @method V20140618\SubmitImageSearchJob submitImageSearchJob(array $options = [])
 * @method V20140618\SubmitJobs submitJobs(array $options = [])
 * @method V20140618\SubmitKwsJob submitKwsJob(array $options = [])
 * @method V20140618\SubmitMcuJob submitMcuJob(array $options = [])
 * @method V20140618\SubmitMediaCensorJob submitMediaCensorJob(array $options = [])
 * @method V20140618\SubmitMediaDetailJob submitMediaDetailJob(array $options = [])
 * @method V20140618\SubmitMediaFpDeleteJob submitMediaFpDeleteJob(array $options = [])
 * @method V20140618\SubmitMediaInfoJob submitMediaInfoJob(array $options = [])
 * @method V20140618\SubmitPornJob submitPornJob(array $options = [])
 * @method V20140618\SubmitSnapshotJob submitSnapshotJob(array $options = [])
 * @method V20140618\SubmitSubtitleJob submitSubtitleJob(array $options = [])
 * @method V20140618\SubmitTagJob submitTagJob(array $options = [])
 * @method V20140618\SubmitTerrorismJob submitTerrorismJob(array $options = [])
 * @method V20140618\SubmitVideoGifJob submitVideoGifJob(array $options = [])
 * @method V20140618\SubmitVideoPoseJob submitVideoPoseJob(array $options = [])
 * @method V20140618\SubmitVideoSplitJob submitVideoSplitJob(array $options = [])
 * @method V20140618\SubmitVideoSummaryJob submitVideoSummaryJob(array $options = [])
 * @method V20140618\UnbindInputBucket unbindInputBucket(array $options = [])
 * @method V20140618\UnbindOutputBucket unbindOutputBucket(array $options = [])
 * @method V20140618\UnindInputBucket unindInputBucket(array $options = [])
 * @method V20140618\UpdateAsrPipeline updateAsrPipeline(array $options = [])
 * @method V20140618\UpdateCategoryName updateCategoryName(array $options = [])
 * @method V20140618\UpdateCensorPipeline updateCensorPipeline(array $options = [])
 * @method V20140618\UpdateCoverPipeline updateCoverPipeline(array $options = [])
 * @method V20140618\UpdateKwsDictionary updateKwsDictionary(array $options = [])
 * @method V20140618\UpdateKwsPipeline updateKwsPipeline(array $options = [])
 * @method V20140618\UpdateMcuTemplate updateMcuTemplate(array $options = [])
 * @method V20140618\UpdateMedia updateMedia(array $options = [])
 * @method V20140618\UpdateMediaCategory updateMediaCategory(array $options = [])
 * @method V20140618\UpdateMediaCover updateMediaCover(array $options = [])
 * @method V20140618\UpdateMediaPublishState updateMediaPublishState(array $options = [])
 * @method V20140618\UpdateMediaWorkflow updateMediaWorkflow(array $options = [])
 * @method V20140618\UpdateMediaWorkflowTriggerMode updateMediaWorkflowTriggerMode(array $options = [])
 * @method V20140618\UpdatePipeline updatePipeline(array $options = [])
 * @method V20140618\UpdatePornPipeline updatePornPipeline(array $options = [])
 * @method V20140618\UpdateTemplate updateTemplate(array $options = [])
 * @method V20140618\UpdateTerrorismPipeline updateTerrorismPipeline(array $options = [])
 * @method V20140618\UpdateVideoSummaryPipeline updateVideoSummaryPipeline(array $options = [])
 * @method V20140618\UpdateWaterMarkTemplate updateWaterMarkTemplate(array $options = [])
 */
class MtsV20140618ApiResolver
{
    use ApiResolverTrait;

    /**
     * @var string
     */
    protected $namespace = 'AlibabaCloud\\Mts\\V20140618';
}
