<?php

namespace AlibabaCloud\Cr\V20160607;

use AlibabaCloud\ApiResolverTrait;

/**
 * Resolve Api based on the method name.
 *
 * @method DeleteUserSourceAccount deleteUserSourceAccount(array $options = [])
 * @method GetRepoSyncTaskList getRepoSyncTaskList(array $options = [])
 * @method DeleteImage deleteImage(array $options = [])
 * @method GetAuthorizationToken getAuthorizationToken(array $options = [])
 * @method UpdateRepoSourceRepo updateRepoSourceRepo(array $options = [])
 * @method GetRepoBuildList getRepoBuildList(array $options = [])
 * @method GetRepoWebhookLogList getRepoWebhookLogList(array $options = [])
 * @method GetUserSourceRepoRefList getUserSourceRepoRefList(array $options = [])
 * @method GetRepoSourceRepo getRepoSourceRepo(array $options = [])
 * @method CreateUserInfo createUserInfo(array $options = [])
 * @method SearchRepo searchRepo(array $options = [])
 * @method GetUserSourceRepoList getUserSourceRepoList(array $options = [])
 * @method UpdateUserInfo updateUserInfo(array $options = [])
 * @method GetRepoBuildRuleList getRepoBuildRuleList(array $options = [])
 * @method GetUserSourceAccount getUserSourceAccount(array $options = [])
 * @method GetSubUserList getSubUserList(array $options = [])
 * @method GetNamespace getNamespace(array $options = [])
 * @method GetMirrorList getMirrorList(array $options = [])
 * @method CreateUserSourceAccount createUserSourceAccount(array $options = [])
 * @method UpdateRepoWebhook updateRepoWebhook(array $options = [])
 * @method UpdateRepo updateRepo(array $options = [])
 * @method UpdateRepoAuthorization updateRepoAuthorization(array $options = [])
 * @method UpdateRepoBuildRule updateRepoBuildRule(array $options = [])
 * @method UpdateNamespace updateNamespace(array $options = [])
 * @method UpdateNamespaceAuthorization updateNamespaceAuthorization(array $options = [])
 * @method StartRepoBuildByRule startRepoBuildByRule(array $options = [])
 * @method StartImageScan startImageScan(array $options = [])
 * @method GetImageScan getImageScan(array $options = [])
 * @method GetImageLayer getImageLayer(array $options = [])
 * @method DeleteRepoBuildRule deleteRepoBuildRule(array $options = [])
 * @method DeleteNamespace deleteNamespace(array $options = [])
 * @method CreateRepoBuildRule createRepoBuildRule(array $options = [])
 * @method CancelRepoBuild cancelRepoBuild(array $options = [])
 * @method GetRepoBatch getRepoBatch(array $options = [])
 * @method GetImageManifest getImageManifest(array $options = [])
 * @method GetCollection getCollection(array $options = [])
 * @method DeleteCollection deleteCollection(array $options = [])
 * @method CreateCollection createCollection(array $options = [])
 * @method GetSearch getSearch(array $options = [])
 * @method CreateNamespace createNamespace(array $options = [])
 * @method GetRepoWebhook getRepoWebhook(array $options = [])
 * @method DeleteRepoWebhook deleteRepoWebhook(array $options = [])
 * @method GetRepo getRepo(array $options = [])
 * @method GetNamespaceList getNamespaceList(array $options = [])
 * @method GetRepoListByNamespace getRepoListByNamespace(array $options = [])
 * @method CreateRepoSyncTask createRepoSyncTask(array $options = [])
 * @method CreateRepoTagSyncTask createRepoTagSyncTask(array $options = [])
 * @method GetRepoSyncTask getRepoSyncTask(array $options = [])
 * @method CreateRepoTagSync createRepoTagSync(array $options = [])
 * @method GetRegionList getRegionList(array $options = [])
 * @method GetRepoAuthorizationList getRepoAuthorizationList(array $options = [])
 * @method DeleteRepoAuthorization deleteRepoAuthorization(array $options = [])
 * @method GetNamespaceAuthorizationList getNamespaceAuthorizationList(array $options = [])
 * @method CreateRepoWebhook createRepoWebhook(array $options = [])
 * @method DeleteNamespaceAuthorization deleteNamespaceAuthorization(array $options = [])
 * @method DeleteRepo deleteRepo(array $options = [])
 * @method CreateRepoAuthorization createRepoAuthorization(array $options = [])
 * @method CreateNamespaceAuthorization createNamespaceAuthorization(array $options = [])
 * @method GetUserInfo getUserInfo(array $options = [])
 * @method CreateRepo createRepo(array $options = [])
 * @method GetRepoBuildLogs getRepoBuildLogs(array $options = [])
 * @method GetRepoBuildStatus getRepoBuildStatus(array $options = [])
 * @method GetRepoList getRepoList(array $options = [])
 * @method GetRepoTags getRepoTags(array $options = [])
 * @method StartRepoBuild startRepoBuild(array $options = [])
 */
class CrApiResolver
{
    use ApiResolverTrait;
}
