<?php

namespace AlibabaCloud\Dds;

use AlibabaCloud\ApiResolverTrait;

/**
 * Find the specified Api of the Dds based on the method name as the Api name.
 *
 * @package   AlibabaCloud\Dds
 *
 * @method V20151201\AddBindingTunnel addBindingTunnel(array $options = [])
 * @method V20151201\AddMonitorNode addMonitorNode(array $options = [])
 * @method V20151201\AllocatePublicNetworkAddress allocatePublicNetworkAddress(array $options = [])
 * @method V20151201\BindTunnel bindTunnel(array $options = [])
 * @method V20151201\CheckConnectivity checkConnectivity(array $options = [])
 * @method V20151201\CreateBackup createBackup(array $options = [])
 * @method V20151201\CreateDBInstance createDBInstance(array $options = [])
 * @method V20151201\CreateMonitorInstance createMonitorInstance(array $options = [])
 * @method V20151201\CreateNode createNode(array $options = [])
 * @method V20151201\CreateRecommendationTask createRecommendationTask(array $options = [])
 * @method V20151201\CreateReplicationGroup createReplicationGroup(array $options = [])
 * @method V20151201\CreateShardingDBInstance createShardingDBInstance(array $options = [])
 * @method V20151201\CreateStaticVerification createStaticVerification(array $options = [])
 * @method V20151201\DeleteDBInstance deleteDBInstance(array $options = [])
 * @method V20151201\DeleteMonitorInstance deleteMonitorInstance(array $options = [])
 * @method V20151201\DeleteMonitorNode deleteMonitorNode(array $options = [])
 * @method V20151201\DeleteNode deleteNode(array $options = [])
 * @method V20151201\DeleteReplicationGroup deleteReplicationGroup(array $options = [])
 * @method V20151201\DescribeAccounts describeAccounts(array $options = [])
 * @method V20151201\DescribeActiveOperationTask describeActiveOperationTask(array $options = [])
 * @method V20151201\DescribeActiveOperationTaskCount describeActiveOperationTaskCount(array $options = [])
 * @method V20151201\DescribeActiveOperationTaskRegion describeActiveOperationTaskRegion(array $options = [])
 * @method V20151201\DescribeActiveOperationTaskType describeActiveOperationTaskType(array $options = [])
 * @method V20151201\DescribeAuditFiles describeAuditFiles(array $options = [])
 * @method V20151201\DescribeAuditLogFilter describeAuditLogFilter(array $options = [])
 * @method V20151201\DescribeAuditPolicy describeAuditPolicy(array $options = [])
 * @method V20151201\DescribeAuditRecords describeAuditRecords(array $options = [])
 * @method V20151201\DescribeAvailableEngineVersion describeAvailableEngineVersion(array $options = [])
 * @method V20151201\DescribeAvailableTimeRange describeAvailableTimeRange(array $options = [])
 * @method V20151201\DescribeAvaliableTimeRange describeAvaliableTimeRange(array $options = [])
 * @method V20151201\DescribeBackupPolicy describeBackupPolicy(array $options = [])
 * @method V20151201\DescribeBackups describeBackups(array $options = [])
 * @method V20151201\DescribeConnectionInfo describeConnectionInfo(array $options = [])
 * @method V20151201\DescribeDBInstanceAttribute describeDBInstanceAttribute(array $options = [])
 * @method V20151201\DescribeDBInstanceMonitor describeDBInstanceMonitor(array $options = [])
 * @method V20151201\DescribeDBInstancePerformance describeDBInstancePerformance(array $options = [])
 * @method V20151201\DescribeDBInstanceSSL describeDBInstanceSSL(array $options = [])
 * @method V20151201\DescribeDBInstances describeDBInstances(array $options = [])
 * @method V20151201\DescribeDynamicVerificationList describeDynamicVerificationList(array $options = [])
 * @method V20151201\DescribeErrorLogRecords describeErrorLogRecords(array $options = [])
 * @method V20151201\DescribeIndexRecommendation describeIndexRecommendation(array $options = [])
 * @method V20151201\DescribeInstanceAutoRenewalAttribute describeInstanceAutoRenewalAttribute(array $options = [])
 * @method V20151201\DescribeKernelReleaseNotes describeKernelReleaseNotes(array $options = [])
 * @method V20151201\DescribeMonitorAttribute describeMonitorAttribute(array $options = [])
 * @method V20151201\DescribeMonitorInstances describeMonitorInstances(array $options = [])
 * @method V20151201\DescribeParameterModificationHistory describeParameterModificationHistory(array $options = [])
 * @method V20151201\DescribeParameterTemplates describeParameterTemplates(array $options = [])
 * @method V20151201\DescribeParameters describeParameters(array $options = [])
 * @method V20151201\DescribePerformanceInfo describePerformanceInfo(array $options = [])
 * @method V20151201\DescribeRdsVSwitchs describeRdsVSwitchs(array $options = [])
 * @method V20151201\DescribeRdsVpcs describeRdsVpcs(array $options = [])
 * @method V20151201\DescribeRegions describeRegions(array $options = [])
 * @method V20151201\DescribeRenewalPrice describeRenewalPrice(array $options = [])
 * @method V20151201\DescribeReplicaConflictInfo describeReplicaConflictInfo(array $options = [])
 * @method V20151201\DescribeReplicaInitializeProgress describeReplicaInitializeProgress(array $options = [])
 * @method V20151201\DescribeReplicaPerformance describeReplicaPerformance(array $options = [])
 * @method V20151201\DescribeReplicaSetRole describeReplicaSetRole(array $options = [])
 * @method V20151201\DescribeReplicaUsage describeReplicaUsage(array $options = [])
 * @method V20151201\DescribeReplicas describeReplicas(array $options = [])
 * @method V20151201\DescribeReplicationGroup describeReplicationGroup(array $options = [])
 * @method V20151201\DescribeRunningLogRecords describeRunningLogRecords(array $options = [])
 * @method V20151201\DescribeSecurityIps describeSecurityIps(array $options = [])
 * @method V20151201\DescribeShardingNetworkAddress describeShardingNetworkAddress(array $options = [])
 * @method V20151201\DescribeSlowLogRecords describeSlowLogRecords(array $options = [])
 * @method V20151201\DescribeStaticVerificationList describeStaticVerificationList(array $options = [])
 * @method V20151201\DescribeStrategy describeStrategy(array $options = [])
 * @method V20151201\DescribeTargetAVZ describeTargetAVZ(array $options = [])
 * @method V20151201\DescribeVerificationList describeVerificationList(array $options = [])
 * @method V20151201\DestroyInstance destroyInstance(array $options = [])
 * @method V20151201\EvaluateFailOverSwitch evaluateFailOverSwitch(array $options = [])
 * @method V20151201\EvaluateResource evaluateResource(array $options = [])
 * @method V20151201\ListReplicationGroup listReplicationGroup(array $options = [])
 * @method V20151201\MigrateToOtherZone migrateToOtherZone(array $options = [])
 * @method V20151201\ModifyAccountDescription modifyAccountDescription(array $options = [])
 * @method V20151201\ModifyAccountInfo modifyAccountInfo(array $options = [])
 * @method V20151201\ModifyActiveOperationPendingTask modifyActiveOperationPendingTask(array $options = [])
 * @method V20151201\ModifyActiveOperationTask modifyActiveOperationTask(array $options = [])
 * @method V20151201\ModifyAuditLogFilter modifyAuditLogFilter(array $options = [])
 * @method V20151201\ModifyAuditPolicy modifyAuditPolicy(array $options = [])
 * @method V20151201\ModifyBackupPolicy modifyBackupPolicy(array $options = [])
 * @method V20151201\ModifyConnectionInfo modifyConnectionInfo(array $options = [])
 * @method V20151201\ModifyDBInstanceConnectionString modifyDBInstanceConnectionString(array $options = [])
 * @method V20151201\ModifyDBInstanceDescription modifyDBInstanceDescription(array $options = [])
 * @method V20151201\ModifyDBInstanceMaintainTime modifyDBInstanceMaintainTime(array $options = [])
 * @method V20151201\ModifyDBInstanceMonitor modifyDBInstanceMonitor(array $options = [])
 * @method V20151201\ModifyDBInstanceNetExpireTime modifyDBInstanceNetExpireTime(array $options = [])
 * @method V20151201\ModifyDBInstanceNetworkType modifyDBInstanceNetworkType(array $options = [])
 * @method V20151201\ModifyDBInstanceSSL modifyDBInstanceSSL(array $options = [])
 * @method V20151201\ModifyDBInstanceSpec modifyDBInstanceSpec(array $options = [])
 * @method V20151201\ModifyDescribetion modifyDescribetion(array $options = [])
 * @method V20151201\ModifyDynamicMode modifyDynamicMode(array $options = [])
 * @method V20151201\ModifyGuardDomainMode modifyGuardDomainMode(array $options = [])
 * @method V20151201\ModifyInstanceAutoRenewalAttribute modifyInstanceAutoRenewalAttribute(array $options = [])
 * @method V20151201\ModifyNodeSpec modifyNodeSpec(array $options = [])
 * @method V20151201\ModifyParameter modifyParameter(array $options = [])
 * @method V20151201\ModifyParameters modifyParameters(array $options = [])
 * @method V20151201\ModifyReplicaDescription modifyReplicaDescription(array $options = [])
 * @method V20151201\ModifyReplicaDynamicMode modifyReplicaDynamicMode(array $options = [])
 * @method V20151201\ModifyReplicaFilterMode modifyReplicaFilterMode(array $options = [])
 * @method V20151201\ModifyReplicaMode modifyReplicaMode(array $options = [])
 * @method V20151201\ModifyReplicaRecoverMode modifyReplicaRecoverMode(array $options = [])
 * @method V20151201\ModifyReplicaRecoveryMode modifyReplicaRecoveryMode(array $options = [])
 * @method V20151201\ModifyReplicaRelation modifyReplicaRelation(array $options = [])
 * @method V20151201\ModifyReplicaVerificationMode modifyReplicaVerificationMode(array $options = [])
 * @method V20151201\ModifyReplicationGroup modifyReplicationGroup(array $options = [])
 * @method V20151201\ModifySecurityIps modifySecurityIps(array $options = [])
 * @method V20151201\RebuildInstance rebuildInstance(array $options = [])
 * @method V20151201\ReleasePublicNetworkAddress releasePublicNetworkAddress(array $options = [])
 * @method V20151201\ReleaseReplica releaseReplica(array $options = [])
 * @method V20151201\RenewDBInstance renewDBInstance(array $options = [])
 * @method V20151201\ResetAccountPassword resetAccountPassword(array $options = [])
 * @method V20151201\RestartDBInstance restartDBInstance(array $options = [])
 * @method V20151201\RestoreDBInstance restoreDBInstance(array $options = [])
 * @method V20151201\Sample sample(array $options = [])
 * @method V20151201\SwitchDBInstanceHA switchDBInstanceHA(array $options = [])
 * @method V20151201\SwithcDBInstanceHA swithcDBInstanceHA(array $options = [])
 * @method V20151201\TransformToPrePaid transformToPrePaid(array $options = [])
 * @method V20151201\UnbindTunnel unbindTunnel(array $options = [])
 * @method V20151201\UpgradeDBInstanceEngineVersion upgradeDBInstanceEngineVersion(array $options = [])
 * @method V20151201\UpgradeDBInstanceKernelVersion upgradeDBInstanceKernelVersion(array $options = [])
 */
class DdsV20151201ApiResolver
{
    use ApiResolverTrait;

    /**
     * @var string
     */
    protected $namespace = 'AlibabaCloud\\Dds\\V20151201';
}
