<?php

namespace AlibabaCloud\Ess\V20140828;

use AlibabaCloud\ApiResolverTrait;

/**
 * Resolve Api based on the method name.
 *
 * @method CheckScalingGroupAvailability checkScalingGroupAvailability(array $options = [])
 * @method DetachVServerGroups detachVServerGroups(array $options = [])
 * @method AttachVServerGroups attachVServerGroups(array $options = [])
 * @method DetachDBInstances detachDBInstances(array $options = [])
 * @method AttachDBInstances attachDBInstances(array $options = [])
 * @method ModifyScalingConfiguration modifyScalingConfiguration(array $options = [])
 * @method DescribeLoadBalancers describeLoadBalancers(array $options = [])
 * @method DetachLoadBalancers detachLoadBalancers(array $options = [])
 * @method AttachLoadBalancers attachLoadBalancers(array $options = [])
 * @method CreateAlarm createAlarm(array $options = [])
 * @method EnableAlarm enableAlarm(array $options = [])
 * @method ModifyAlarm modifyAlarm(array $options = [])
 * @method DeleteAlarm deleteAlarm(array $options = [])
 * @method DescribeAlarms describeAlarms(array $options = [])
 * @method DisableAlarm disableAlarm(array $options = [])
 * @method RebalanceInstances rebalanceInstances(array $options = [])
 * @method ModifyNotificationConfiguration modifyNotificationConfiguration(array $options = [])
 * @method SetInstancesProtection setInstancesProtection(array $options = [])
 * @method DeleteNotificationConfiguration deleteNotificationConfiguration(array $options = [])
 * @method DescribeNotificationTypes describeNotificationTypes(array $options = [])
 * @method DescribeNotificationConfigurations describeNotificationConfigurations(array $options = [])
 * @method CreateNotificationConfiguration createNotificationConfiguration(array $options = [])
 * @method DescribeLifecycleHooks describeLifecycleHooks(array $options = [])
 * @method ModifyLifecycleHook modifyLifecycleHook(array $options = [])
 * @method CompleteLifecycleAction completeLifecycleAction(array $options = [])
 * @method DeleteLifecycleHook deleteLifecycleHook(array $options = [])
 * @method RecordLifecycleActionHeartbeat recordLifecycleActionHeartbeat(array $options = [])
 * @method CreateLifecycleHook createLifecycleHook(array $options = [])
 * @method EnterStandby enterStandby(array $options = [])
 * @method ExitStandby exitStandby(array $options = [])
 * @method DeactivateScalingConfiguration deactivateScalingConfiguration(array $options = [])
 * @method OrderSucceededCallback orderSucceededCallback(array $options = [])
 * @method ModifyAlertConfig modifyAlertConfig(array $options = [])
 * @method DescribeAlertConfig describeAlertConfig(array $options = [])
 * @method SpiCallExecuteScalingRule spiCallExecuteScalingRule(array $options = [])
 * @method UserOperation userOperation(array $options = [])
 * @method CountScalingActivitiesInWorker countScalingActivitiesInWorker(array $options = [])
 * @method VerifyAuthentication verifyAuthentication(array $options = [])
 * @method VerifyUser verifyUser(array $options = [])
 * @method DescribeAccountAttributes describeAccountAttributes(array $options = [])
 * @method DescribeScalingActivityDetail describeScalingActivityDetail(array $options = [])
 * @method DescribeLimitation describeLimitation(array $options = [])
 * @method DescribeCapacityHistory describeCapacityHistory(array $options = [])
 * @method DescribeRegions describeRegions(array $options = [])
 * @method AttachInstances attachInstances(array $options = [])
 * @method CreateScalingRule createScalingRule(array $options = [])
 * @method CreateScalingGroup createScalingGroup(array $options = [])
 * @method CreateScalingConfiguration createScalingConfiguration(array $options = [])
 * @method DeleteScalingRule deleteScalingRule(array $options = [])
 * @method DeleteScalingGroup deleteScalingGroup(array $options = [])
 * @method DeleteScalingConfiguration deleteScalingConfiguration(array $options = [])
 * @method CreateScheduledTask createScheduledTask(array $options = [])
 * @method DescribeScalingConfigurations describeScalingConfigurations(array $options = [])
 * @method DescribeScalingActivities describeScalingActivities(array $options = [])
 * @method DeleteScheduledTask deleteScheduledTask(array $options = [])
 * @method DescribeScalingRules describeScalingRules(array $options = [])
 * @method DescribeScalingInstances describeScalingInstances(array $options = [])
 * @method DescribeScalingGroups describeScalingGroups(array $options = [])
 * @method DisableScalingGroup disableScalingGroup(array $options = [])
 * @method DetachInstances detachInstances(array $options = [])
 * @method DescribeScheduledTasks describeScheduledTasks(array $options = [])
 * @method ModifyScalingRule modifyScalingRule(array $options = [])
 * @method ModifyScalingGroup modifyScalingGroup(array $options = [])
 * @method ExecuteScalingRule executeScalingRule(array $options = [])
 * @method EnableScalingGroup enableScalingGroup(array $options = [])
 * @method RemoveInstances removeInstances(array $options = [])
 * @method ModifyScheduledTask modifyScheduledTask(array $options = [])
 */
class EssApiResolver
{
    use ApiResolverTrait;
}
