<?php

namespace AlibabaCloud\LinkWAN\V20181230;

use AlibabaCloud\ApiResolverTrait;

/**
 * Resolve Api based on the method name.
 *
 * @method MeteringQuerySubscribePush meteringQuerySubscribePush(array $options = [])
 * @method MeteringSubscribePush meteringSubscribePush(array $options = [])
 * @method QueryMeteringDetail queryMeteringDetail(array $options = [])
 * @method QueryMeteringStatistics queryMeteringStatistics(array $options = [])
 * @method MeteringUnsubscribePush meteringUnsubscribePush(array $options = [])
 * @method UpdateRoamingJoinPermission updateRoamingJoinPermission(array $options = [])
 * @method UpdateOwnedLocalJoinPermission updateOwnedLocalJoinPermission(array $options = [])
 * @method UpdateRoamingJoinPermissionEnablingState updateRoamingJoinPermissionEnablingState(array $options = [])
 * @method UpdateOwnedLocalJoinPermissionEnablingState updateOwnedLocalJoinPermissionEnablingState(array $options = [])
 * @method ListNodeTransferPacketPaths listNodeTransferPacketPaths(array $options = [])
 * @method CountNodesByNodeGroupId countNodesByNodeGroupId(array $options = [])
 * @method CountNodesByOwnedJoinPermissionId countNodesByOwnedJoinPermissionId(array $options = [])
 * @method ListNodesByNodeGroupId listNodesByNodeGroupId(array $options = [])
 * @method ListNodesByOwnedJoinPermissionId listNodesByOwnedJoinPermissionId(array $options = [])
 * @method SendMulticastCommand sendMulticastCommand(array $options = [])
 * @method SendUnicastCommand sendUnicastCommand(array $options = [])
 * @method ListBoundNodesByMcAddress listBoundNodesByMcAddress(array $options = [])
 * @method GetNodeMulticastConfig getNodeMulticastConfig(array $options = [])
 * @method GetMulticastGroup getMulticastGroup(array $options = [])
 * @method UnbindNodesFromMulticastGroup unbindNodesFromMulticastGroup(array $options = [])
 * @method BindNodesToMulticastGroup bindNodesToMulticastGroup(array $options = [])
 * @method DeleteMulticastGroup deleteMulticastGroup(array $options = [])
 * @method CreateMulticastGroup createMulticastGroup(array $options = [])
 * @method UpdateNotificationsHandleState updateNotificationsHandleState(array $options = [])
 * @method UpdateLabNodeJoinAcceptConfig updateLabNodeJoinAcceptConfig(array $options = [])
 * @method UpdateLabNodeDownlinkConfig updateLabNodeDownlinkConfig(array $options = [])
 * @method UpdateLabNodeDebugConfig updateLabNodeDebugConfig(array $options = [])
 * @method UpdateLabNode updateLabNode(array $options = [])
 * @method UpdateLabGatewayUartCtrl updateLabGatewayUartCtrl(array $options = [])
 * @method UpdateLabGatewaySshCtrl updateLabGatewaySshCtrl(array $options = [])
 * @method UpdateLabGatewayGwmpConfig updateLabGatewayGwmpConfig(array $options = [])
 * @method UpdateLabGateway updateLabGateway(array $options = [])
 * @method UpdateGatewayEnablingState updateGatewayEnablingState(array $options = [])
 * @method UpdateGateway updateGateway(array $options = [])
 * @method UnregisterKpmPublicKey unregisterKpmPublicKey(array $options = [])
 * @method UnbindLabNodeFromLabGateway unbindLabNodeFromLabGateway(array $options = [])
 * @method TriggerLabGatewayLogReport triggerLabGatewayLogReport(array $options = [])
 * @method TriggerLabGatewayDeviceInfoReport triggerLabGatewayDeviceInfoReport(array $options = [])
 * @method TriggerLabGatewayConfigReport triggerLabGatewayConfigReport(array $options = [])
 * @method SubmitNodeTupleOrder submitNodeTupleOrder(array $options = [])
 * @method SubmitGatewayTupleOrder submitGatewayTupleOrder(array $options = [])
 * @method SendMacCommandToLabNode sendMacCommandToLabNode(array $options = [])
 * @method SendBusinessCommandToLabNode sendBusinessCommandToLabNode(array $options = [])
 * @method RegisterKpmPublicKey registerKpmPublicKey(array $options = [])
 * @method RebootLabGateway rebootLabGateway(array $options = [])
 * @method ListNotifications listNotifications(array $options = [])
 * @method ListNodeTupleOrders listNodeTupleOrders(array $options = [])
 * @method ListNodeGroupTransferFlowStats listNodeGroupTransferFlowStats(array $options = [])
 * @method ListLabNodes listLabNodes(array $options = [])
 * @method ListLabNodeLogs listLabNodeLogs(array $options = [])
 * @method ListLabGateways listLabGateways(array $options = [])
 * @method ListLabGatewayLogs listLabGatewayLogs(array $options = [])
 * @method ListGatewayTupleOrders listGatewayTupleOrders(array $options = [])
 * @method ListGatewayTransferPackets listGatewayTransferPackets(array $options = [])
 * @method ListGatewayTransferFlowStats listGatewayTransferFlowStats(array $options = [])
 * @method ListGatewaysGisInfo listGatewaysGisInfo(array $options = [])
 * @method ListGatewayOnlineRecords listGatewayOnlineRecords(array $options = [])
 * @method ListBoundLabNodes listBoundLabNodes(array $options = [])
 * @method ListBoundLabGateways listBoundLabGateways(array $options = [])
 * @method ListActiveGateways listActiveGateways(array $options = [])
 * @method GetUserLicense getUserLicense(array $options = [])
 * @method GetNotification getNotification(array $options = [])
 * @method GetNodeTuplesDownloadUrl getNodeTuplesDownloadUrl(array $options = [])
 * @method GetNodeTupleOrder getNodeTupleOrder(array $options = [])
 * @method GetLabNodeJoinAcceptConfig getLabNodeJoinAcceptConfig(array $options = [])
 * @method GetLabNodeDownlinkConfig getLabNodeDownlinkConfig(array $options = [])
 * @method GetLabNodeDebugConfig getLabNodeDebugConfig(array $options = [])
 * @method GetLabNode getLabNode(array $options = [])
 * @method GetLabGatewayGwmpConfig getLabGatewayGwmpConfig(array $options = [])
 * @method GetLabGateway getLabGateway(array $options = [])
 * @method GetGatewayTuplesDownloadUrl getGatewayTuplesDownloadUrl(array $options = [])
 * @method GetGatewayTupleOrder getGatewayTupleOrder(array $options = [])
 * @method GetGatewayTransferPacketsDownloadUrl getGatewayTransferPacketsDownloadUrl(array $options = [])
 * @method GetGatewayStatusStat getGatewayStatusStat(array $options = [])
 * @method GetGatewayPacketStat getGatewayPacketStat(array $options = [])
 * @method GetGateway getGateway(array $options = [])
 * @method GetFreqBandPlanGroup getFreqBandPlanGroup(array $options = [])
 * @method DescribeRegions describeRegions(array $options = [])
 * @method DeleteLabNode deleteLabNode(array $options = [])
 * @method DeleteLabGateway deleteLabGateway(array $options = [])
 * @method DeleteGateway deleteGateway(array $options = [])
 * @method CreateLabNode createLabNode(array $options = [])
 * @method CreateLabGateway createLabGateway(array $options = [])
 * @method CreateGateway createGateway(array $options = [])
 * @method CountNotifications countNotifications(array $options = [])
 * @method CountNodeTupleOrders countNodeTupleOrders(array $options = [])
 * @method CountLabNodes countLabNodes(array $options = [])
 * @method CountGateways countGateways(array $options = [])
 * @method DeleteLocalJoinPermission deleteLocalJoinPermission(array $options = [])
 * @method CreateLocalJoinPermission createLocalJoinPermission(array $options = [])
 * @method BindLabNodeToLabGateway bindLabNodeToLabGateway(array $options = [])
 * @method GetOwnedJoinPermission getOwnedJoinPermission(array $options = [])
 * @method GetRentedJoinPermission getRentedJoinPermission(array $options = [])
 * @method ListOwnedJoinPermissions listOwnedJoinPermissions(array $options = [])
 * @method ListRentedJoinPermissions listRentedJoinPermissions(array $options = [])
 * @method CountLabGateways countLabGateways(array $options = [])
 * @method CountOwnedJoinPermissions countOwnedJoinPermissions(array $options = [])
 * @method CountGatewayTupleOrders countGatewayTupleOrders(array $options = [])
 * @method CountRentedJoinPermissions countRentedJoinPermissions(array $options = [])
 * @method ApplyRoamingJoinPermission applyRoamingJoinPermission(array $options = [])
 * @method ReturnJoinPermission returnJoinPermission(array $options = [])
 * @method SubmitJoinPermissionAuthOrder submitJoinPermissionAuthOrder(array $options = [])
 * @method AcceptJoinPermissionAuthOrder acceptJoinPermissionAuthOrder(array $options = [])
 * @method CancelJoinPermissionAuthOrder cancelJoinPermissionAuthOrder(array $options = [])
 * @method RejectJoinPermissionAuthOrder rejectJoinPermissionAuthOrder(array $options = [])
 * @method GetJoinPermissionAuthOrder getJoinPermissionAuthOrder(array $options = [])
 * @method GetKpmPublicKey getKpmPublicKey(array $options = [])
 * @method CreateNodeGroup createNodeGroup(array $options = [])
 * @method DeleteNodeGroup deleteNodeGroup(array $options = [])
 * @method UpdateNodeGroup updateNodeGroup(array $options = [])
 * @method GetNodeGroup getNodeGroup(array $options = [])
 * @method ListNodeGroups listNodeGroups(array $options = [])
 * @method CountNodeGroups countNodeGroups(array $options = [])
 * @method BindJoinPermissionToNodeGroup bindJoinPermissionToNodeGroup(array $options = [])
 * @method UpdateDataDispatchConfig updateDataDispatchConfig(array $options = [])
 * @method UpdateDataDispatchEnablingState updateDataDispatchEnablingState(array $options = [])
 * @method AddNodeToGroup addNodeToGroup(array $options = [])
 * @method RemoveNodeFromGroup removeNodeFromGroup(array $options = [])
 * @method GetNode getNode(array $options = [])
 * @method ListNodeGroupTransferPackets listNodeGroupTransferPackets(array $options = [])
 * @method GetNodeGroupTransferPacketsDownloadUrl getNodeGroupTransferPacketsDownloadUrl(array $options = [])
 * @method UnbindJoinPermissionFromNodeGroup unbindJoinPermissionFromNodeGroup(array $options = [])
 * @method ListGateways listGateways(array $options = [])
 * @method ListFreqBandPlanGroups listFreqBandPlanGroups(array $options = [])
 * @method ListActivatedFeatures listActivatedFeatures(array $options = [])
 * @method CheckCloudProductOpenStatus checkCloudProductOpenStatus(array $options = [])
 */
class LinkWANApiResolver
{
    use ApiResolverTrait;
}
