<?php

namespace AlibabaCloud\Vod;

use AlibabaCloud\ApiResolverTrait;

/**
 * Find the specified Api of the Vod based on the method name as the Api name.
 *
 * @package   AlibabaCloud\Vod
 *
 * @method static V20170321\AddCategory addCategory(array $options = [])
 * @method static V20170321\AddEditingProject addEditingProject(array $options = [])
 * @method static V20170321\AddFaceRegistration addFaceRegistration(array $options = [])
 * @method static V20170321\AddMediaSequences addMediaSequences(array $options = [])
 * @method static V20170321\AddStorage addStorage(array $options = [])
 * @method static V20170321\AddVodDomain addVodDomain(array $options = [])
 * @method static V20170321\AddVodTemplate addVodTemplate(array $options = [])
 * @method static V20170321\AddWatermark addWatermark(array $options = [])
 * @method static V20170321\AddWorkFlow addWorkFlow(array $options = [])
 * @method static V20170321\CreateAudit createAudit(array $options = [])
 * @method static V20170321\CreateUploadAttachedMedia createUploadAttachedMedia(array $options = [])
 * @method static V20170321\CreateUploadImage createUploadImage(array $options = [])
 * @method static V20170321\CreateUploadVideo createUploadVideo(array $options = [])
 * @method static V20170321\DeleteCategory deleteCategory(array $options = [])
 * @method static V20170321\DeleteEditingProject deleteEditingProject(array $options = [])
 * @method static V20170321\DeleteImage deleteImage(array $options = [])
 * @method static V20170321\DeleteMezzanines deleteMezzanines(array $options = [])
 * @method static V20170321\DeleteStream deleteStream(array $options = [])
 * @method static V20170321\DeleteVideo deleteVideo(array $options = [])
 * @method static V20170321\DeleteVodDomain deleteVodDomain(array $options = [])
 * @method static V20170321\DeleteVodTemplate deleteVodTemplate(array $options = [])
 * @method static V20170321\DeleteWatermark deleteWatermark(array $options = [])
 * @method static V20170321\DeleteWorkFlow deleteWorkFlow(array $options = [])
 * @method static V20170321\DescribeCdnDomainLogs describeCdnDomainLogs(array $options = [])
 * @method static V20170321\DescribeDomainBpsData describeDomainBpsData(array $options = [])
 * @method static V20170321\DescribeDomainFlowData describeDomainFlowData(array $options = [])
 * @method static V20170321\DescribePlayTopVideos describePlayTopVideos(array $options = [])
 * @method static V20170321\DescribePlayUserAvg describePlayUserAvg(array $options = [])
 * @method static V20170321\DescribePlayUserTotal describePlayUserTotal(array $options = [])
 * @method static V20170321\DescribePlayVideoStatis describePlayVideoStatis(array $options = [])
 * @method static V20170321\DescribeRefreshQuota describeRefreshQuota(array $options = [])
 * @method static V20170321\DescribeRefreshTasks describeRefreshTasks(array $options = [])
 * @method static V20170321\DescribeUserVodStatus describeUserVodStatus(array $options = [])
 * @method static V20170321\DescribeVodCertificateList describeVodCertificateList(array $options = [])
 * @method static V20170321\DescribeVodDomainCertificateInfo describeVodDomainCertificateInfo(array $options = [])
 * @method static V20170321\DescribeVodDomainConfigs describeVodDomainConfigs(array $options = [])
 * @method static V20170321\DescribeVodDomainDetail describeVodDomainDetail(array $options = [])
 * @method static V20170321\DescribeVodService describeVodService(array $options = [])
 * @method static V20170321\DescribeVodUserDomains describeVodUserDomains(array $options = [])
 * @method static V20170321\DescribeVodUserResourcePackage describeVodUserResourcePackage(array $options = [])
 * @method static V20170321\EditLiveRecordVideo editLiveRecordVideo(array $options = [])
 * @method static V20170321\GetAuditHistory getAuditHistory(array $options = [])
 * @method static V20170321\GetAuditResult getAuditResult(array $options = [])
 * @method static V20170321\GetCDNStatisSum getCDNStatisSum(array $options = [])
 * @method static V20170321\GetCategories getCategories(array $options = [])
 * @method static V20170321\GetEditingProject getEditingProject(array $options = [])
 * @method static V20170321\GetEditingProjectMaterials getEditingProjectMaterials(array $options = [])
 * @method static V20170321\GetFileInfo getFileInfo(array $options = [])
 * @method static V20170321\GetImageInfo getImageInfo(array $options = [])
 * @method static V20170321\GetMediaDNAResult getMediaDNAResult(array $options = [])
 * @method static V20170321\GetMessageCallback getMessageCallback(array $options = [])
 * @method static V20170321\GetMezzanineInfo getMezzanineInfo(array $options = [])
 * @method static V20170321\GetOSSStatis getOSSStatis(array $options = [])
 * @method static V20170321\GetPlayInfo getPlayInfo(array $options = [])
 * @method static V20170321\GetVideoConfig getVideoConfig(array $options = [])
 * @method static V20170321\GetVideoInfo getVideoInfo(array $options = [])
 * @method static V20170321\GetVideoInfos getVideoInfos(array $options = [])
 * @method static V20170321\GetVideoList getVideoList(array $options = [])
 * @method static V20170321\GetVideoPlayAuth getVideoPlayAuth(array $options = [])
 * @method static V20170321\GetVideoPlayInfo getVideoPlayInfo(array $options = [])
 * @method static V20170321\GetVodTemplate getVodTemplate(array $options = [])
 * @method static V20170321\GetWatermark getWatermark(array $options = [])
 * @method static V20170321\GetWorkFlow getWorkFlow(array $options = [])
 * @method static V20170321\ListAIASRJob listAIASRJob(array $options = [])
 * @method static V20170321\ListAIJob listAIJob(array $options = [])
 * @method static V20170321\ListAIVideoCategoryJob listAIVideoCategoryJob(array $options = [])
 * @method static V20170321\ListAIVideoCensorJob listAIVideoCensorJob(array $options = [])
 * @method static V20170321\ListAIVideoCoverJob listAIVideoCoverJob(array $options = [])
 * @method static V20170321\ListAIVideoPornRecogJob listAIVideoPornRecogJob(array $options = [])
 * @method static V20170321\ListAIVideoSummaryJob listAIVideoSummaryJob(array $options = [])
 * @method static V20170321\ListAIVideoTerrorismRecogJob listAIVideoTerrorismRecogJob(array $options = [])
 * @method static V20170321\ListAuditSecurityIp listAuditSecurityIp(array $options = [])
 * @method static V20170321\ListLiveRecordVideo listLiveRecordVideo(array $options = [])
 * @method static V20170321\ListSnapshots listSnapshots(array $options = [])
 * @method static V20170321\ListVodTemplate listVodTemplate(array $options = [])
 * @method static V20170321\ListWatermark listWatermark(array $options = [])
 * @method static V20170321\ListWorkFlow listWorkFlow(array $options = [])
 * @method static V20170321\OpenVodService openVodService(array $options = [])
 * @method static V20170321\ProduceEditingProjectVideo produceEditingProjectVideo(array $options = [])
 * @method static V20170321\PushObjectCache pushObjectCache(array $options = [])
 * @method static V20170321\RefreshObjectCaches refreshObjectCaches(array $options = [])
 * @method static V20170321\RefreshUploadVideo refreshUploadVideo(array $options = [])
 * @method static V20170321\RegisterMedia registerMedia(array $options = [])
 * @method static V20170321\SearchEditingProject searchEditingProject(array $options = [])
 * @method static V20170321\SearchMedia searchMedia(array $options = [])
 * @method static V20170321\SetAuditSecurityIp setAuditSecurityIp(array $options = [])
 * @method static V20170321\SetDefaultVodTemplate setDefaultVodTemplate(array $options = [])
 * @method static V20170321\SetDefaultWatermark setDefaultWatermark(array $options = [])
 * @method static V20170321\SetEditingProjectMaterials setEditingProjectMaterials(array $options = [])
 * @method static V20170321\SetMessageCallback setMessageCallback(array $options = [])
 * @method static V20170321\SetVodDomainCertificate setVodDomainCertificate(array $options = [])
 * @method static V20170321\StartVodDomain startVodDomain(array $options = [])
 * @method static V20170321\StopVodDomain stopVodDomain(array $options = [])
 * @method static V20170321\SubmitAIASRJob submitAIASRJob(array $options = [])
 * @method static V20170321\SubmitAIJob submitAIJob(array $options = [])
 * @method static V20170321\SubmitAIVideoCategoryJob submitAIVideoCategoryJob(array $options = [])
 * @method static V20170321\SubmitAIVideoCensorJob submitAIVideoCensorJob(array $options = [])
 * @method static V20170321\SubmitAIVideoCoverJob submitAIVideoCoverJob(array $options = [])
 * @method static V20170321\SubmitAIVideoPornRecogJob submitAIVideoPornRecogJob(array $options = [])
 * @method static V20170321\SubmitAIVideoSummaryJob submitAIVideoSummaryJob(array $options = [])
 * @method static V20170321\SubmitAIVideoTerrorismRecogJob submitAIVideoTerrorismRecogJob(array $options = [])
 * @method static V20170321\SubmitPreprocessJobs submitPreprocessJobs(array $options = [])
 * @method static V20170321\SubmitSnapshotJob submitSnapshotJob(array $options = [])
 * @method static V20170321\SubmitTranscodeJobs submitTranscodeJobs(array $options = [])
 * @method static V20170321\UpdateCategory updateCategory(array $options = [])
 * @method static V20170321\UpdateEditingProject updateEditingProject(array $options = [])
 * @method static V20170321\UpdateImageInfos updateImageInfos(array $options = [])
 * @method static V20170321\UpdateVideoInfo updateVideoInfo(array $options = [])
 * @method static V20170321\UpdateVideoInfos updateVideoInfos(array $options = [])
 * @method static V20170321\UpdateVodTemplate updateVodTemplate(array $options = [])
 * @method static V20170321\UpdateWatermark updateWatermark(array $options = [])
 * @method static V20170321\UpdateWorkFlow updateWorkFlow(array $options = [])
 * @method static V20170321\UploadMediaByURL uploadMediaByURL(array $options = [])
 */
class VodV20170321
{
    use ApiResolverTrait;

    /**
     * @var string
     */
    protected $namespace = 'AlibabaCloud\\Vod\\V20170321';
}
