<?php

namespace AlibabaCloud\Imm\V20170906;

use AlibabaCloud\ApiResolverTrait;

/**
 * Resolve Api based on the method name.
 *
 * @method DetectImageLogos detectImageLogos(array $options = [])
 * @method FindSimilarFaces findSimilarFaces(array $options = [])
 * @method FindImagesByTagNames findImagesByTagNames(array $options = [])
 * @method FindImages findImages(array $options = [])
 * @method IndexVideo indexVideo(array $options = [])
 * @method GetVideo getVideo(array $options = [])
 * @method ListVideos listVideos(array $options = [])
 * @method DeleteVideo deleteVideo(array $options = [])
 * @method ListVideoAudios listVideoAudios(array $options = [])
 * @method ListVideoFrames listVideoFrames(array $options = [])
 * @method IndexImage indexImage(array $options = [])
 * @method CompareImageFaces compareImageFaces(array $options = [])
 * @method DetectImageCelebrity detectImageCelebrity(array $options = [])
 * @method DetectImageTexts detectImageTexts(array $options = [])
 * @method UpdateImage updateImage(array $options = [])
 * @method ListImages listImages(array $options = [])
 * @method DeleteImage deleteImage(array $options = [])
 * @method DetectImageFaces detectImageFaces(array $options = [])
 * @method DetectImageTags detectImageTags(array $options = [])
 * @method DeleteSet deleteSet(array $options = [])
 * @method ListSetTags listSetTags(array $options = [])
 * @method GetImage getImage(array $options = [])
 * @method ListSets listSets(array $options = [])
 * @method UpdateSet updateSet(array $options = [])
 * @method CreateSet createSet(array $options = [])
 * @method CreateVideoAnalyseTask createVideoAnalyseTask(array $options = [])
 * @method GetVideoTask getVideoTask(array $options = [])
 * @method DeleteVideoTask deleteVideoTask(array $options = [])
 * @method ListVideoTasks listVideoTasks(array $options = [])
 * @method GetSet getSet(array $options = [])
 * @method GetImageJob getImageJob(array $options = [])
 * @method DeleteImageJob deleteImageJob(array $options = [])
 * @method ListImageJobs listImageJobs(array $options = [])
 * @method CreateGroupFacesJob createGroupFacesJob(array $options = [])
 * @method CreateDocIndexTask createDocIndexTask(array $options = [])
 * @method GetDocIndexTask getDocIndexTask(array $options = [])
 * @method UpdateDocIndexMeta updateDocIndexMeta(array $options = [])
 * @method GetDocIndex getDocIndex(array $options = [])
 * @method DeleteDocIndex deleteDocIndex(array $options = [])
 * @method SearchDocIndex searchDocIndex(array $options = [])
 * @method UpdateProject updateProject(array $options = [])
 * @method DetectLogo detectLogo(array $options = [])
 * @method DetectClothes detectClothes(array $options = [])
 * @method DetectQRCodes detectQRCodes(array $options = [])
 * @method CompareFace compareFace(array $options = [])
 * @method RegistFace registFace(array $options = [])
 * @method SearchFace searchFace(array $options = [])
 * @method GetFaceSearchImage getFaceSearchImage(array $options = [])
 * @method GetFaceSearchUser getFaceSearchUser(array $options = [])
 * @method GetFaceSearchGroup getFaceSearchGroup(array $options = [])
 * @method DeleteFaceSearchGroup deleteFaceSearchGroup(array $options = [])
 * @method DeleteFaceSearchUser deleteFaceSearchUser(array $options = [])
 * @method ListFaceSearchGroups listFaceSearchGroups(array $options = [])
 * @method ListFaceSearchGroupImages listFaceSearchGroupImages(array $options = [])
 * @method DeleteFaceSearchImageById deleteFaceSearchImageById(array $options = [])
 * @method ListFaceSearchGroupUsers listFaceSearchGroupUsers(array $options = [])
 * @method DeleteTagByUrl deleteTagByUrl(array $options = [])
 * @method DeleteTagByName deleteTagByName(array $options = [])
 * @method ListTagNames listTagNames(array $options = [])
 * @method ListOfficeConversionTask listOfficeConversionTask(array $options = [])
 * @method ListTagPhotos listTagPhotos(array $options = [])
 * @method GetOfficeConversionTask getOfficeConversionTask(array $options = [])
 * @method DeleteOfficeConversionTask deleteOfficeConversionTask(array $options = [])
 * @method CreateOfficeConversionTask createOfficeConversionTask(array $options = [])
 * @method DescribeRegions describeRegions(array $options = [])
 * @method ConvertOfficeFormat convertOfficeFormat(array $options = [])
 * @method PhotoProcess photoProcess(array $options = [])
 * @method GetPhotoProcessTask getPhotoProcessTask(array $options = [])
 * @method DeletePhotoProcessTask deletePhotoProcessTask(array $options = [])
 * @method ListPhotoProcessTasks listPhotoProcessTasks(array $options = [])
 * @method DeleteProject deleteProject(array $options = [])
 * @method GetTagSet getTagSet(array $options = [])
 * @method CreateFaceSet createFaceSet(array $options = [])
 * @method IndexTag indexTag(array $options = [])
 * @method DeleteTagSet deleteTagSet(array $options = [])
 * @method ListTagSets listTagSets(array $options = [])
 * @method CreateTagSet createTagSet(array $options = [])
 * @method DeleteFaceJob deleteFaceJob(array $options = [])
 * @method CreateTagJob createTagJob(array $options = [])
 * @method DetectTag detectTag(array $options = [])
 * @method DeleteTagJob deleteTagJob(array $options = [])
 * @method GetTagJob getTagJob(array $options = [])
 * @method ListTagJobs listTagJobs(array $options = [])
 * @method PutProject putProject(array $options = [])
 * @method GetProject getProject(array $options = [])
 * @method ListProjects listProjects(array $options = [])
 * @method DeletePornBatchDetectJob deletePornBatchDetectJob(array $options = [])
 * @method CreatePornBatchDetectJob createPornBatchDetectJob(array $options = [])
 * @method GetPornBatchDetectJob getPornBatchDetectJob(array $options = [])
 * @method ListPornBatchDetectJobs listPornBatchDetectJobs(array $options = [])
 */
class ImmApiResolver
{
    use ApiResolverTrait;
}
