<?php

namespace AlibabaCloud\Rds;

use AlibabaCloud\ApiResolverTrait;

/**
 * Find the specified Api of the Rds based on the method name as the Api name.
 *
 * @package   AlibabaCloud\Rds
 *
 * @method static V20140815\AddDBInstanceNetworkType addDBInstanceNetworkType(array $options = [])
 * @method static V20140815\AddTagsToResource addTagsToResource(array $options = [])
 * @method static V20140815\AllocateInstancePrivateConnection allocateInstancePrivateConnection(array $options = [])
 * @method static V20140815\AllocateInstancePublicConnection allocateInstancePublicConnection(array $options = [])
 * @method static V20140815\AllocateReadWriteSplittingConnection allocateReadWriteSplittingConnection(array $options = [])
 * @method static V20140815\CalculateDBInstanceWeight calculateDBInstanceWeight(array $options = [])
 * @method static V20140815\CancelImport cancelImport(array $options = [])
 * @method static V20140815\CheckAccountNameAvailable checkAccountNameAvailable(array $options = [])
 * @method static V20140815\CheckInstanceExist checkInstanceExist(array $options = [])
 * @method static V20140815\CheckRecoveryConditions checkRecoveryConditions(array $options = [])
 * @method static V20140815\CheckResource checkResource(array $options = [])
 * @method static V20140815\CloneDBInstance cloneDBInstance(array $options = [])
 * @method static V20140815\CopyDatabase copyDatabase(array $options = [])
 * @method static V20140815\CopyDatabaseBetweenInstances copyDatabaseBetweenInstances(array $options = [])
 * @method static V20140815\CreateAccount createAccount(array $options = [])
 * @method static V20140815\CreateBackup createBackup(array $options = [])
 * @method static V20140815\CreateDBInstance createDBInstance(array $options = [])
 * @method static V20140815\CreateDBInstanceReplica createDBInstanceReplica(array $options = [])
 * @method static V20140815\CreateDatabase createDatabase(array $options = [])
 * @method static V20140815\CreateMigrateTask createMigrateTask(array $options = [])
 * @method static V20140815\CreateMigrateTaskForSQLServer createMigrateTaskForSQLServer(array $options = [])
 * @method static V20140815\CreateOnlineDatabaseTask createOnlineDatabaseTask(array $options = [])
 * @method static V20140815\CreateReadOnlyDBInstance createReadOnlyDBInstance(array $options = [])
 * @method static V20140815\CreateTempDBInstance createTempDBInstance(array $options = [])
 * @method static V20140815\DeleteAccount deleteAccount(array $options = [])
 * @method static V20140815\DeleteBackup deleteBackup(array $options = [])
 * @method static V20140815\DeleteDBInstance deleteDBInstance(array $options = [])
 * @method static V20140815\DeleteDatabase deleteDatabase(array $options = [])
 * @method static V20140815\DescibeImportsFromDatabase descibeImportsFromDatabase(array $options = [])
 * @method static V20140815\DescribeAccounts describeAccounts(array $options = [])
 * @method static V20140815\DescribeActiveOperationTask describeActiveOperationTask(array $options = [])
 * @method static V20140815\DescribeAvailableInstanceClass describeAvailableInstanceClass(array $options = [])
 * @method static V20140815\DescribeAvailableResource describeAvailableResource(array $options = [])
 * @method static V20140815\DescribeBackupDatabase describeBackupDatabase(array $options = [])
 * @method static V20140815\DescribeBackupPolicy describeBackupPolicy(array $options = [])
 * @method static V20140815\DescribeBackupTasks describeBackupTasks(array $options = [])
 * @method static V20140815\DescribeBackups describeBackups(array $options = [])
 * @method static V20140815\DescribeBinlogFiles describeBinlogFiles(array $options = [])
 * @method static V20140815\DescribeCharacterSetName describeCharacterSetName(array $options = [])
 * @method static V20140815\DescribeCloudDbExpertService describeCloudDbExpertService(array $options = [])
 * @method static V20140815\DescribeCollationTimeZones describeCollationTimeZones(array $options = [])
 * @method static V20140815\DescribeDBInstanceAttribute describeDBInstanceAttribute(array $options = [])
 * @method static V20140815\DescribeDBInstanceByTags describeDBInstanceByTags(array $options = [])
 * @method static V20140815\DescribeDBInstanceHAConfig describeDBInstanceHAConfig(array $options = [])
 * @method static V20140815\DescribeDBInstanceIPArrayList describeDBInstanceIPArrayList(array $options = [])
 * @method static V20140815\DescribeDBInstanceMonitor describeDBInstanceMonitor(array $options = [])
 * @method static V20140815\DescribeDBInstanceNetInfo describeDBInstanceNetInfo(array $options = [])
 * @method static V20140815\DescribeDBInstancePerformance describeDBInstancePerformance(array $options = [])
 * @method static V20140815\DescribeDBInstanceProxyConfiguration describeDBInstanceProxyConfiguration(array $options = [])
 * @method static V20140815\DescribeDBInstanceSSL describeDBInstanceSSL(array $options = [])
 * @method static V20140815\DescribeDBInstanceTDE describeDBInstanceTDE(array $options = [])
 * @method static V20140815\DescribeDBInstances describeDBInstances(array $options = [])
 * @method static V20140815\DescribeDBInstancesAsCsv describeDBInstancesAsCsv(array $options = [])
 * @method static V20140815\DescribeDBInstancesByExpireTime describeDBInstancesByExpireTime(array $options = [])
 * @method static V20140815\DescribeDBInstancesByPerformance describeDBInstancesByPerformance(array $options = [])
 * @method static V20140815\DescribeDatabases describeDatabases(array $options = [])
 * @method static V20140815\DescribeDiagnosticReportList describeDiagnosticReportList(array $options = [])
 * @method static V20140815\DescribeErrorLogs describeErrorLogs(array $options = [])
 * @method static V20140815\DescribeInstanceAutoRenewalAttribute describeInstanceAutoRenewalAttribute(array $options = [])
 * @method static V20140815\DescribeLogBackupFiles describeLogBackupFiles(array $options = [])
 * @method static V20140815\DescribeMetaList describeMetaList(array $options = [])
 * @method static V20140815\DescribeMigrateTasks describeMigrateTasks(array $options = [])
 * @method static V20140815\DescribeMigrateTasksForSQLServer describeMigrateTasksForSQLServer(array $options = [])
 * @method static V20140815\DescribeModifyParameterLog describeModifyParameterLog(array $options = [])
 * @method static V20140815\DescribeOssDownloads describeOssDownloads(array $options = [])
 * @method static V20140815\DescribeOssDownloadsForSQLServer describeOssDownloadsForSQLServer(array $options = [])
 * @method static V20140815\DescribeParameterTemplates describeParameterTemplates(array $options = [])
 * @method static V20140815\DescribeParameters describeParameters(array $options = [])
 * @method static V20140815\DescribePrice describePrice(array $options = [])
 * @method static V20140815\DescribeProxyFunctionSupport describeProxyFunctionSupport(array $options = [])
 * @method static V20140815\DescribeRdsVSwitchs describeRdsVSwitchs(array $options = [])
 * @method static V20140815\DescribeRdsVpcs describeRdsVpcs(array $options = [])
 * @method static V20140815\DescribeRegions describeRegions(array $options = [])
 * @method static V20140815\DescribeRenewalPrice describeRenewalPrice(array $options = [])
 * @method static V20140815\DescribeResourceUsage describeResourceUsage(array $options = [])
 * @method static V20140815\DescribeSQLLogFiles describeSQLLogFiles(array $options = [])
 * @method static V20140815\DescribeSQLLogRecords describeSQLLogRecords(array $options = [])
 * @method static V20140815\DescribeSQLLogReportList describeSQLLogReportList(array $options = [])
 * @method static V20140815\DescribeSQLLogReports describeSQLLogReports(array $options = [])
 * @method static V20140815\DescribeSQLReports describeSQLReports(array $options = [])
 * @method static V20140815\DescribeSecurityGroupConfiguration describeSecurityGroupConfiguration(array $options = [])
 * @method static V20140815\DescribeSlowLogRecords describeSlowLogRecords(array $options = [])
 * @method static V20140815\DescribeSlowLogs describeSlowLogs(array $options = [])
 * @method static V20140815\DescribeTags describeTags(array $options = [])
 * @method static V20140815\DescribeTargetAVZ describeTargetAVZ(array $options = [])
 * @method static V20140815\DescribeTaskInfo describeTaskInfo(array $options = [])
 * @method static V20140815\DescribeTasks describeTasks(array $options = [])
 * @method static V20140815\DescribeTemplatesList describeTemplatesList(array $options = [])
 * @method static V20140815\GrantAccountPrivilege grantAccountPrivilege(array $options = [])
 * @method static V20140815\GrantOperatorPermission grantOperatorPermission(array $options = [])
 * @method static V20140815\ImportDataForSQLServer importDataForSQLServer(array $options = [])
 * @method static V20140815\ImportDatabaseBetweenInstances importDatabaseBetweenInstances(array $options = [])
 * @method static V20140815\ListTagResources listTagResources(array $options = [])
 * @method static V20140815\MigrateSecurityIPMode migrateSecurityIPMode(array $options = [])
 * @method static V20140815\MigrateToOtherZone migrateToOtherZone(array $options = [])
 * @method static V20140815\ModifyAccountDescription modifyAccountDescription(array $options = [])
 * @method static V20140815\ModifyActiveOperationPendingTask modifyActiveOperationPendingTask(array $options = [])
 * @method static V20140815\ModifyBackupPolicy modifyBackupPolicy(array $options = [])
 * @method static V20140815\ModifyCollationTimeZone modifyCollationTimeZone(array $options = [])
 * @method static V20140815\ModifyDBDescription modifyDBDescription(array $options = [])
 * @method static V20140815\ModifyDBInstanceConnectionMode modifyDBInstanceConnectionMode(array $options = [])
 * @method static V20140815\ModifyDBInstanceConnectionString modifyDBInstanceConnectionString(array $options = [])
 * @method static V20140815\ModifyDBInstanceDescription modifyDBInstanceDescription(array $options = [])
 * @method static V20140815\ModifyDBInstanceHAConfig modifyDBInstanceHAConfig(array $options = [])
 * @method static V20140815\ModifyDBInstanceMaintainTime modifyDBInstanceMaintainTime(array $options = [])
 * @method static V20140815\ModifyDBInstanceMonitor modifyDBInstanceMonitor(array $options = [])
 * @method static V20140815\ModifyDBInstanceNetworkExpireTime modifyDBInstanceNetworkExpireTime(array $options = [])
 * @method static V20140815\ModifyDBInstanceNetworkType modifyDBInstanceNetworkType(array $options = [])
 * @method static V20140815\ModifyDBInstanceProxyConfiguration modifyDBInstanceProxyConfiguration(array $options = [])
 * @method static V20140815\ModifyDBInstanceSSL modifyDBInstanceSSL(array $options = [])
 * @method static V20140815\ModifyDBInstanceSpec modifyDBInstanceSpec(array $options = [])
 * @method static V20140815\ModifyDBInstanceTDE modifyDBInstanceTDE(array $options = [])
 * @method static V20140815\ModifyInstanceAutoRenewalAttribute modifyInstanceAutoRenewalAttribute(array $options = [])
 * @method static V20140815\ModifyMySQLDBInstanceDelay modifyMySQLDBInstanceDelay(array $options = [])
 * @method static V20140815\ModifyParameter modifyParameter(array $options = [])
 * @method static V20140815\ModifyReadWriteSplittingConnection modifyReadWriteSplittingConnection(array $options = [])
 * @method static V20140815\ModifyReadonlyInstanceDelayReplicationTime modifyReadonlyInstanceDelayReplicationTime(array $options = [])
 * @method static V20140815\ModifyReplicaDescription modifyReplicaDescription(array $options = [])
 * @method static V20140815\ModifyResourceGroup modifyResourceGroup(array $options = [])
 * @method static V20140815\ModifySQLCollectorPolicy modifySQLCollectorPolicy(array $options = [])
 * @method static V20140815\ModifySecurityGroupConfiguration modifySecurityGroupConfiguration(array $options = [])
 * @method static V20140815\ModifySecurityIps modifySecurityIps(array $options = [])
 * @method static V20140815\PurgeDBInstanceLog purgeDBInstanceLog(array $options = [])
 * @method static V20140815\RecoveryDBInstance recoveryDBInstance(array $options = [])
 * @method static V20140815\ReleaseInstancePublicConnection releaseInstancePublicConnection(array $options = [])
 * @method static V20140815\ReleaseReadWriteSplittingConnection releaseReadWriteSplittingConnection(array $options = [])
 * @method static V20140815\RemoveTagsFromResource removeTagsFromResource(array $options = [])
 * @method static V20140815\RenewInstance renewInstance(array $options = [])
 * @method static V20140815\RequestServiceOfCloudDBExpert requestServiceOfCloudDBExpert(array $options = [])
 * @method static V20140815\ResetAccount resetAccount(array $options = [])
 * @method static V20140815\ResetAccountForPG resetAccountForPG(array $options = [])
 * @method static V20140815\ResetAccountPassword resetAccountPassword(array $options = [])
 * @method static V20140815\RestartDBInstance restartDBInstance(array $options = [])
 * @method static V20140815\RestoreDBInstance restoreDBInstance(array $options = [])
 * @method static V20140815\RevokeAccountPrivilege revokeAccountPrivilege(array $options = [])
 * @method static V20140815\RevokeOperatorPermission revokeOperatorPermission(array $options = [])
 * @method static V20140815\SwitchDBInstanceHA switchDBInstanceHA(array $options = [])
 * @method static V20140815\SwitchDBInstanceNetType switchDBInstanceNetType(array $options = [])
 * @method static V20140815\SwitchDBInstanceVpc switchDBInstanceVpc(array $options = [])
 * @method static V20140815\TagResources tagResources(array $options = [])
 * @method static V20140815\UntagResources untagResources(array $options = [])
 * @method static V20140815\UpgradeDBInstanceEngineVersion upgradeDBInstanceEngineVersion(array $options = [])
 * @method static V20140815\UpgradeDBInstanceKernelVersion upgradeDBInstanceKernelVersion(array $options = [])
 */
class RdsV20140815
{
    use ApiResolverTrait;

    /**
     * @var string
     */
    protected $namespace = 'AlibabaCloud\\Rds\\V20140815';
}
