<?php

namespace AlibabaCloud\Live;

use AlibabaCloud\ApiResolverTrait;

/**
 * Find the specified Api of the Live based on the method name as the Api name.
 *
 * @package   AlibabaCloud\Live
 *
 * @method static V20161101\AddCasterComponent addCasterComponent(array $options = [])
 * @method static V20161101\AddCasterEpisode addCasterEpisode(array $options = [])
 * @method static V20161101\AddCasterEpisodeGroup addCasterEpisodeGroup(array $options = [])
 * @method static V20161101\AddCasterEpisodeGroupContent addCasterEpisodeGroupContent(array $options = [])
 * @method static V20161101\AddCasterLayout addCasterLayout(array $options = [])
 * @method static V20161101\AddCasterProgram addCasterProgram(array $options = [])
 * @method static V20161101\AddCasterVideoResource addCasterVideoResource(array $options = [])
 * @method static V20161101\AddCustomLiveStreamTranscode addCustomLiveStreamTranscode(array $options = [])
 * @method static V20161101\AddLiveAppRecordConfig addLiveAppRecordConfig(array $options = [])
 * @method static V20161101\AddLiveAppSnapshotConfig addLiveAppSnapshotConfig(array $options = [])
 * @method static V20161101\AddLiveDetectNotifyConfig addLiveDetectNotifyConfig(array $options = [])
 * @method static V20161101\AddLiveDomain addLiveDomain(array $options = [])
 * @method static V20161101\AddLiveDomainMapping addLiveDomainMapping(array $options = [])
 * @method static V20161101\AddLivePullStreamInfoConfig addLivePullStreamInfoConfig(array $options = [])
 * @method static V20161101\AddLiveRecordNotifyConfig addLiveRecordNotifyConfig(array $options = [])
 * @method static V20161101\AddLiveRecordVodConfig addLiveRecordVodConfig(array $options = [])
 * @method static V20161101\AddLiveSnapshotDetectPornConfig addLiveSnapshotDetectPornConfig(array $options = [])
 * @method static V20161101\AddLiveStreamTranscode addLiveStreamTranscode(array $options = [])
 * @method static V20161101\AddTrancodeSEI addTrancodeSEI(array $options = [])
 * @method static V20161101\AllowPushStream allowPushStream(array $options = [])
 * @method static V20161101\ApplyBoardToken applyBoardToken(array $options = [])
 * @method static V20161101\ApplyRecordToken applyRecordToken(array $options = [])
 * @method static V20161101\BatchDeleteLiveDomainConfigs batchDeleteLiveDomainConfigs(array $options = [])
 * @method static V20161101\BatchSetLiveDomainConfigs batchSetLiveDomainConfigs(array $options = [])
 * @method static V20161101\CompleteBoard completeBoard(array $options = [])
 * @method static V20161101\CompleteBoardRecord completeBoardRecord(array $options = [])
 * @method static V20161101\CopyCaster copyCaster(array $options = [])
 * @method static V20161101\CopyCasterSceneConfig copyCasterSceneConfig(array $options = [])
 * @method static V20161101\CreateBoard createBoard(array $options = [])
 * @method static V20161101\CreateCaster createCaster(array $options = [])
 * @method static V20161101\CreateLiveStreamRecordIndexFiles createLiveStreamRecordIndexFiles(array $options = [])
 * @method static V20161101\CreateRoom createRoom(array $options = [])
 * @method static V20161101\DeleteBoard deleteBoard(array $options = [])
 * @method static V20161101\DeleteCaster deleteCaster(array $options = [])
 * @method static V20161101\DeleteCasterComponent deleteCasterComponent(array $options = [])
 * @method static V20161101\DeleteCasterEpisode deleteCasterEpisode(array $options = [])
 * @method static V20161101\DeleteCasterEpisodeGroup deleteCasterEpisodeGroup(array $options = [])
 * @method static V20161101\DeleteCasterLayout deleteCasterLayout(array $options = [])
 * @method static V20161101\DeleteCasterProgram deleteCasterProgram(array $options = [])
 * @method static V20161101\DeleteCasterSceneConfig deleteCasterSceneConfig(array $options = [])
 * @method static V20161101\DeleteCasterVideoResource deleteCasterVideoResource(array $options = [])
 * @method static V20161101\DeleteLiveAppRecordConfig deleteLiveAppRecordConfig(array $options = [])
 * @method static V20161101\DeleteLiveAppSnapshotConfig deleteLiveAppSnapshotConfig(array $options = [])
 * @method static V20161101\DeleteLiveDetectNotifyConfig deleteLiveDetectNotifyConfig(array $options = [])
 * @method static V20161101\DeleteLiveDomain deleteLiveDomain(array $options = [])
 * @method static V20161101\DeleteLiveDomainMapping deleteLiveDomainMapping(array $options = [])
 * @method static V20161101\DeleteLiveLazyPullStreamInfoConfig deleteLiveLazyPullStreamInfoConfig(array $options = [])
 * @method static V20161101\DeleteLivePullStreamInfoConfig deleteLivePullStreamInfoConfig(array $options = [])
 * @method static V20161101\DeleteLiveRecordNotifyConfig deleteLiveRecordNotifyConfig(array $options = [])
 * @method static V20161101\DeleteLiveRecordVodConfig deleteLiveRecordVodConfig(array $options = [])
 * @method static V20161101\DeleteLiveSnapshotDetectPornConfig deleteLiveSnapshotDetectPornConfig(array $options = [])
 * @method static V20161101\DeleteLiveSpecificConfig deleteLiveSpecificConfig(array $options = [])
 * @method static V20161101\DeleteLiveStreamTranscode deleteLiveStreamTranscode(array $options = [])
 * @method static V20161101\DeleteLiveStreamsNotifyUrlConfig deleteLiveStreamsNotifyUrlConfig(array $options = [])
 * @method static V20161101\DeleteRoom deleteRoom(array $options = [])
 * @method static V20161101\DescribeBoardEvents describeBoardEvents(array $options = [])
 * @method static V20161101\DescribeBoardSnapshot describeBoardSnapshot(array $options = [])
 * @method static V20161101\DescribeBoards describeBoards(array $options = [])
 * @method static V20161101\DescribeCasterChannels describeCasterChannels(array $options = [])
 * @method static V20161101\DescribeCasterComponents describeCasterComponents(array $options = [])
 * @method static V20161101\DescribeCasterConfig describeCasterConfig(array $options = [])
 * @method static V20161101\DescribeCasterLayouts describeCasterLayouts(array $options = [])
 * @method static V20161101\DescribeCasterProgram describeCasterProgram(array $options = [])
 * @method static V20161101\DescribeCasterRtcInfo describeCasterRtcInfo(array $options = [])
 * @method static V20161101\DescribeCasterSceneAudio describeCasterSceneAudio(array $options = [])
 * @method static V20161101\DescribeCasterScenes describeCasterScenes(array $options = [])
 * @method static V20161101\DescribeCasterStreamUrl describeCasterStreamUrl(array $options = [])
 * @method static V20161101\DescribeCasterVideoResources describeCasterVideoResources(array $options = [])
 * @method static V20161101\DescribeCasters describeCasters(array $options = [])
 * @method static V20161101\DescribeDomainConfigs describeDomainConfigs(array $options = [])
 * @method static V20161101\DescribeForbidPushStreamRoomList describeForbidPushStreamRoomList(array $options = [])
 * @method static V20161101\DescribeHlsLiveStreamRealTimeBpsData describeHlsLiveStreamRealTimeBpsData(array $options = [])
 * @method static V20161101\DescribeLiveCertificateDetail describeLiveCertificateDetail(array $options = [])
 * @method static V20161101\DescribeLiveCertificateList describeLiveCertificateList(array $options = [])
 * @method static V20161101\DescribeLiveDetectNotifyConfig describeLiveDetectNotifyConfig(array $options = [])
 * @method static V20161101\DescribeLiveDomainBpsData describeLiveDomainBpsData(array $options = [])
 * @method static V20161101\DescribeLiveDomainConfigs describeLiveDomainConfigs(array $options = [])
 * @method static V20161101\DescribeLiveDomainDetail describeLiveDomainDetail(array $options = [])
 * @method static V20161101\DescribeLiveDomainHttpsData describeLiveDomainHttpsData(array $options = [])
 * @method static V20161101\DescribeLiveDomainMapping describeLiveDomainMapping(array $options = [])
 * @method static V20161101\DescribeLiveDomainRealTimeBpsData describeLiveDomainRealTimeBpsData(array $options = [])
 * @method static V20161101\DescribeLiveDomainRealTimeHttpCodeData describeLiveDomainRealTimeHttpCodeData(array $options = [])
 * @method static V20161101\DescribeLiveDomainRealTimeTrafficData describeLiveDomainRealTimeTrafficData(array $options = [])
 * @method static V20161101\DescribeLiveDomainRecordData describeLiveDomainRecordData(array $options = [])
 * @method static V20161101\DescribeLiveDomainSnapshotData describeLiveDomainSnapshotData(array $options = [])
 * @method static V20161101\DescribeLiveDomainSrcHttpCodeData describeLiveDomainSrcHttpCodeData(array $options = [])
 * @method static V20161101\DescribeLiveDomainTrafficData describeLiveDomainTrafficData(array $options = [])
 * @method static V20161101\DescribeLiveDomainTrancodeData describeLiveDomainTrancodeData(array $options = [])
 * @method static V20161101\DescribeLiveDomainTranscodeData describeLiveDomainTranscodeData(array $options = [])
 * @method static V20161101\DescribeLiveDomainUvData describeLiveDomainUvData(array $options = [])
 * @method static V20161101\DescribeLiveLazyPullStreamConfig describeLiveLazyPullStreamConfig(array $options = [])
 * @method static V20161101\DescribeLivePullStreamConfig describeLivePullStreamConfig(array $options = [])
 * @method static V20161101\DescribeLiveRecordConfig describeLiveRecordConfig(array $options = [])
 * @method static V20161101\DescribeLiveRecordNotifyConfig describeLiveRecordNotifyConfig(array $options = [])
 * @method static V20161101\DescribeLiveRecordVodConfigs describeLiveRecordVodConfigs(array $options = [])
 * @method static V20161101\DescribeLiveSnapshotConfig describeLiveSnapshotConfig(array $options = [])
 * @method static V20161101\DescribeLiveSnapshotDetectPornConfig describeLiveSnapshotDetectPornConfig(array $options = [])
 * @method static V20161101\DescribeLiveStreamBitRateData describeLiveStreamBitRateData(array $options = [])
 * @method static V20161101\DescribeLiveStreamCount describeLiveStreamCount(array $options = [])
 * @method static V20161101\DescribeLiveStreamHistoryUserNum describeLiveStreamHistoryUserNum(array $options = [])
 * @method static V20161101\DescribeLiveStreamOnlineUserNum describeLiveStreamOnlineUserNum(array $options = [])
 * @method static V20161101\DescribeLiveStreamRecordContent describeLiveStreamRecordContent(array $options = [])
 * @method static V20161101\DescribeLiveStreamRecordIndexFile describeLiveStreamRecordIndexFile(array $options = [])
 * @method static V20161101\DescribeLiveStreamRecordIndexFiles describeLiveStreamRecordIndexFiles(array $options = [])
 * @method static V20161101\DescribeLiveStreamSnapshotInfo describeLiveStreamSnapshotInfo(array $options = [])
 * @method static V20161101\DescribeLiveStreamTranscodeInfo describeLiveStreamTranscodeInfo(array $options = [])
 * @method static V20161101\DescribeLiveStreamsBlockList describeLiveStreamsBlockList(array $options = [])
 * @method static V20161101\DescribeLiveStreamsControlHistory describeLiveStreamsControlHistory(array $options = [])
 * @method static V20161101\DescribeLiveStreamsFrameRateAndBitRateData describeLiveStreamsFrameRateAndBitRateData(array $options = [])
 * @method static V20161101\DescribeLiveStreamsNotifyUrlConfig describeLiveStreamsNotifyUrlConfig(array $options = [])
 * @method static V20161101\DescribeLiveStreamsOnlineList describeLiveStreamsOnlineList(array $options = [])
 * @method static V20161101\DescribeLiveStreamsPublishList describeLiveStreamsPublishList(array $options = [])
 * @method static V20161101\DescribeLiveTopDomainsByFlow describeLiveTopDomainsByFlow(array $options = [])
 * @method static V20161101\DescribeLiveTranscodeInfo describeLiveTranscodeInfo(array $options = [])
 * @method static V20161101\DescribeLiveUserDomains describeLiveUserDomains(array $options = [])
 * @method static V20161101\DescribeRecord describeRecord(array $options = [])
 * @method static V20161101\DescribeRecords describeRecords(array $options = [])
 * @method static V20161101\DescribeRoomKickoutUserList describeRoomKickoutUserList(array $options = [])
 * @method static V20161101\DescribeRoomList describeRoomList(array $options = [])
 * @method static V20161101\DescribeRoomStatus describeRoomStatus(array $options = [])
 * @method static V20161101\DescribeUpBpsPeakData describeUpBpsPeakData(array $options = [])
 * @method static V20161101\DescribeUpBpsPeakOfLine describeUpBpsPeakOfLine(array $options = [])
 * @method static V20161101\DescribeUpPeakPublishStreamData describeUpPeakPublishStreamData(array $options = [])
 * @method static V20161101\DescribeUserLiveDomains describeUserLiveDomains(array $options = [])
 * @method static V20161101\EffectCasterUrgent effectCasterUrgent(array $options = [])
 * @method static V20161101\EffectCasterVideoResource effectCasterVideoResource(array $options = [])
 * @method static V20161101\ForbidLiveStream forbidLiveStream(array $options = [])
 * @method static V20161101\ForbidPushStream forbidPushStream(array $options = [])
 * @method static V20161101\JoinBoard joinBoard(array $options = [])
 * @method static V20161101\ModifyCasterComponent modifyCasterComponent(array $options = [])
 * @method static V20161101\ModifyCasterEpisode modifyCasterEpisode(array $options = [])
 * @method static V20161101\ModifyCasterLayout modifyCasterLayout(array $options = [])
 * @method static V20161101\ModifyCasterProgram modifyCasterProgram(array $options = [])
 * @method static V20161101\ModifyCasterVideoResource modifyCasterVideoResource(array $options = [])
 * @method static V20161101\RealTimeRecordCommand realTimeRecordCommand(array $options = [])
 * @method static V20161101\RealTimeSnapshotCommand realTimeSnapshotCommand(array $options = [])
 * @method static V20161101\ResumeLiveStream resumeLiveStream(array $options = [])
 * @method static V20161101\SendRoomNotification sendRoomNotification(array $options = [])
 * @method static V20161101\SendRoomUserNotification sendRoomUserNotification(array $options = [])
 * @method static V20161101\SetCasterChannel setCasterChannel(array $options = [])
 * @method static V20161101\SetCasterConfig setCasterConfig(array $options = [])
 * @method static V20161101\SetCasterSceneConfig setCasterSceneConfig(array $options = [])
 * @method static V20161101\SetLiveDomainCertificate setLiveDomainCertificate(array $options = [])
 * @method static V20161101\SetLiveLazyPullStreamInfoConfig setLiveLazyPullStreamInfoConfig(array $options = [])
 * @method static V20161101\SetLiveStreamsNotifyUrlConfig setLiveStreamsNotifyUrlConfig(array $options = [])
 * @method static V20161101\StartBoardRecord startBoardRecord(array $options = [])
 * @method static V20161101\StartCaster startCaster(array $options = [])
 * @method static V20161101\StartCasterScene startCasterScene(array $options = [])
 * @method static V20161101\StartLiveDomain startLiveDomain(array $options = [])
 * @method static V20161101\StartLiveIndex startLiveIndex(array $options = [])
 * @method static V20161101\StopCaster stopCaster(array $options = [])
 * @method static V20161101\StopCasterScene stopCasterScene(array $options = [])
 * @method static V20161101\StopLiveDomain stopLiveDomain(array $options = [])
 * @method static V20161101\StopLiveIndex stopLiveIndex(array $options = [])
 * @method static V20161101\UpdateBoard updateBoard(array $options = [])
 * @method static V20161101\UpdateCasterSceneAudio updateCasterSceneAudio(array $options = [])
 * @method static V20161101\UpdateCasterSceneConfig updateCasterSceneConfig(array $options = [])
 * @method static V20161101\UpdateLiveAppSnapshotConfig updateLiveAppSnapshotConfig(array $options = [])
 * @method static V20161101\UpdateLiveDetectNotifyConfig updateLiveDetectNotifyConfig(array $options = [])
 * @method static V20161101\UpdateLiveRecordNotifyConfig updateLiveRecordNotifyConfig(array $options = [])
 * @method static V20161101\UpdateLiveSnapshotDetectPornConfig updateLiveSnapshotDetectPornConfig(array $options = [])
 */
class LiveV20161101
{
    use ApiResolverTrait;

    /**
     * @var string
     */
    protected $namespace = 'AlibabaCloud\\Live\\V20161101';
}
