<?php

namespace AlibabaCloud\RKvstore;

use AlibabaCloud\ApiResolverTrait;

/**
 * Find the specified Api of the RKvstore based on the method name as the Api name.
 *
 * @package   AlibabaCloud\RKvstore
 *
 * @method static V20150101\AddBindingTunnel addBindingTunnel(array $options = [])
 * @method static V20150101\AllocateInstancePublicConnection allocateInstancePublicConnection(array $options = [])
 * @method static V20150101\BindTunnel bindTunnel(array $options = [])
 * @method static V20150101\CreateAccount createAccount(array $options = [])
 * @method static V20150101\CreateBackup createBackup(array $options = [])
 * @method static V20150101\CreateCacheAnalysisTask createCacheAnalysisTask(array $options = [])
 * @method static V20150101\CreateInstance createInstance(array $options = [])
 * @method static V20150101\CreateReplicationGroup createReplicationGroup(array $options = [])
 * @method static V20150101\CreateSnapshot createSnapshot(array $options = [])
 * @method static V20150101\CreateStaticVerification createStaticVerification(array $options = [])
 * @method static V20150101\CreateTempInstance createTempInstance(array $options = [])
 * @method static V20150101\DeleteAccount deleteAccount(array $options = [])
 * @method static V20150101\DeleteInstance deleteInstance(array $options = [])
 * @method static V20150101\DeleteReplicationGroup deleteReplicationGroup(array $options = [])
 * @method static V20150101\DeleteSnapshot deleteSnapshot(array $options = [])
 * @method static V20150101\DeleteSnapshotSettings deleteSnapshotSettings(array $options = [])
 * @method static V20150101\DeleteTempInstance deleteTempInstance(array $options = [])
 * @method static V20150101\DescribeAccounts describeAccounts(array $options = [])
 * @method static V20150101\DescribeActiveOperationTask describeActiveOperationTask(array $options = [])
 * @method static V20150101\DescribeActiveOperationTaskCount describeActiveOperationTaskCount(array $options = [])
 * @method static V20150101\DescribeActiveOperationTaskRegion describeActiveOperationTaskRegion(array $options = [])
 * @method static V20150101\DescribeActiveOperationTaskType describeActiveOperationTaskType(array $options = [])
 * @method static V20150101\DescribeAuditRecords describeAuditRecords(array $options = [])
 * @method static V20150101\DescribeBackupPolicy describeBackupPolicy(array $options = [])
 * @method static V20150101\DescribeBackups describeBackups(array $options = [])
 * @method static V20150101\DescribeCacheAnalysisReport describeCacheAnalysisReport(array $options = [])
 * @method static V20150101\DescribeCacheAnalysisReportList describeCacheAnalysisReportList(array $options = [])
 * @method static V20150101\DescribeCertification describeCertification(array $options = [])
 * @method static V20150101\DescribeDBInstanceMonitor describeDBInstanceMonitor(array $options = [])
 * @method static V20150101\DescribeDBInstanceNetInfo describeDBInstanceNetInfo(array $options = [])
 * @method static V20150101\DescribeDynamicVerificationList describeDynamicVerificationList(array $options = [])
 * @method static V20150101\DescribeErrorLogRecords describeErrorLogRecords(array $options = [])
 * @method static V20150101\DescribeHistoryMonitorValues describeHistoryMonitorValues(array $options = [])
 * @method static V20150101\DescribeInstanceAttribute describeInstanceAttribute(array $options = [])
 * @method static V20150101\DescribeInstanceAutoRenewalAttribute describeInstanceAutoRenewalAttribute(array $options = [])
 * @method static V20150101\DescribeInstanceConfig describeInstanceConfig(array $options = [])
 * @method static V20150101\DescribeInstancePerformanceUsage describeInstancePerformanceUsage(array $options = [])
 * @method static V20150101\DescribeInstanceSSL describeInstanceSSL(array $options = [])
 * @method static V20150101\DescribeInstances describeInstances(array $options = [])
 * @method static V20150101\DescribeInstancesByExpireTime describeInstancesByExpireTime(array $options = [])
 * @method static V20150101\DescribeIntranetAttribute describeIntranetAttribute(array $options = [])
 * @method static V20150101\DescribeLogicInstanceTopology describeLogicInstanceTopology(array $options = [])
 * @method static V20150101\DescribeMonitorItems describeMonitorItems(array $options = [])
 * @method static V20150101\DescribeMonthlyServiceStatus describeMonthlyServiceStatus(array $options = [])
 * @method static V20150101\DescribeMonthlyServiceStatusDetail describeMonthlyServiceStatusDetail(array $options = [])
 * @method static V20150101\DescribeParameterModificationHistory describeParameterModificationHistory(array $options = [])
 * @method static V20150101\DescribeParameterTemplates describeParameterTemplates(array $options = [])
 * @method static V20150101\DescribeParameters describeParameters(array $options = [])
 * @method static V20150101\DescribeRdsVSwitchs describeRdsVSwitchs(array $options = [])
 * @method static V20150101\DescribeRdsVpcs describeRdsVpcs(array $options = [])
 * @method static V20150101\DescribeRegions describeRegions(array $options = [])
 * @method static V20150101\DescribeReplicaConflictInfo describeReplicaConflictInfo(array $options = [])
 * @method static V20150101\DescribeReplicaInitializeProgress describeReplicaInitializeProgress(array $options = [])
 * @method static V20150101\DescribeReplicaPerformance describeReplicaPerformance(array $options = [])
 * @method static V20150101\DescribeReplicaUsage describeReplicaUsage(array $options = [])
 * @method static V20150101\DescribeReplicas describeReplicas(array $options = [])
 * @method static V20150101\DescribeReplicationGroup describeReplicationGroup(array $options = [])
 * @method static V20150101\DescribeRunningLogRecords describeRunningLogRecords(array $options = [])
 * @method static V20150101\DescribeSecurityIps describeSecurityIps(array $options = [])
 * @method static V20150101\DescribeSlowLogRecords describeSlowLogRecords(array $options = [])
 * @method static V20150101\DescribeSnapshots describeSnapshots(array $options = [])
 * @method static V20150101\DescribeStaticVerificationList describeStaticVerificationList(array $options = [])
 * @method static V20150101\DescribeStrategy describeStrategy(array $options = [])
 * @method static V20150101\DescribeTargetAVZ describeTargetAVZ(array $options = [])
 * @method static V20150101\DescribeTempInstance describeTempInstance(array $options = [])
 * @method static V20150101\DescribeVerificationList describeVerificationList(array $options = [])
 * @method static V20150101\DescribeZones describeZones(array $options = [])
 * @method static V20150101\DestroyInstance destroyInstance(array $options = [])
 * @method static V20150101\EvaluateFailOverSwitch evaluateFailOverSwitch(array $options = [])
 * @method static V20150101\EvaluateResource evaluateResource(array $options = [])
 * @method static V20150101\FlushExpireKeys flushExpireKeys(array $options = [])
 * @method static V20150101\FlushInstance flushInstance(array $options = [])
 * @method static V20150101\GetSnapshotSettings getSnapshotSettings(array $options = [])
 * @method static V20150101\GrantAccountPrivilege grantAccountPrivilege(array $options = [])
 * @method static V20150101\ListReplicationGroup listReplicationGroup(array $options = [])
 * @method static V20150101\ListTagResources listTagResources(array $options = [])
 * @method static V20150101\MigrateToOtherZone migrateToOtherZone(array $options = [])
 * @method static V20150101\ModifyAccountDescription modifyAccountDescription(array $options = [])
 * @method static V20150101\ModifyActiveOperationPendingTask modifyActiveOperationPendingTask(array $options = [])
 * @method static V20150101\ModifyActiveOperationTask modifyActiveOperationTask(array $options = [])
 * @method static V20150101\ModifyAuditLogConfig modifyAuditLogConfig(array $options = [])
 * @method static V20150101\ModifyBackupPolicy modifyBackupPolicy(array $options = [])
 * @method static V20150101\ModifyCertification modifyCertification(array $options = [])
 * @method static V20150101\ModifyDBInstanceConnectionString modifyDBInstanceConnectionString(array $options = [])
 * @method static V20150101\ModifyDBInstanceMonitor modifyDBInstanceMonitor(array $options = [])
 * @method static V20150101\ModifyDynamicMode modifyDynamicMode(array $options = [])
 * @method static V20150101\ModifyGuardDomainMode modifyGuardDomainMode(array $options = [])
 * @method static V20150101\ModifyInstanceAttribute modifyInstanceAttribute(array $options = [])
 * @method static V20150101\ModifyInstanceAutoRenewalAttribute modifyInstanceAutoRenewalAttribute(array $options = [])
 * @method static V20150101\ModifyInstanceConfig modifyInstanceConfig(array $options = [])
 * @method static V20150101\ModifyInstanceMaintainTime modifyInstanceMaintainTime(array $options = [])
 * @method static V20150101\ModifyInstanceMajorVersion modifyInstanceMajorVersion(array $options = [])
 * @method static V20150101\ModifyInstanceMinorVersion modifyInstanceMinorVersion(array $options = [])
 * @method static V20150101\ModifyInstanceNetExpireTime modifyInstanceNetExpireTime(array $options = [])
 * @method static V20150101\ModifyInstanceSSL modifyInstanceSSL(array $options = [])
 * @method static V20150101\ModifyInstanceSpec modifyInstanceSpec(array $options = [])
 * @method static V20150101\ModifyInstanceSpecPreCheck modifyInstanceSpecPreCheck(array $options = [])
 * @method static V20150101\ModifyInstanceVpcAuthMode modifyInstanceVpcAuthMode(array $options = [])
 * @method static V20150101\ModifyIntranetAttribute modifyIntranetAttribute(array $options = [])
 * @method static V20150101\ModifyReplicaDescription modifyReplicaDescription(array $options = [])
 * @method static V20150101\ModifyReplicaDynamicMode modifyReplicaDynamicMode(array $options = [])
 * @method static V20150101\ModifyReplicaFilterMode modifyReplicaFilterMode(array $options = [])
 * @method static V20150101\ModifyReplicaMode modifyReplicaMode(array $options = [])
 * @method static V20150101\ModifyReplicaRecoverMode modifyReplicaRecoverMode(array $options = [])
 * @method static V20150101\ModifyReplicaRecoveryMode modifyReplicaRecoveryMode(array $options = [])
 * @method static V20150101\ModifyReplicaRelation modifyReplicaRelation(array $options = [])
 * @method static V20150101\ModifyReplicaVerificationMode modifyReplicaVerificationMode(array $options = [])
 * @method static V20150101\ModifyReplicationGroup modifyReplicationGroup(array $options = [])
 * @method static V20150101\ModifySecurityIps modifySecurityIps(array $options = [])
 * @method static V20150101\QueryTask queryTask(array $options = [])
 * @method static V20150101\RebuildInstance rebuildInstance(array $options = [])
 * @method static V20150101\ReleaseInstancePublicConnection releaseInstancePublicConnection(array $options = [])
 * @method static V20150101\ReleaseReplica releaseReplica(array $options = [])
 * @method static V20150101\RenewInstance renewInstance(array $options = [])
 * @method static V20150101\RenewMultiInstance renewMultiInstance(array $options = [])
 * @method static V20150101\ResetAccount resetAccount(array $options = [])
 * @method static V20150101\ResetAccountPassword resetAccountPassword(array $options = [])
 * @method static V20150101\RestartDBInstance restartDBInstance(array $options = [])
 * @method static V20150101\RestartInstance restartInstance(array $options = [])
 * @method static V20150101\RestoreInstance restoreInstance(array $options = [])
 * @method static V20150101\RestoreSnapshot restoreSnapshot(array $options = [])
 * @method static V20150101\RevokeAccountPrivilege revokeAccountPrivilege(array $options = [])
 * @method static V20150101\SetSnapshotSettings setSnapshotSettings(array $options = [])
 * @method static V20150101\SwitchNetwork switchNetwork(array $options = [])
 * @method static V20150101\SwitchTempInstance switchTempInstance(array $options = [])
 * @method static V20150101\TagResources tagResources(array $options = [])
 * @method static V20150101\TransformToPrePaid transformToPrePaid(array $options = [])
 * @method static V20150101\UnbindTunnel unbindTunnel(array $options = [])
 * @method static V20150101\UnlinkReplicaInstance unlinkReplicaInstance(array $options = [])
 * @method static V20150101\UntagResources untagResources(array $options = [])
 * @method static V20150101\VerifyPassword verifyPassword(array $options = [])
 */
class RKvstoreV20150101
{
    use ApiResolverTrait;

    /**
     * @var string
     */
    protected $namespace = 'AlibabaCloud\\RKvstore\\V20150101';
}
