<?php

namespace AlibabaCloud\Cdn;

use AlibabaCloud\ApiResolverTrait;

/**
 * Find the specified Api of the Cdn based on the method name as the Api name.
 *
 * @package   AlibabaCloud\Cdn
 *
 * @method static V20180510\AddCdnDomain addCdnDomain(array $options = [])
 * @method static V20180510\AddFCTrigger addFCTrigger(array $options = [])
 * @method static V20180510\BatchAddCdnDomain batchAddCdnDomain(array $options = [])
 * @method static V20180510\BatchDeleteCdnDomainConfig batchDeleteCdnDomainConfig(array $options = [])
 * @method static V20180510\BatchSetCdnDomainConfig batchSetCdnDomainConfig(array $options = [])
 * @method static V20180510\BatchSetCdnDomainServerCertificate batchSetCdnDomainServerCertificate(array $options = [])
 * @method static V20180510\BatchUpdateCdnDomain batchUpdateCdnDomain(array $options = [])
 * @method static V20180510\CreateUsageDetailDataExportTask createUsageDetailDataExportTask(array $options = [])
 * @method static V20180510\CreateUserUsageDataExportTask createUserUsageDataExportTask(array $options = [])
 * @method static V20180510\DeleteCdnDomain deleteCdnDomain(array $options = [])
 * @method static V20180510\DeleteFCTrigger deleteFCTrigger(array $options = [])
 * @method static V20180510\DeleteUsageDetailDataExportTask deleteUsageDetailDataExportTask(array $options = [])
 * @method static V20180510\DeleteUserUsageDataExportTask deleteUserUsageDataExportTask(array $options = [])
 * @method static V20180510\DescribeCdnCertificateDetail describeCdnCertificateDetail(array $options = [])
 * @method static V20180510\DescribeCdnCertificateList describeCdnCertificateList(array $options = [])
 * @method static V20180510\DescribeCdnDomainBaseDetail describeCdnDomainBaseDetail(array $options = [])
 * @method static V20180510\DescribeCdnDomainConfigs describeCdnDomainConfigs(array $options = [])
 * @method static V20180510\DescribeCdnDomainDetail describeCdnDomainDetail(array $options = [])
 * @method static V20180510\DescribeCdnDomainLogs describeCdnDomainLogs(array $options = [])
 * @method static V20180510\DescribeCdnMonitorData describeCdnMonitorData(array $options = [])
 * @method static V20180510\DescribeCdnRegionAndIsp describeCdnRegionAndIsp(array $options = [])
 * @method static V20180510\DescribeCdnService describeCdnService(array $options = [])
 * @method static V20180510\DescribeCdnUserQuota describeCdnUserQuota(array $options = [])
 * @method static V20180510\DescribeCdnUserResourcePackage describeCdnUserResourcePackage(array $options = [])
 * @method static V20180510\DescribeCustomLogConfig describeCustomLogConfig(array $options = [])
 * @method static V20180510\DescribeDomainAverageResponseTime describeDomainAverageResponseTime(array $options = [])
 * @method static V20180510\DescribeDomainBpsData describeDomainBpsData(array $options = [])
 * @method static V20180510\DescribeDomainBpsDataByTimeStamp describeDomainBpsDataByTimeStamp(array $options = [])
 * @method static V20180510\DescribeDomainCCAttackInfo describeDomainCCAttackInfo(array $options = [])
 * @method static V20180510\DescribeDomainCCData describeDomainCCData(array $options = [])
 * @method static V20180510\DescribeDomainCertificateInfo describeDomainCertificateInfo(array $options = [])
 * @method static V20180510\DescribeDomainCname describeDomainCname(array $options = [])
 * @method static V20180510\DescribeDomainConfigs describeDomainConfigs(array $options = [])
 * @method static V20180510\DescribeDomainCustomLogConfig describeDomainCustomLogConfig(array $options = [])
 * @method static V20180510\DescribeDomainDownstreamBpsOfEdge describeDomainDownstreamBpsOfEdge(array $options = [])
 * @method static V20180510\DescribeDomainFileSizeProportionData describeDomainFileSizeProportionData(array $options = [])
 * @method static V20180510\DescribeDomainHitRateData describeDomainHitRateData(array $options = [])
 * @method static V20180510\DescribeDomainHttpCodeData describeDomainHttpCodeData(array $options = [])
 * @method static V20180510\DescribeDomainISPData describeDomainISPData(array $options = [])
 * @method static V20180510\DescribeDomainMax95BpsData describeDomainMax95BpsData(array $options = [])
 * @method static V20180510\DescribeDomainMonthBillingBpsData describeDomainMonthBillingBpsData(array $options = [])
 * @method static V20180510\DescribeDomainPathData describeDomainPathData(array $options = [])
 * @method static V20180510\DescribeDomainPvData describeDomainPvData(array $options = [])
 * @method static V20180510\DescribeDomainQpsData describeDomainQpsData(array $options = [])
 * @method static V20180510\DescribeDomainRealTimeBpsData describeDomainRealTimeBpsData(array $options = [])
 * @method static V20180510\DescribeDomainRealTimeByteHitRateData describeDomainRealTimeByteHitRateData(array $options = [])
 * @method static V20180510\DescribeDomainRealTimeData describeDomainRealTimeData(array $options = [])
 * @method static V20180510\DescribeDomainRealTimeHttpCodeData describeDomainRealTimeHttpCodeData(array $options = [])
 * @method static V20180510\DescribeDomainRealTimeQpsData describeDomainRealTimeQpsData(array $options = [])
 * @method static V20180510\DescribeDomainRealTimeReqHitRateData describeDomainRealTimeReqHitRateData(array $options = [])
 * @method static V20180510\DescribeDomainRealTimeSrcBpsData describeDomainRealTimeSrcBpsData(array $options = [])
 * @method static V20180510\DescribeDomainRealTimeSrcTrafficData describeDomainRealTimeSrcTrafficData(array $options = [])
 * @method static V20180510\DescribeDomainRegionData describeDomainRegionData(array $options = [])
 * @method static V20180510\DescribeDomainReqHitRateData describeDomainReqHitRateData(array $options = [])
 * @method static V20180510\DescribeDomainSrcBpsData describeDomainSrcBpsData(array $options = [])
 * @method static V20180510\DescribeDomainSrcHttpCodeData describeDomainSrcHttpCodeData(array $options = [])
 * @method static V20180510\DescribeDomainSrcTrafficData describeDomainSrcTrafficData(array $options = [])
 * @method static V20180510\DescribeDomainTopReferVisit describeDomainTopReferVisit(array $options = [])
 * @method static V20180510\DescribeDomainTopUrlVisit describeDomainTopUrlVisit(array $options = [])
 * @method static V20180510\DescribeDomainTrafficData describeDomainTrafficData(array $options = [])
 * @method static V20180510\DescribeDomainUpstreamBpsOfEdge describeDomainUpstreamBpsOfEdge(array $options = [])
 * @method static V20180510\DescribeDomainUpstreamOfCenter describeDomainUpstreamOfCenter(array $options = [])
 * @method static V20180510\DescribeDomainUsageData describeDomainUsageData(array $options = [])
 * @method static V20180510\DescribeDomainUvData describeDomainUvData(array $options = [])
 * @method static V20180510\DescribeDomainsBySource describeDomainsBySource(array $options = [])
 * @method static V20180510\DescribeDomainsUsageByDay describeDomainsUsageByDay(array $options = [])
 * @method static V20180510\DescribeFCTrigger describeFCTrigger(array $options = [])
 * @method static V20180510\DescribeIpInfo describeIpInfo(array $options = [])
 * @method static V20180510\DescribeL2VipsByDomain describeL2VipsByDomain(array $options = [])
 * @method static V20180510\DescribeOneMinuteData describeOneMinuteData(array $options = [])
 * @method static V20180510\DescribeRangeDataByLocateAndIspService describeRangeDataByLocateAndIspService(array $options = [])
 * @method static V20180510\DescribeRealtimeDeliveryAcc describeRealtimeDeliveryAcc(array $options = [])
 * @method static V20180510\DescribeRefreshQuota describeRefreshQuota(array $options = [])
 * @method static V20180510\DescribeRefreshTasks describeRefreshTasks(array $options = [])
 * @method static V20180510\DescribeTopDomainsByFlow describeTopDomainsByFlow(array $options = [])
 * @method static V20180510\DescribeUserConfigs describeUserConfigs(array $options = [])
 * @method static V20180510\DescribeUserDomains describeUserDomains(array $options = [])
 * @method static V20180510\DescribeUserUsageDataExportTask describeUserUsageDataExportTask(array $options = [])
 * @method static V20180510\DescribeUserUsageDetailDataExportTask describeUserUsageDetailDataExportTask(array $options = [])
 * @method static V20180510\GetUserDomainBlackList getUserDomainBlackList(array $options = [])
 * @method static V20180510\ListDomainsByLogConfigId listDomainsByLogConfigId(array $options = [])
 * @method static V20180510\ListFCTrigger listFCTrigger(array $options = [])
 * @method static V20180510\ModifyCdnDomain modifyCdnDomain(array $options = [])
 * @method static V20180510\ModifyCdnService modifyCdnService(array $options = [])
 * @method static V20180510\ModifyCdnSubscribeService modifyCdnSubscribeService(array $options = [])
 * @method static V20180510\ModifyDomainCustomLogConfig modifyDomainCustomLogConfig(array $options = [])
 * @method static V20180510\ModifyFileCacheExpiredConfig modifyFileCacheExpiredConfig(array $options = [])
 * @method static V20180510\ModifyHttpHeaderConfig modifyHttpHeaderConfig(array $options = [])
 * @method static V20180510\ModifyUserCustomLogConfig modifyUserCustomLogConfig(array $options = [])
 * @method static V20180510\OpenCdnService openCdnService(array $options = [])
 * @method static V20180510\PushObjectCache pushObjectCache(array $options = [])
 * @method static V20180510\RefreshObjectCaches refreshObjectCaches(array $options = [])
 * @method static V20180510\SetBusinessFunctionConfig setBusinessFunctionConfig(array $options = [])
 * @method static V20180510\SetCacheExpiredConfig setCacheExpiredConfig(array $options = [])
 * @method static V20180510\SetCcConfig setCcConfig(array $options = [])
 * @method static V20180510\SetDomainGreenManagerConfig setDomainGreenManagerConfig(array $options = [])
 * @method static V20180510\SetDomainServerCertificate setDomainServerCertificate(array $options = [])
 * @method static V20180510\SetErrorPageConfig setErrorPageConfig(array $options = [])
 * @method static V20180510\SetFileCacheExpiredConfig setFileCacheExpiredConfig(array $options = [])
 * @method static V20180510\SetForceRedirectConfig setForceRedirectConfig(array $options = [])
 * @method static V20180510\SetForwardSchemeConfig setForwardSchemeConfig(array $options = [])
 * @method static V20180510\SetHttpErrorPageConfig setHttpErrorPageConfig(array $options = [])
 * @method static V20180510\SetHttpHeaderConfig setHttpHeaderConfig(array $options = [])
 * @method static V20180510\SetHttpsOptionConfig setHttpsOptionConfig(array $options = [])
 * @method static V20180510\SetIgnoreQueryStringConfig setIgnoreQueryStringConfig(array $options = [])
 * @method static V20180510\SetIpAllowListConfig setIpAllowListConfig(array $options = [])
 * @method static V20180510\SetIpBlackListConfig setIpBlackListConfig(array $options = [])
 * @method static V20180510\SetL2OssKeyConfig setL2OssKeyConfig(array $options = [])
 * @method static V20180510\SetLocationAccessRestriction setLocationAccessRestriction(array $options = [])
 * @method static V20180510\SetOptimizeConfig setOptimizeConfig(array $options = [])
 * @method static V20180510\SetPageCompressConfig setPageCompressConfig(array $options = [])
 * @method static V20180510\SetPathCacheExpiredConfig setPathCacheExpiredConfig(array $options = [])
 * @method static V20180510\SetRangeConfig setRangeConfig(array $options = [])
 * @method static V20180510\SetRefererConfig setRefererConfig(array $options = [])
 * @method static V20180510\SetRefererRegexConfig setRefererRegexConfig(array $options = [])
 * @method static V20180510\SetRemoveQueryStringConfig setRemoveQueryStringConfig(array $options = [])
 * @method static V20180510\SetReqAuthConfig setReqAuthConfig(array $options = [])
 * @method static V20180510\SetReqHeaderConfig setReqHeaderConfig(array $options = [])
 * @method static V20180510\SetSourceHostConfig setSourceHostConfig(array $options = [])
 * @method static V20180510\SetVideoSeekConfig setVideoSeekConfig(array $options = [])
 * @method static V20180510\SetWafConfig setWafConfig(array $options = [])
 * @method static V20180510\SetWaitingRoomConfig setWaitingRoomConfig(array $options = [])
 * @method static V20180510\StartCdnDomain startCdnDomain(array $options = [])
 * @method static V20180510\StopCdnDomain stopCdnDomain(array $options = [])
 * @method static V20180510\TagResources tagResources(array $options = [])
 * @method static V20180510\UntagResources untagResources(array $options = [])
 * @method static V20180510\UpdateFCTrigger updateFCTrigger(array $options = [])
 */
class CdnV20180510
{
    use ApiResolverTrait;

    /**
     * @var string
     */
    protected $namespace = 'AlibabaCloud\\Cdn\\V20180510';
}
