<?php

namespace AlibabaCloud\Cdn;

use AlibabaCloud\ApiResolverTrait;

/**
 * Find the specified Api of the Cdn based on the method name as the Api name.
 *
 * @package   AlibabaCloud\Cdn
 *
 * @method V20141111\AddCdnDomain addCdnDomain(array $options = [])
 * @method V20141111\AddFCTrigger addFCTrigger(array $options = [])
 * @method V20141111\AddLiveAppRecordConfig addLiveAppRecordConfig(array $options = [])
 * @method V20141111\AddLiveAppSnapshotConfig addLiveAppSnapshotConfig(array $options = [])
 * @method V20141111\AddLiveDomainMapping addLiveDomainMapping(array $options = [])
 * @method V20141111\AddLiveStreamTranscode addLiveStreamTranscode(array $options = [])
 * @method V20141111\BatchDeleteCdnDomainConfig batchDeleteCdnDomainConfig(array $options = [])
 * @method V20141111\BatchDescribeDomainCname batchDescribeDomainCname(array $options = [])
 * @method V20141111\BatchSetCdnDomainConfig batchSetCdnDomainConfig(array $options = [])
 * @method V20141111\CreateLiveStreamRecordIndexFiles createLiveStreamRecordIndexFiles(array $options = [])
 * @method V20141111\DeleteCacheExpiredConfig deleteCacheExpiredConfig(array $options = [])
 * @method V20141111\DeleteCdnDomain deleteCdnDomain(array $options = [])
 * @method V20141111\DeleteCertificate deleteCertificate(array $options = [])
 * @method V20141111\DeleteFCTrigger deleteFCTrigger(array $options = [])
 * @method V20141111\DeleteHttpHeaderConfig deleteHttpHeaderConfig(array $options = [])
 * @method V20141111\DeleteLiveAppRecordConfig deleteLiveAppRecordConfig(array $options = [])
 * @method V20141111\DeleteLiveAppSnapshotConfig deleteLiveAppSnapshotConfig(array $options = [])
 * @method V20141111\DeleteLiveDomainMapping deleteLiveDomainMapping(array $options = [])
 * @method V20141111\DeleteLiveStreamTranscode deleteLiveStreamTranscode(array $options = [])
 * @method V20141111\DeleteSpecificConfig deleteSpecificConfig(array $options = [])
 * @method V20141111\DescribeCdnDomainConfigs describeCdnDomainConfigs(array $options = [])
 * @method V20141111\DescribeCdnDomainDetail describeCdnDomainDetail(array $options = [])
 * @method V20141111\DescribeCdnDomainLogs describeCdnDomainLogs(array $options = [])
 * @method V20141111\DescribeCdnMonitorData describeCdnMonitorData(array $options = [])
 * @method V20141111\DescribeCdnMonthSubscribe describeCdnMonthSubscribe(array $options = [])
 * @method V20141111\DescribeCdnRegionAndIsp describeCdnRegionAndIsp(array $options = [])
 * @method V20141111\DescribeCdnService describeCdnService(array $options = [])
 * @method V20141111\DescribeCdnUserBillInfo describeCdnUserBillInfo(array $options = [])
 * @method V20141111\DescribeCdnUserQuota describeCdnUserQuota(array $options = [])
 * @method V20141111\DescribeCdnUserSubscribe describeCdnUserSubscribe(array $options = [])
 * @method V20141111\DescribeCdnWeekSubscribe describeCdnWeekSubscribe(array $options = [])
 * @method V20141111\DescribeCustomLogConfig describeCustomLogConfig(array $options = [])
 * @method V20141111\DescribeDomainAverageResponseTime describeDomainAverageResponseTime(array $options = [])
 * @method V20141111\DescribeDomainBpsData describeDomainBpsData(array $options = [])
 * @method V20141111\DescribeDomainBpsDataByTimeStamp describeDomainBpsDataByTimeStamp(array $options = [])
 * @method V20141111\DescribeDomainCCData describeDomainCCData(array $options = [])
 * @method V20141111\DescribeDomainCertificateInfo describeDomainCertificateInfo(array $options = [])
 * @method V20141111\DescribeDomainCname describeDomainCname(array $options = [])
 * @method V20141111\DescribeDomainConfigs describeDomainConfigs(array $options = [])
 * @method V20141111\DescribeDomainCustomLogConfig describeDomainCustomLogConfig(array $options = [])
 * @method V20141111\DescribeDomainFileSizeProportionData describeDomainFileSizeProportionData(array $options = [])
 * @method V20141111\DescribeDomainFlowData describeDomainFlowData(array $options = [])
 * @method V20141111\DescribeDomainHitRateData describeDomainHitRateData(array $options = [])
 * @method V20141111\DescribeDomainHttpCodeData describeDomainHttpCodeData(array $options = [])
 * @method V20141111\DescribeDomainISPData describeDomainISPData(array $options = [])
 * @method V20141111\DescribeDomainMax95BpsData describeDomainMax95BpsData(array $options = [])
 * @method V20141111\DescribeDomainPathData describeDomainPathData(array $options = [])
 * @method V20141111\DescribeDomainPvData describeDomainPvData(array $options = [])
 * @method V20141111\DescribeDomainQpsData describeDomainQpsData(array $options = [])
 * @method V20141111\DescribeDomainRealTimeBpsData describeDomainRealTimeBpsData(array $options = [])
 * @method V20141111\DescribeDomainRealTimeByteHitRateData describeDomainRealTimeByteHitRateData(array $options = [])
 * @method V20141111\DescribeDomainRealTimeHttpCodeData describeDomainRealTimeHttpCodeData(array $options = [])
 * @method V20141111\DescribeDomainRealTimeQpsData describeDomainRealTimeQpsData(array $options = [])
 * @method V20141111\DescribeDomainRealTimeReqHitRateData describeDomainRealTimeReqHitRateData(array $options = [])
 * @method V20141111\DescribeDomainRealTimeSrcBpsData describeDomainRealTimeSrcBpsData(array $options = [])
 * @method V20141111\DescribeDomainRealTimeSrcTrafficData describeDomainRealTimeSrcTrafficData(array $options = [])
 * @method V20141111\DescribeDomainRegionData describeDomainRegionData(array $options = [])
 * @method V20141111\DescribeDomainReqHitRateData describeDomainReqHitRateData(array $options = [])
 * @method V20141111\DescribeDomainSlowRatio describeDomainSlowRatio(array $options = [])
 * @method V20141111\DescribeDomainSrcBpsData describeDomainSrcBpsData(array $options = [])
 * @method V20141111\DescribeDomainSrcFlowData describeDomainSrcFlowData(array $options = [])
 * @method V20141111\DescribeDomainTopReferVisit describeDomainTopReferVisit(array $options = [])
 * @method V20141111\DescribeDomainTopUrlVisit describeDomainTopUrlVisit(array $options = [])
 * @method V20141111\DescribeDomainUvData describeDomainUvData(array $options = [])
 * @method V20141111\DescribeDomainsBySource describeDomainsBySource(array $options = [])
 * @method V20141111\DescribeDomainsUsageByDay describeDomainsUsageByDay(array $options = [])
 * @method V20141111\DescribeFCTrigger describeFCTrigger(array $options = [])
 * @method V20141111\DescribeIpInfo describeIpInfo(array $options = [])
 * @method V20141111\DescribeL2VipsByDomain describeL2VipsByDomain(array $options = [])
 * @method V20141111\DescribeL2VipsByDynamicDomain describeL2VipsByDynamicDomain(array $options = [])
 * @method V20141111\DescribeLivePullStreamConfig describeLivePullStreamConfig(array $options = [])
 * @method V20141111\DescribeLiveRecordConfig describeLiveRecordConfig(array $options = [])
 * @method V20141111\DescribeLiveSnapshotConfig describeLiveSnapshotConfig(array $options = [])
 * @method V20141111\DescribeLiveStreamBitRateData describeLiveStreamBitRateData(array $options = [])
 * @method V20141111\DescribeLiveStreamHistoryUserNumber describeLiveStreamHistoryUserNumber(array $options = [])
 * @method V20141111\DescribeLiveStreamOnlineUserNum describeLiveStreamOnlineUserNum(array $options = [])
 * @method V20141111\DescribeLiveStreamRecordContent describeLiveStreamRecordContent(array $options = [])
 * @method V20141111\DescribeLiveStreamRecordIndexFile describeLiveStreamRecordIndexFile(array $options = [])
 * @method V20141111\DescribeLiveStreamRecordIndexFiles describeLiveStreamRecordIndexFiles(array $options = [])
 * @method V20141111\DescribeLiveStreamSnapshotInfo describeLiveStreamSnapshotInfo(array $options = [])
 * @method V20141111\DescribeLiveStreamTranscodeInfo describeLiveStreamTranscodeInfo(array $options = [])
 * @method V20141111\DescribeLiveStreamsBlockList describeLiveStreamsBlockList(array $options = [])
 * @method V20141111\DescribeLiveStreamsControlHistory describeLiveStreamsControlHistory(array $options = [])
 * @method V20141111\DescribeLiveStreamsFrameRateAndBitRateData describeLiveStreamsFrameRateAndBitRateData(array $options = [])
 * @method V20141111\DescribeLiveStreamsOnlineList describeLiveStreamsOnlineList(array $options = [])
 * @method V20141111\DescribeLiveStreamsPublishList describeLiveStreamsPublishList(array $options = [])
 * @method V20141111\DescribeRangeDataByLocateAndIspService describeRangeDataByLocateAndIspService(array $options = [])
 * @method V20141111\DescribeRefreshQuota describeRefreshQuota(array $options = [])
 * @method V20141111\DescribeRefreshTasks describeRefreshTasks(array $options = [])
 * @method V20141111\DescribeScdnService describeScdnService(array $options = [])
 * @method V20141111\DescribeTopDomainsByFlow describeTopDomainsByFlow(array $options = [])
 * @method V20141111\DescribeUserConfigs describeUserConfigs(array $options = [])
 * @method V20141111\DescribeUserCustomLogConfig describeUserCustomLogConfig(array $options = [])
 * @method V20141111\DescribeUserCustomerLabels describeUserCustomerLabels(array $options = [])
 * @method V20141111\DescribeUserDomains describeUserDomains(array $options = [])
 * @method V20141111\ForbidLiveStream forbidLiveStream(array $options = [])
 * @method V20141111\ListDomainsByLogConfigId listDomainsByLogConfigId(array $options = [])
 * @method V20141111\ListFCTrigger listFCTrigger(array $options = [])
 * @method V20141111\ModifyCdnDomain modifyCdnDomain(array $options = [])
 * @method V20141111\ModifyCdnService modifyCdnService(array $options = [])
 * @method V20141111\ModifyCdnSubscribeService modifyCdnSubscribeService(array $options = [])
 * @method V20141111\ModifyDomainCustomLogConfig modifyDomainCustomLogConfig(array $options = [])
 * @method V20141111\ModifyFileCacheExpiredConfig modifyFileCacheExpiredConfig(array $options = [])
 * @method V20141111\ModifyHttpHeaderConfig modifyHttpHeaderConfig(array $options = [])
 * @method V20141111\ModifyPathCacheExpiredConfig modifyPathCacheExpiredConfig(array $options = [])
 * @method V20141111\ModifyUserCustomLogConfig modifyUserCustomLogConfig(array $options = [])
 * @method V20141111\OpenCdnService openCdnService(array $options = [])
 * @method V20141111\OpenCdnSubscribeService openCdnSubscribeService(array $options = [])
 * @method V20141111\PushObjectCache pushObjectCache(array $options = [])
 * @method V20141111\RefreshObjectCaches refreshObjectCaches(array $options = [])
 * @method V20141111\ResumeLiveStream resumeLiveStream(array $options = [])
 * @method V20141111\SetBusinessFunctionConfig setBusinessFunctionConfig(array $options = [])
 * @method V20141111\SetCacheExpiredConfig setCacheExpiredConfig(array $options = [])
 * @method V20141111\SetCcConfig setCcConfig(array $options = [])
 * @method V20141111\SetDomainFiletypeForceTtlCodeConfig setDomainFiletypeForceTtlCodeConfig(array $options = [])
 * @method V20141111\SetDomainGreenManagerConfig setDomainGreenManagerConfig(array $options = [])
 * @method V20141111\SetDomainPathForceTtlCodeConfig setDomainPathForceTtlCodeConfig(array $options = [])
 * @method V20141111\SetDomainServerCertificate setDomainServerCertificate(array $options = [])
 * @method V20141111\SetDynamicConfig setDynamicConfig(array $options = [])
 * @method V20141111\SetErrorPageConfig setErrorPageConfig(array $options = [])
 * @method V20141111\SetFileCacheExpiredConfig setFileCacheExpiredConfig(array $options = [])
 * @method V20141111\SetForceRedirectConfig setForceRedirectConfig(array $options = [])
 * @method V20141111\SetForwardSchemeConfig setForwardSchemeConfig(array $options = [])
 * @method V20141111\SetHttpErrorPageConfig setHttpErrorPageConfig(array $options = [])
 * @method V20141111\SetHttpHeaderConfig setHttpHeaderConfig(array $options = [])
 * @method V20141111\SetHttpsOptionConfig setHttpsOptionConfig(array $options = [])
 * @method V20141111\SetIgnoreQueryStringConfig setIgnoreQueryStringConfig(array $options = [])
 * @method V20141111\SetIpAllowListConfig setIpAllowListConfig(array $options = [])
 * @method V20141111\SetIpBlackListConfig setIpBlackListConfig(array $options = [])
 * @method V20141111\SetIpWhiteListConfig setIpWhiteListConfig(array $options = [])
 * @method V20141111\SetL2OssKeyConfig setL2OssKeyConfig(array $options = [])
 * @method V20141111\SetLiveStreamsNotifyUrlConfig setLiveStreamsNotifyUrlConfig(array $options = [])
 * @method V20141111\SetOptimizeConfig setOptimizeConfig(array $options = [])
 * @method V20141111\SetPageCompressConfig setPageCompressConfig(array $options = [])
 * @method V20141111\SetPathCacheExpiredConfig setPathCacheExpiredConfig(array $options = [])
 * @method V20141111\SetRangeConfig setRangeConfig(array $options = [])
 * @method V20141111\SetRefererConfig setRefererConfig(array $options = [])
 * @method V20141111\SetRefererRegexConfig setRefererRegexConfig(array $options = [])
 * @method V20141111\SetRemoveQueryStringConfig setRemoveQueryStringConfig(array $options = [])
 * @method V20141111\SetReqAuthConfig setReqAuthConfig(array $options = [])
 * @method V20141111\SetReqHeaderConfig setReqHeaderConfig(array $options = [])
 * @method V20141111\SetSourceHostConfig setSourceHostConfig(array $options = [])
 * @method V20141111\SetUserGreenManagerConfig setUserGreenManagerConfig(array $options = [])
 * @method V20141111\SetVideoSeekConfig setVideoSeekConfig(array $options = [])
 * @method V20141111\SetWaitingRoomConfig setWaitingRoomConfig(array $options = [])
 * @method V20141111\StartCdnDomain startCdnDomain(array $options = [])
 * @method V20141111\StartMixStreamsService startMixStreamsService(array $options = [])
 * @method V20141111\StopCdnDomain stopCdnDomain(array $options = [])
 * @method V20141111\StopCdnSubscribeService stopCdnSubscribeService(array $options = [])
 * @method V20141111\StopMixStreamsService stopMixStreamsService(array $options = [])
 * @method V20141111\UpdateFCTrigger updateFCTrigger(array $options = [])
 * @method V20141111\UpdateLiveAppSnapshotConfig updateLiveAppSnapshotConfig(array $options = [])
 */
class CdnV20141111ApiResolver
{
    use ApiResolverTrait;

    /**
     * @var string
     */
    protected $namespace = 'AlibabaCloud\\Cdn\\V20141111';
}
