<?php

namespace AlibabaCloud\CCC;

use AlibabaCloud\ApiResolverTrait;

/**
 * Find the specified Api of the CCC based on the method name as the Api name.
 *
 * @package   AlibabaCloud\CCC
 *
 * @method static V20170705\AddNumberToSkillGroup addNumberToSkillGroup(array $options = [])
 * @method static V20170705\AddPhoneNumber addPhoneNumber(array $options = [])
 * @method static V20170705\AssignJobs assignJobs(array $options = [])
 * @method static V20170705\AssignUsers assignUsers(array $options = [])
 * @method static V20170705\CallOnlinePrivacyNumber callOnlinePrivacyNumber(array $options = [])
 * @method static V20170705\CancelJobs cancelJobs(array $options = [])
 * @method static V20170705\CancelPredictiveJobs cancelPredictiveJobs(array $options = [])
 * @method static V20170705\CommitContactFlowVersionModification commitContactFlowVersionModification(array $options = [])
 * @method static V20170705\CreateAndPublishSpecialContactFlow createAndPublishSpecialContactFlow(array $options = [])
 * @method static V20170705\CreateBatchJobs createBatchJobs(array $options = [])
 * @method static V20170705\CreateCCCPostOrder createCCCPostOrder(array $options = [])
 * @method static V20170705\CreateContactFlow createContactFlow(array $options = [])
 * @method static V20170705\CreateInstance createInstance(array $options = [])
 * @method static V20170705\CreateJobGroup createJobGroup(array $options = [])
 * @method static V20170705\CreateMedia createMedia(array $options = [])
 * @method static V20170705\CreatePredictiveJobs createPredictiveJobs(array $options = [])
 * @method static V20170705\CreateScenario createScenario(array $options = [])
 * @method static V20170705\CreateScenarioFromTemplate createScenarioFromTemplate(array $options = [])
 * @method static V20170705\CreateSkillGroup createSkillGroup(array $options = [])
 * @method static V20170705\CreateSurvey createSurvey(array $options = [])
 * @method static V20170705\CreateUser createUser(array $options = [])
 * @method static V20170705\DeleteInstance deleteInstance(array $options = [])
 * @method static V20170705\DeleteJobGroup deleteJobGroup(array $options = [])
 * @method static V20170705\DeleteMedia deleteMedia(array $options = [])
 * @method static V20170705\DeleteSkillGroup deleteSkillGroup(array $options = [])
 * @method static V20170705\DeleteSurvey deleteSurvey(array $options = [])
 * @method static V20170705\Dialogue dialogue(array $options = [])
 * @method static V20170705\DownloadOriginalStatisticsReport downloadOriginalStatisticsReport(array $options = [])
 * @method static V20170705\DownloadRecording downloadRecording(array $options = [])
 * @method static V20170705\DownloadUnreachableContacts downloadUnreachableContacts(array $options = [])
 * @method static V20170705\FindUsers findUsers(array $options = [])
 * @method static V20170705\GenerateAgentStatisticReport generateAgentStatisticReport(array $options = [])
 * @method static V20170705\GetAgentData getAgentData(array $options = [])
 * @method static V20170705\GetAgentState getAgentState(array $options = [])
 * @method static V20170705\GetCallMeasureSummaryReport getCallMeasureSummaryReport(array $options = [])
 * @method static V20170705\GetConfig getConfig(array $options = [])
 * @method static V20170705\GetContactIdentifyByOutBoundTaskId getContactIdentifyByOutBoundTaskId(array $options = [])
 * @method static V20170705\GetConversationDetailByContactId getConversationDetailByContactId(array $options = [])
 * @method static V20170705\GetConversationList getConversationList(array $options = [])
 * @method static V20170705\GetInstance getInstance(array $options = [])
 * @method static V20170705\GetInstanceState getInstanceState(array $options = [])
 * @method static V20170705\GetInstanceSummaryReport getInstanceSummaryReport(array $options = [])
 * @method static V20170705\GetInstanceSummaryReportByInterval getInstanceSummaryReportByInterval(array $options = [])
 * @method static V20170705\GetInstanceSummaryReportSinceMidnight getInstanceSummaryReportSinceMidnight(array $options = [])
 * @method static V20170705\GetJob getJob(array $options = [])
 * @method static V20170705\GetJobDataUploadParams getJobDataUploadParams(array $options = [])
 * @method static V20170705\GetJobGroup getJobGroup(array $options = [])
 * @method static V20170705\GetJobList getJobList(array $options = [])
 * @method static V20170705\GetJobStatusByCallId getJobStatusByCallId(array $options = [])
 * @method static V20170705\GetJobTemplateDownloadParams getJobTemplateDownloadParams(array $options = [])
 * @method static V20170705\GetNumberRegionInfo getNumberRegionInfo(array $options = [])
 * @method static V20170705\GetPredictiveJob getPredictiveJob(array $options = [])
 * @method static V20170705\GetScenario getScenario(array $options = [])
 * @method static V20170705\GetServiceExtensions getServiceExtensions(array $options = [])
 * @method static V20170705\GetSmsConfig getSmsConfig(array $options = [])
 * @method static V20170705\GetSurvey getSurvey(array $options = [])
 * @method static V20170705\GetTaskList getTaskList(array $options = [])
 * @method static V20170705\GetUser getUser(array $options = [])
 * @method static V20170705\LaunchAppraise launchAppraise(array $options = [])
 * @method static V20170705\LaunchShortMessageAppraise launchShortMessageAppraise(array $options = [])
 * @method static V20170705\ListAgentStates listAgentStates(array $options = [])
 * @method static V20170705\ListAgentSummaryReports listAgentSummaryReports(array $options = [])
 * @method static V20170705\ListAgentSummaryReportsByInterval listAgentSummaryReportsByInterval(array $options = [])
 * @method static V20170705\ListAgentSummaryReportsSinceMidnight listAgentSummaryReportsSinceMidnight(array $options = [])
 * @method static V20170705\ListBasicStatisticsReportSubItems listBasicStatisticsReportSubItems(array $options = [])
 * @method static V20170705\ListCallDetailRecords listCallDetailRecords(array $options = [])
 * @method static V20170705\ListCallMeasureSummaryReports listCallMeasureSummaryReports(array $options = [])
 * @method static V20170705\ListConfig listConfig(array $options = [])
 * @method static V20170705\ListContactFlows listContactFlows(array $options = [])
 * @method static V20170705\ListIvrTrackingDetail listIvrTrackingDetail(array $options = [])
 * @method static V20170705\ListJobGroups listJobGroups(array $options = [])
 * @method static V20170705\ListJobStatus listJobStatus(array $options = [])
 * @method static V20170705\ListJobsByGroup listJobsByGroup(array $options = [])
 * @method static V20170705\ListMedias listMedias(array $options = [])
 * @method static V20170705\ListOutboundPhoneNumberOfUser listOutboundPhoneNumberOfUser(array $options = [])
 * @method static V20170705\ListPhoneNumbers listPhoneNumbers(array $options = [])
 * @method static V20170705\ListPredictiveJobStatus listPredictiveJobStatus(array $options = [])
 * @method static V20170705\ListPrivacyNumberCallDetails listPrivacyNumberCallDetails(array $options = [])
 * @method static V20170705\ListPrivilegesOfUser listPrivilegesOfUser(array $options = [])
 * @method static V20170705\ListRealTimeAgent listRealTimeAgent(array $options = [])
 * @method static V20170705\ListRecentCallRecords listRecentCallRecords(array $options = [])
 * @method static V20170705\ListRecordingOfDualTrack listRecordingOfDualTrack(array $options = [])
 * @method static V20170705\ListRecordings listRecordings(array $options = [])
 * @method static V20170705\ListRecordingsByContactId listRecordingsByContactId(array $options = [])
 * @method static V20170705\ListRoles listRoles(array $options = [])
 * @method static V20170705\ListScenarioTemplates listScenarioTemplates(array $options = [])
 * @method static V20170705\ListScenarios listScenarios(array $options = [])
 * @method static V20170705\ListSkillGroupStates listSkillGroupStates(array $options = [])
 * @method static V20170705\ListSkillGroupSummaryReports listSkillGroupSummaryReports(array $options = [])
 * @method static V20170705\ListSkillGroupSummaryReportsByInterval listSkillGroupSummaryReportsByInterval(array $options = [])
 * @method static V20170705\ListSkillGroupSummaryReportsSinceMidnight listSkillGroupSummaryReportsSinceMidnight(array $options = [])
 * @method static V20170705\ListSkillGroups listSkillGroups(array $options = [])
 * @method static V20170705\ListSkillGroupsOfUser listSkillGroupsOfUser(array $options = [])
 * @method static V20170705\ListSurveys listSurveys(array $options = [])
 * @method static V20170705\ListUnreachableContacts listUnreachableContacts(array $options = [])
 * @method static V20170705\ListUsers listUsers(array $options = [])
 * @method static V20170705\ListUsersOfSkillGroup listUsersOfSkillGroup(array $options = [])
 * @method static V20170705\ModifyMedia modifyMedia(array $options = [])
 * @method static V20170705\ModifyNotificationConfig modifyNotificationConfig(array $options = [])
 * @method static V20170705\ModifyPhoneNumber modifyPhoneNumber(array $options = [])
 * @method static V20170705\ModifyPrivacyNumberCallDetail modifyPrivacyNumberCallDetail(array $options = [])
 * @method static V20170705\ModifyScenario modifyScenario(array $options = [])
 * @method static V20170705\ModifySkillGroup modifySkillGroup(array $options = [])
 * @method static V20170705\ModifySkillGroupOfUser modifySkillGroupOfUser(array $options = [])
 * @method static V20170705\ModifySurvey modifySurvey(array $options = [])
 * @method static V20170705\ModifyUser modifyUser(array $options = [])
 * @method static V20170705\PickLocalNumber pickLocalNumber(array $options = [])
 * @method static V20170705\PickOutboundNumbers pickOutboundNumbers(array $options = [])
 * @method static V20170705\PreCreateMedia preCreateMedia(array $options = [])
 * @method static V20170705\PreModifyMedia preModifyMedia(array $options = [])
 * @method static V20170705\PublishContactFlowVersion publishContactFlowVersion(array $options = [])
 * @method static V20170705\PublishSurvey publishSurvey(array $options = [])
 * @method static V20170705\QueryRedialIndicator queryRedialIndicator(array $options = [])
 * @method static V20170705\RefreshToken refreshToken(array $options = [])
 * @method static V20170705\RemoveNumberFromSkillGroup removeNumberFromSkillGroup(array $options = [])
 * @method static V20170705\RemovePhoneNumber removePhoneNumber(array $options = [])
 * @method static V20170705\RemoveUsers removeUsers(array $options = [])
 * @method static V20170705\RemoveUsersFromSkillGroup removeUsersFromSkillGroup(array $options = [])
 * @method static V20170705\RequestLoginInfo requestLoginInfo(array $options = [])
 * @method static V20170705\ResumeJobs resumeJobs(array $options = [])
 * @method static V20170705\SendPredefinedShortMessage sendPredefinedShortMessage(array $options = [])
 * @method static V20170705\SimpleDial simpleDial(array $options = [])
 * @method static V20170705\StartBack2BackCall startBack2BackCall(array $options = [])
 * @method static V20170705\StartJob startJob(array $options = [])
 * @method static V20170705\SubmitBatchJobs submitBatchJobs(array $options = [])
 * @method static V20170705\SuspendJobs suspendJobs(array $options = [])
 * @method static V20170705\TwoPartiesCall twoPartiesCall(array $options = [])
 */
class CCCV20170705
{
    use ApiResolverTrait;

    /**
     * @var string
     */
    protected $namespace = 'AlibabaCloud\\CCC\\V20170705';
}
