<?php

namespace AlibabaCloud;

use AlibabaCloud\Client\AlibabaCloud;

/**
 * Find service based on the static method name as service name.
 *
 * @package   AlibabaCloud
 *
 * @mixin     AlibabaCloud
 *
 * @codeCoverageIgnore
 *
 * @method static ARMS\ARMS aRMS()
 * @method static ARMS4FINANCE\ARMS4FINANCE aRMS4FINANCE()
 * @method static Aegis\Aegis aegis()
 * @method static Afs\Afs afs()
 * @method static Airec\Airec airec()
 * @method static Alidns\Alidns alidns()
 * @method static Alimt\Alimt alimt()
 * @method static Baas\Baas baas()
 * @method static BatchCompute\BatchCompute batchCompute()
 * @method static BssOpenApi\BssOpenApi bssOpenApi()
 * @method static CCC\CCC cCC()
 * @method static CS\CS cS()
 * @method static CSB\CSB cSB()
 * @method static Ccs\Ccs ccs()
 * @method static Cdn\Cdn cdn()
 * @method static Chatbot\Chatbot chatbot()
 * @method static CloudAPI\CloudAPI cloudAPI()
 * @method static CloudPhoto\CloudPhoto cloudPhoto()
 * @method static Cloudauth\Cloudauth cloudauth()
 * @method static Cloudesl\Cloudesl cloudesl()
 * @method static Cms\Cms cms()
 * @method static Crm\Crm crm()
 * @method static Dcdn\Dcdn dcdn()
 * @method static Dds\Dds dds()
 * @method static Dm\Dm dm()
 * @method static DmsEnterprise\DmsEnterprise dmsEnterprise()
 * @method static Domain\Domain domain()
 * @method static DomainIntl\DomainIntl domainIntl()
 * @method static Drds\Drds drds()
 * @method static Dts\Dts dts()
 * @method static Dybaseapi\Dybaseapi dybaseapi()
 * @method static Dysmsapi\Dysmsapi dysmsapi()
 * @method static Dyvmsapi\Dyvmsapi dyvmsapi()
 * @method static EHPC\EHPC eHPC()
 * @method static Eci\Eci eci()
 * @method static Ecs\Ecs ecs()
 * @method static EcsInc\EcsInc ecsInc()
 * @method static Ess\Ess ess()
 * @method static Green\Green green()
 * @method static Hsm\Hsm hsm()
 * @method static Httpdns\Httpdns httpdns()
 * @method static IDST\IDST iDST()
 * @method static ImageSearch\ImageSearch imageSearch()
 * @method static Imm\Imm imm()
 * @method static Iot\Iot iot()
 * @method static Jaq\Jaq jaq()
 * @method static Jarvis\Jarvis jarvis()
 * @method static LinkFace\LinkFace linkFace()
 * @method static Linkedmall\Linkedmall linkedmall()
 * @method static Live\Live live()
 * @method static Lubancloud\Lubancloud lubancloud()
 * @method static Market\Market market()
 * @method static Mts\Mts mts()
 * @method static NAS\NAS nAS()
 * @method static Nlp\Nlp nlp()
 * @method static NlsCloudMeta\NlsCloudMeta nlsCloudMeta()
 * @method static NlsFiletrans\NlsFiletrans nlsFiletrans()
 * @method static Ons\Ons ons()
 * @method static Ots\Ots ots()
 * @method static Push\Push push()
 * @method static Pvtz\Pvtz pvtz()
 * @method static RKvstore\RKvstore rKvstore()
 * @method static Ram\Ram ram()
 * @method static Rds\Rds rds()
 * @method static Rtc\Rtc rtc()
 * @method static Saf\Saf saf()
 * @method static SasApi\SasApi sasApi()
 * @method static Scdn\Scdn scdn()
 * @method static Skyeye\Skyeye skyeye()
 * @method static Slb\Slb slb()
 * @method static Smartag\Smartag smartag()
 * @method static Sms\Sms sms()
 * @method static Sts\Sts sts()
 * @method static TagINner\TagINner tagINner()
 * @method static TeslaDam\TeslaDam teslaDam()
 * @method static TeslaMaxCompute\TeslaMaxCompute teslaMaxCompute()
 * @method static TeslaStream\TeslaStream teslaStream()
 * @method static Ubsms\Ubsms ubsms()
 * @method static UbsmsInner\UbsmsInner ubsmsInner()
 * @method static Uis\Uis uis()
 * @method static Vod\Vod vod()
 * @method static Vpc\Vpc vpc()
 * @method static YqBridge\YqBridge yqBridge()
 */
trait ServiceResolverTrait
{
}
