<?php

namespace AlibabaCloud\Aegis;

use AlibabaCloud\ApiResolverTrait;

/**
 * Find the specified Api of the Aegis based on the method name as the Api name.
 *
 * @package   AlibabaCloud\Aegis
 *
 * @method static V20161111\AutoUpgradeSas autoUpgradeSas(array $options = [])
 * @method static V20161111\BatchDeleteWhiteList batchDeleteWhiteList(array $options = [])
 * @method static V20161111\CreatScreenSetting creatScreenSetting(array $options = [])
 * @method static V20161111\CreateCondition createCondition(array $options = [])
 * @method static V20161111\CreateInstance createInstance(array $options = [])
 * @method static V20161111\CreateLogQuery createLogQuery(array $options = [])
 * @method static V20161111\CreateOrUpdateGroup createOrUpdateGroup(array $options = [])
 * @method static V20161111\CreateOrUpdateRule createOrUpdateRule(array $options = [])
 * @method static V20161111\CreateSuspiciousExport createSuspiciousExport(array $options = [])
 * @method static V20161111\CreateTypeWhiteList createTypeWhiteList(array $options = [])
 * @method static V20161111\CreateUserSetting createUserSetting(array $options = [])
 * @method static V20161111\CreateUserWhiteList createUserWhiteList(array $options = [])
 * @method static V20161111\DeleteCondition deleteCondition(array $options = [])
 * @method static V20161111\DeleteCustomizeReport deleteCustomizeReport(array $options = [])
 * @method static V20161111\DeleteLogQuery deleteLogQuery(array $options = [])
 * @method static V20161111\DeleteRule deleteRule(array $options = [])
 * @method static V20161111\DeleteRuleGroup deleteRuleGroup(array $options = [])
 * @method static V20161111\DeleteScreenSetting deleteScreenSetting(array $options = [])
 * @method static V20161111\DeleteSearchCondition deleteSearchCondition(array $options = [])
 * @method static V20161111\DeleteStrategy deleteStrategy(array $options = [])
 * @method static V20161111\DescribeAlarmEventDetail describeAlarmEventDetail(array $options = [])
 * @method static V20161111\DescribeAlarmEventList describeAlarmEventList(array $options = [])
 * @method static V20161111\DescribeAllRegionsStatistics describeAllRegionsStatistics(array $options = [])
 * @method static V20161111\DescribeApiBuySummary describeApiBuySummary(array $options = [])
 * @method static V20161111\DescribeAssetDetailByUuid describeAssetDetailByUuid(array $options = [])
 * @method static V20161111\DescribeAssetList describeAssetList(array $options = [])
 * @method static V20161111\DescribeAssetSummary describeAssetSummary(array $options = [])
 * @method static V20161111\DescribeAttackAnalysisData describeAttackAnalysisData(array $options = [])
 * @method static V20161111\DescribeBuySummary describeBuySummary(array $options = [])
 * @method static V20161111\DescribeConcernNecessity describeConcernNecessity(array $options = [])
 * @method static V20161111\DescribeCustomizeReportChartData describeCustomizeReportChartData(array $options = [])
 * @method static V20161111\DescribeCustomizeReportChartList describeCustomizeReportChartList(array $options = [])
 * @method static V20161111\DescribeCustomizeReportConfigDetail describeCustomizeReportConfigDetail(array $options = [])
 * @method static V20161111\DescribeCustomizeReportList describeCustomizeReportList(array $options = [])
 * @method static V20161111\DescribeDataSource describeDataSource(array $options = [])
 * @method static V20161111\DescribeEmgNotice describeEmgNotice(array $options = [])
 * @method static V20161111\DescribeEmgUserAgreement describeEmgUserAgreement(array $options = [])
 * @method static V20161111\DescribeEmgVulGroup describeEmgVulGroup(array $options = [])
 * @method static V20161111\DescribeEventCountCurve describeEventCountCurve(array $options = [])
 * @method static V20161111\DescribeEventLevelCount describeEventLevelCount(array $options = [])
 * @method static V20161111\DescribeExportInfo describeExportInfo(array $options = [])
 * @method static V20161111\DescribeFilterFields describeFilterFields(array $options = [])
 * @method static V20161111\DescribeGroupList describeGroupList(array $options = [])
 * @method static V20161111\DescribeHistogram describeHistogram(array $options = [])
 * @method static V20161111\DescribeHostTotalCount describeHostTotalCount(array $options = [])
 * @method static V20161111\DescribeHostWafs describeHostWafs(array $options = [])
 * @method static V20161111\DescribeHosts describeHosts(array $options = [])
 * @method static V20161111\DescribeInstanceStatistics describeInstanceStatistics(array $options = [])
 * @method static V20161111\DescribeLogInfo describeLogInfo(array $options = [])
 * @method static V20161111\DescribeLogItems describeLogItems(array $options = [])
 * @method static V20161111\DescribeLogMeta describeLogMeta(array $options = [])
 * @method static V20161111\DescribeLogQuery describeLogQuery(array $options = [])
 * @method static V20161111\DescribeLogShipperStatus describeLogShipperStatus(array $options = [])
 * @method static V20161111\DescribeLoginLogs describeLoginLogs(array $options = [])
 * @method static V20161111\DescribeMacConfig describeMacConfig(array $options = [])
 * @method static V20161111\DescribeMachineConfig describeMachineConfig(array $options = [])
 * @method static V20161111\DescribeNsasSuspEventType describeNsasSuspEventType(array $options = [])
 * @method static V20161111\DescribeOperateInfo describeOperateInfo(array $options = [])
 * @method static V20161111\DescribePropertyScheduleConfig describePropertyScheduleConfig(array $options = [])
 * @method static V20161111\DescribePropertyUserDetail describePropertyUserDetail(array $options = [])
 * @method static V20161111\DescribeQuaraFile describeQuaraFile(array $options = [])
 * @method static V20161111\DescribeRiskType describeRiskType(array $options = [])
 * @method static V20161111\DescribeRiskWhiteList describeRiskWhiteList(array $options = [])
 * @method static V20161111\DescribeRisks describeRisks(array $options = [])
 * @method static V20161111\DescribeRuleList describeRuleList(array $options = [])
 * @method static V20161111\DescribeSasAssetStatistics describeSasAssetStatistics(array $options = [])
 * @method static V20161111\DescribeSasAssetStatisticsColumn describeSasAssetStatisticsColumn(array $options = [])
 * @method static V20161111\DescribeSasLeftCondition describeSasLeftCondition(array $options = [])
 * @method static V20161111\DescribeScreenAlarmEventList describeScreenAlarmEventList(array $options = [])
 * @method static V20161111\DescribeScreenAttackAnalysisData describeScreenAttackAnalysisData(array $options = [])
 * @method static V20161111\DescribeScreenScoreThread describeScreenScoreThread(array $options = [])
 * @method static V20161111\DescribeScreenSecurityStatInfo describeScreenSecurityStatInfo(array $options = [])
 * @method static V20161111\DescribeScreenSetting describeScreenSetting(array $options = [])
 * @method static V20161111\DescribeScreenSettings describeScreenSettings(array $options = [])
 * @method static V20161111\DescribeScreenSummaryInfo describeScreenSummaryInfo(array $options = [])
 * @method static V20161111\DescribeSearchCondition describeSearchCondition(array $options = [])
 * @method static V20161111\DescribeSecurityStatInfo describeSecurityStatInfo(array $options = [])
 * @method static V20161111\DescribeStrategy describeStrategy(array $options = [])
 * @method static V20161111\DescribeStrategyExecDetail describeStrategyExecDetail(array $options = [])
 * @method static V20161111\DescribeStrategyTarget describeStrategyTarget(array $options = [])
 * @method static V20161111\DescribeStratety describeStratety(array $options = [])
 * @method static V20161111\DescribeStratetyDetail describeStratetyDetail(array $options = [])
 * @method static V20161111\DescribeSummaryInfo describeSummaryInfo(array $options = [])
 * @method static V20161111\DescribeSuspEventDetail describeSuspEventDetail(array $options = [])
 * @method static V20161111\DescribeSuspEventExportInfo describeSuspEventExportInfo(array $options = [])
 * @method static V20161111\DescribeSuspEventQuaraFiles describeSuspEventQuaraFiles(array $options = [])
 * @method static V20161111\DescribeSuspEventTypes describeSuspEventTypes(array $options = [])
 * @method static V20161111\DescribeSuspEventUserSetting describeSuspEventUserSetting(array $options = [])
 * @method static V20161111\DescribeSuspEvents describeSuspEvents(array $options = [])
 * @method static V20161111\DescribeSuspTrendStatistics describeSuspTrendStatistics(array $options = [])
 * @method static V20161111\DescribeSuspiciousEvents describeSuspiciousEvents(array $options = [])
 * @method static V20161111\DescribeSuspiciousExportInfo describeSuspiciousExportInfo(array $options = [])
 * @method static V20161111\DescribeSuspiciousOverallConfig describeSuspiciousOverallConfig(array $options = [])
 * @method static V20161111\DescribeSuspiciousUUIDConfig describeSuspiciousUUIDConfig(array $options = [])
 * @method static V20161111\DescribeTopRiskyAssets describeTopRiskyAssets(array $options = [])
 * @method static V20161111\DescribeTotalStatistics describeTotalStatistics(array $options = [])
 * @method static V20161111\DescribeUserSetting describeUserSetting(array $options = [])
 * @method static V20161111\DescribeUserTypeWhiteList describeUserTypeWhiteList(array $options = [])
 * @method static V20161111\DescribeUserWhiteList describeUserWhiteList(array $options = [])
 * @method static V20161111\DescribeUuidConfig describeUuidConfig(array $options = [])
 * @method static V20161111\DescribeUuidStatistics describeUuidStatistics(array $options = [])
 * @method static V20161111\DescribeVersionConfig describeVersionConfig(array $options = [])
 * @method static V20161111\DescribeVulDetails describeVulDetails(array $options = [])
 * @method static V20161111\DescribeVulList describeVulList(array $options = [])
 * @method static V20161111\DescribeVulnerabilitySummary describeVulnerabilitySummary(array $options = [])
 * @method static V20161111\DescribeWarning describeWarning(array $options = [])
 * @method static V20161111\DescribeWebLockBindList describeWebLockBindList(array $options = [])
 * @method static V20161111\DescribeWebLockConfigList describeWebLockConfigList(array $options = [])
 * @method static V20161111\DescribeWebLockEvents describeWebLockEvents(array $options = [])
 * @method static V20161111\DescribeWebLockMachineList describeWebLockMachineList(array $options = [])
 * @method static V20161111\DescribeWebLockStatus describeWebLockStatus(array $options = [])
 * @method static V20161111\DescribeWebshell describeWebshell(array $options = [])
 * @method static V20161111\DescribeYesterdayStatistics describeYesterdayStatistics(array $options = [])
 * @method static V20161111\Describesummary describesummary(array $options = [])
 * @method static V20161111\DownloadLog downloadLog(array $options = [])
 * @method static V20161111\ExecStrategy execStrategy(array $options = [])
 * @method static V20161111\ExportSuspEvents exportSuspEvents(array $options = [])
 * @method static V20161111\ExportWarning exportWarning(array $options = [])
 * @method static V20161111\GetAccountStatistics getAccountStatistics(array $options = [])
 * @method static V20161111\GetCrackStatistics getCrackStatistics(array $options = [])
 * @method static V20161111\GetEntityList getEntityList(array $options = [])
 * @method static V20161111\GetStatistics getStatistics(array $options = [])
 * @method static V20161111\GetStatisticsByUuid getStatisticsByUuid(array $options = [])
 * @method static V20161111\ModifyAssetGroup modifyAssetGroup(array $options = [])
 * @method static V20161111\ModifyBatchIgnoreVul modifyBatchIgnoreVul(array $options = [])
 * @method static V20161111\ModifyConcernNecessity modifyConcernNecessity(array $options = [])
 * @method static V20161111\ModifyEmgVulSubmit modifyEmgVulSubmit(array $options = [])
 * @method static V20161111\ModifyLogMetaStatus modifyLogMetaStatus(array $options = [])
 * @method static V20161111\ModifyMachineConfig modifyMachineConfig(array $options = [])
 * @method static V20161111\ModifyOpenLogShipper modifyOpenLogShipper(array $options = [])
 * @method static V20161111\ModifySasAssetStatisticsColumn modifySasAssetStatisticsColumn(array $options = [])
 * @method static V20161111\ModifyScreenSetting modifyScreenSetting(array $options = [])
 * @method static V20161111\ModifySearchCondition modifySearchCondition(array $options = [])
 * @method static V20161111\ModifyStrategy modifyStrategy(array $options = [])
 * @method static V20161111\ModifyStrategyTarget modifyStrategyTarget(array $options = [])
 * @method static V20161111\ModifyWebLockCreateConfig modifyWebLockCreateConfig(array $options = [])
 * @method static V20161111\ModifyWebLockDeleteConfig modifyWebLockDeleteConfig(array $options = [])
 * @method static V20161111\ModifyWebLockMachineList modifyWebLockMachineList(array $options = [])
 * @method static V20161111\ModifyWebLockRefresh modifyWebLockRefresh(array $options = [])
 * @method static V20161111\ModifyWebLockStatus modifyWebLockStatus(array $options = [])
 * @method static V20161111\ModifyWebLockUpdateConfig modifyWebLockUpdateConfig(array $options = [])
 * @method static V20161111\OperateSuspiciousEvent operateSuspiciousEvent(array $options = [])
 * @method static V20161111\OperateSuspiciousOverallConfig operateSuspiciousOverallConfig(array $options = [])
 * @method static V20161111\OperateSuspiciousTargetConfig operateSuspiciousTargetConfig(array $options = [])
 * @method static V20161111\OperateWarning operateWarning(array $options = [])
 * @method static V20161111\OperateWebVul operateWebVul(array $options = [])
 * @method static V20161111\OperationCustomizeReportChart operationCustomizeReportChart(array $options = [])
 * @method static V20161111\OperationSuspEvents operationSuspEvents(array $options = [])
 * @method static V20161111\PushAllTask pushAllTask(array $options = [])
 * @method static V20161111\QueryCrackEvent queryCrackEvent(array $options = [])
 * @method static V20161111\QueryLoginEvent queryLoginEvent(array $options = [])
 * @method static V20161111\ReleaseInstance releaseInstance(array $options = [])
 * @method static V20161111\RenewInstance renewInstance(array $options = [])
 * @method static V20161111\RollbackQuaraFile rollbackQuaraFile(array $options = [])
 * @method static V20161111\RollbackSuspEventQuaraFile rollbackSuspEventQuaraFile(array $options = [])
 * @method static V20161111\SaveCustomizeReportConfig saveCustomizeReportConfig(array $options = [])
 * @method static V20161111\SaveSuspEventUserSetting saveSuspEventUserSetting(array $options = [])
 * @method static V20161111\TransformLeakage transformLeakage(array $options = [])
 * @method static V20161111\UpdateCustomizeReportStatus updateCustomizeReportStatus(array $options = [])
 * @method static V20161111\UpgradeInstance upgradeInstance(array $options = [])
 */
class AegisV20161111
{
    use ApiResolverTrait;

    /**
     * @var string
     */
    protected $namespace = 'AlibabaCloud\\Aegis\\V20161111';
}
