<?php

namespace AlibabaCloud\CCC\V20170705;

use AlibabaCloud\ApiResolverTrait;

/**
 * Resolve Api based on the method name.
 *
 * @method ListAgentEvents listAgentEvents(array $options = [])
 * @method PickOutboundNumbersByTags pickOutboundNumbersByTags(array $options = [])
 * @method GetJobFileUploadUrl getJobFileUploadUrl(array $options = [])
 * @method CreatePredictiveJobGroup createPredictiveJobGroup(array $options = [])
 * @method AddBulkPhoneNumbers addBulkPhoneNumbers(array $options = [])
 * @method PickNumbersByTags pickNumbersByTags(array $options = [])
 * @method CreateCabInstance createCabInstance(array $options = [])
 * @method ListIvrTrackingDetail listIvrTrackingDetail(array $options = [])
 * @method PickOutboundNumbers pickOutboundNumbers(array $options = [])
 * @method QueryRedialIndicator queryRedialIndicator(array $options = [])
 * @method GetAgentState getAgentState(array $options = [])
 * @method AddNumberToSkillGroup addNumberToSkillGroup(array $options = [])
 * @method RemoveNumberFromSkillGroup removeNumberFromSkillGroup(array $options = [])
 * @method ListRecordingOfDualTrack listRecordingOfDualTrack(array $options = [])
 * @method RemoveUsersFromSkillGroup removeUsersFromSkillGroup(array $options = [])
 * @method ListCallMeasureSummaryReports listCallMeasureSummaryReports(array $options = [])
 * @method GetCallMeasureSummaryReport getCallMeasureSummaryReport(array $options = [])
 * @method CallOnlinePrivacyNumber callOnlinePrivacyNumber(array $options = [])
 * @method ModifyPrivacyNumberCallDetail modifyPrivacyNumberCallDetail(array $options = [])
 * @method ListPrivacyNumberCallDetails listPrivacyNumberCallDetails(array $options = [])
 * @method DeleteMedia deleteMedia(array $options = [])
 * @method ModifyMedia modifyMedia(array $options = [])
 * @method PreModifyMedia preModifyMedia(array $options = [])
 * @method ListMedias listMedias(array $options = [])
 * @method CreateMedia createMedia(array $options = [])
 * @method PreCreateMedia preCreateMedia(array $options = [])
 * @method CreateCCCPostOrder createCCCPostOrder(array $options = [])
 * @method FindUsers findUsers(array $options = [])
 * @method ModifyNotificationConfig modifyNotificationConfig(array $options = [])
 * @method ModifySkillGroupOfUser modifySkillGroupOfUser(array $options = [])
 * @method ListOutboundPhoneNumberOfUser listOutboundPhoneNumberOfUser(array $options = [])
 * @method GetInstanceState getInstanceState(array $options = [])
 * @method SimpleDial simpleDial(array $options = [])
 * @method CreateInstance createInstance(array $options = [])
 * @method DeleteInstance deleteInstance(array $options = [])
 * @method GetInstance getInstance(array $options = [])
 * @method CreateContactFlow createContactFlow(array $options = [])
 * @method CommitContactFlowVersionModification commitContactFlowVersionModification(array $options = [])
 * @method PublishContactFlowVersion publishContactFlowVersion(array $options = [])
 * @method GetPredictiveJob getPredictiveJob(array $options = [])
 * @method GetContactIdentifyByOutBoundTaskId getContactIdentifyByOutBoundTaskId(array $options = [])
 * @method ListSkillGroupStates listSkillGroupStates(array $options = [])
 * @method GetInstanceSummaryReportSinceMidnight getInstanceSummaryReportSinceMidnight(array $options = [])
 * @method GetInstanceSummaryReportByInterval getInstanceSummaryReportByInterval(array $options = [])
 * @method GetInstanceSummaryReport getInstanceSummaryReport(array $options = [])
 * @method ListSkillGroupSummaryReportsByInterval listSkillGroupSummaryReportsByInterval(array $options = [])
 * @method ListSkillGroupSummaryReportsSinceMidnight listSkillGroupSummaryReportsSinceMidnight(array $options = [])
 * @method ListAgentSummaryReportsSinceMidnight listAgentSummaryReportsSinceMidnight(array $options = [])
 * @method ListSkillGroupSummaryReports listSkillGroupSummaryReports(array $options = [])
 * @method ListAgentSummaryReportsByInterval listAgentSummaryReportsByInterval(array $options = [])
 * @method ListAgentSummaryReports listAgentSummaryReports(array $options = [])
 * @method ListAgentStates listAgentStates(array $options = [])
 * @method GetSmsConfig getSmsConfig(array $options = [])
 * @method ListRecentCallRecords listRecentCallRecords(array $options = [])
 * @method SendPredefinedShortMessage sendPredefinedShortMessage(array $options = [])
 * @method LaunchShortMessageAppraise launchShortMessageAppraise(array $options = [])
 * @method GetConversationDetailByContactId getConversationDetailByContactId(array $options = [])
 * @method DeleteJobGroup deleteJobGroup(array $options = [])
 * @method ModifyScenario modifyScenario(array $options = [])
 * @method ListPredictiveJobStatus listPredictiveJobStatus(array $options = [])
 * @method CreatePredictiveJobs createPredictiveJobs(array $options = [])
 * @method CancelPredictiveJobs cancelPredictiveJobs(array $options = [])
 * @method GetJobTemplateDownloadParams getJobTemplateDownloadParams(array $options = [])
 * @method GetScenario getScenario(array $options = [])
 * @method PublishSurvey publishSurvey(array $options = [])
 * @method ModifySurvey modifySurvey(array $options = [])
 * @method ListSurveys listSurveys(array $options = [])
 * @method GetSurvey getSurvey(array $options = [])
 * @method DeleteSurvey deleteSurvey(array $options = [])
 * @method CreateSurvey createSurvey(array $options = [])
 * @method ListBasicStatisticsReportSubItems listBasicStatisticsReportSubItems(array $options = [])
 * @method ListUnreachableContacts listUnreachableContacts(array $options = [])
 * @method DownloadUnreachableContacts downloadUnreachableContacts(array $options = [])
 * @method DownloadOriginalStatisticsReport downloadOriginalStatisticsReport(array $options = [])
 * @method ListPrivilegesOfUser listPrivilegesOfUser(array $options = [])
 * @method GenerateAgentStatisticReport generateAgentStatisticReport(array $options = [])
 * @method StartBack2BackCall startBack2BackCall(array $options = [])
 * @method TwoPartiesCall twoPartiesCall(array $options = [])
 * @method GetAgentData getAgentData(array $options = [])
 * @method GetJobGroup getJobGroup(array $options = [])
 * @method ListScenarioTemplates listScenarioTemplates(array $options = [])
 * @method CreateScenarioFromTemplate createScenarioFromTemplate(array $options = [])
 * @method SuspendJobs suspendJobs(array $options = [])
 * @method SubmitBatchJobs submitBatchJobs(array $options = [])
 * @method ResumeJobs resumeJobs(array $options = [])
 * @method ListJobsByGroup listJobsByGroup(array $options = [])
 * @method CreateBatchJobs createBatchJobs(array $options = [])
 * @method CancelJobs cancelJobs(array $options = [])
 * @method AssignJobs assignJobs(array $options = [])
 * @method GetJobDataUploadParams getJobDataUploadParams(array $options = [])
 * @method LaunchAppraise launchAppraise(array $options = [])
 * @method GetTaskList getTaskList(array $options = [])
 * @method GetJobList getJobList(array $options = [])
 * @method GetConversationList getConversationList(array $options = [])
 * @method GetJob getJob(array $options = [])
 * @method ListRealTimeAgent listRealTimeAgent(array $options = [])
 * @method ListConfig listConfig(array $options = [])
 * @method ListScenarios listScenarios(array $options = [])
 * @method CreateScenario createScenario(array $options = [])
 * @method PickLocalNumber pickLocalNumber(array $options = [])
 * @method GetNumberRegionInfo getNumberRegionInfo(array $options = [])
 * @method Dialogue dialogue(array $options = [])
 * @method CreateJobGroup createJobGroup(array $options = [])
 * @method ListJobGroups listJobGroups(array $options = [])
 * @method GetJobStatusByCallId getJobStatusByCallId(array $options = [])
 * @method ListJobStatus listJobStatus(array $options = [])
 * @method StartJob startJob(array $options = [])
 * @method ListRecordingsByContactId listRecordingsByContactId(array $options = [])
 * @method DownloadRecording downloadRecording(array $options = [])
 * @method ListCallDetailRecords listCallDetailRecords(array $options = [])
 * @method ListRecordings listRecordings(array $options = [])
 * @method RefreshToken refreshToken(array $options = [])
 * @method RemovePhoneNumber removePhoneNumber(array $options = [])
 * @method ModifyUser modifyUser(array $options = [])
 * @method ModifySkillGroup modifySkillGroup(array $options = [])
 * @method ModifyPhoneNumber modifyPhoneNumber(array $options = [])
 * @method RemoveUsers removeUsers(array $options = [])
 * @method ListUsersOfSkillGroup listUsersOfSkillGroup(array $options = [])
 * @method RequestLoginInfo requestLoginInfo(array $options = [])
 * @method ListUsers listUsers(array $options = [])
 * @method ListSkillGroupsOfUser listSkillGroupsOfUser(array $options = [])
 * @method ListSkillGroups listSkillGroups(array $options = [])
 * @method ListRoles listRoles(array $options = [])
 * @method ListPhoneNumbers listPhoneNumbers(array $options = [])
 * @method ListContactFlows listContactFlows(array $options = [])
 * @method GetUser getUser(array $options = [])
 * @method GetServiceExtensions getServiceExtensions(array $options = [])
 * @method GetConfig getConfig(array $options = [])
 * @method DeleteSkillGroup deleteSkillGroup(array $options = [])
 * @method CreateUser createUser(array $options = [])
 * @method CreateSkillGroup createSkillGroup(array $options = [])
 * @method AssignUsers assignUsers(array $options = [])
 * @method AddPhoneNumber addPhoneNumber(array $options = [])
 */
class CCCApiResolver
{
    use ApiResolverTrait;
}
