<?php

namespace AlibabaCloud\Qualitycheck\V20190115;

use AlibabaCloud\ApiResolverTrait;

/**
 * Resolve Api based on the method name.
 *
 * @method OpenService openService(array $options = [])
 * @method GetResultToReview getResultToReview(array $options = [])
 * @method CreateRule createRule(array $options = [])
 * @method GetNextResultToReview getNextResultToReview(array $options = [])
 * @method CloseService closeService(array $options = [])
 * @method UploadAudioData uploadAudioData(array $options = [])
 * @method SaveReviewResult saveReviewResult(array $options = [])
 * @method UploadAudioData4Pre uploadAudioData4Pre(array $options = [])
 * @method AddThesaurusForApi addThesaurusForApi(array $options = [])
 * @method GenerateCustomizationModelId generateCustomizationModelId(array $options = [])
 * @method RemoveAndGetTaskRules removeAndGetTaskRules(array $options = [])
 * @method SubmitReviewInfo submitReviewInfo(array $options = [])
 * @method GetAudioDataStatus getAudioDataStatus(array $options = [])
 * @method ReviewSingleResultById reviewSingleResultById(array $options = [])
 * @method UploadDataSync uploadDataSync(array $options = [])
 * @method SaveConfigDataSet saveConfigDataSet(array $options = [])
 * @method UpdateSubScoreForApi updateSubScoreForApi(array $options = [])
 * @method ConfigDataSet configDataSet(array $options = [])
 * @method UploadRule uploadRule(array $options = [])
 * @method InsertScoreForApi insertScoreForApi(array $options = [])
 * @method SubmitModelTestTask submitModelTestTask(array $options = [])
 * @method InsertSubScoreForApi insertSubScoreForApi(array $options = [])
 * @method DelRuleCategory delRuleCategory(array $options = [])
 * @method GetAccAsrResult getAccAsrResult(array $options = [])
 * @method TestRule testRule(array $options = [])
 * @method ExchangeAudio exchangeAudio(array $options = [])
 * @method GetPocTestReport getPocTestReport(array $options = [])
 * @method GetRuleDetail getRuleDetail(array $options = [])
 * @method UpdateAsrVocab updateAsrVocab(array $options = [])
 * @method UpdateRuleForAnt updateRuleForAnt(array $options = [])
 * @method GetRecognizeResult getRecognizeResult(array $options = [])
 * @method GetOssHeader getOssHeader(array $options = [])
 * @method GetBusinessCategoryList getBusinessCategoryList(array $options = [])
 * @method InvalidRule invalidRule(array $options = [])
 * @method UpdateOnPurchaseSuccess updateOnPurchaseSuccess(array $options = [])
 * @method DeleteSubScoreForApi deleteSubScoreForApi(array $options = [])
 * @method GetThesaurusBySynonymForApi getThesaurusBySynonymForApi(array $options = [])
 * @method CreateAsrVocab createAsrVocab(array $options = [])
 * @method ListDataSetTask listDataSetTask(array $options = [])
 * @method DelThesaurusForApi delThesaurusForApi(array $options = [])
 * @method SubmitAudioLabel submitAudioLabel(array $options = [])
 * @method DeleteAsrVocab deleteAsrVocab(array $options = [])
 * @method GetAudioUrl getAudioUrl(array $options = [])
 * @method AddRuleCategory addRuleCategory(array $options = [])
 * @method AddUploadDataSet addUploadDataSet(array $options = [])
 * @method GetRuleDimension getRuleDimension(array $options = [])
 * @method GetResultCount getResultCount(array $options = [])
 * @method EditThesaurusForApi editThesaurusForApi(array $options = [])
 * @method GetCustomizationConfigList getCustomizationConfigList(array $options = [])
 * @method ExecuteAsrTransform executeAsrTransform(array $options = [])
 * @method GetScoreInfo getScoreInfo(array $options = [])
 * @method AddBusinessCategory addBusinessCategory(array $options = [])
 * @method UploadData uploadData(array $options = [])
 * @method GetAsrVocab getAsrVocab(array $options = [])
 * @method UploadAudioDataWithRules uploadAudioDataWithRules(array $options = [])
 * @method DoLogicalDeleteResource doLogicalDeleteResource(array $options = [])
 * @method GetReviewInfo getReviewInfo(array $options = [])
 * @method GetResult getResult(array $options = [])
 * @method SubmitQualityCheckTask submitQualityCheckTask(array $options = [])
 * @method GetRuleCategory getRuleCategory(array $options = [])
 * @method GetDataSetList getDataSetList(array $options = [])
 * @method GetRule getRule(array $options = [])
 * @method UploadRuleForAnt uploadRuleForAnt(array $options = [])
 * @method SubmitCustomizationConfig submitCustomizationConfig(array $options = [])
 * @method GetTaskFileResultList getTaskFileResultList(array $options = [])
 * @method DoPhysicalDeleteResource doPhysicalDeleteResource(array $options = [])
 * @method UpdateScoreForApi updateScoreForApi(array $options = [])
 * @method DeleteDataSet deleteDataSet(array $options = [])
 * @method DeleteCustomizationConfig deleteCustomizationConfig(array $options = [])
 * @method UploadDataWithRules uploadDataWithRules(array $options = [])
 * @method ValidateRoleSet validateRoleSet(array $options = [])
 * @method DoCheckResource doCheckResource(array $options = [])
 * @method DeleteBusinessCategory deleteBusinessCategory(array $options = [])
 * @method RegisterNotice registerNotice(array $options = [])
 * @method GetDataSetOssHeader getDataSetOssHeader(array $options = [])
 * @method GetTaskRuleList getTaskRuleList(array $options = [])
 * @method GetAudioContentInfo getAudioContentInfo(array $options = [])
 * @method UploadAudioDataWithRules4Pre uploadAudioDataWithRules4Pre(array $options = [])
 * @method GetFileDimension getFileDimension(array $options = [])
 * @method GetResultReviewList getResultReviewList(array $options = [])
 * @method DeleteScoreForApi deleteScoreForApi(array $options = [])
 * @method UpdateRule updateRule(array $options = [])
 * @method GetUserGroup getUserGroup(array $options = [])
 * @method TestNetwork testNetwork(array $options = [])
 */
class QualitycheckApiResolver
{
    use ApiResolverTrait;
}
